const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'../../'+p),'utf8');
const index=read('index.html'),section=index.slice(index.indexOf('<section id="view-auto"'),index.indexOf('\n  <section id="view-reports"',index.indexOf('<section id="view-auto"'))).replace('class="view sf-auto-workspace"','class="view active sf-auto-workspace"');
const planning=index.slice(index.indexOf('let autoPlanPreview=[];'),index.indexOf('\nfunction renderOverviewStats()',index.indexOf('let autoPlanPreview=[];')));
async function fixture(page,theme='dark'){
 await page.route('https://schichtfunk.de/__auto-plan-workspace-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__auto-plan-workspace-fixture');
 await page.setContent(`<meta name="viewport" content="width=device-width,initial-scale=1"><div id="appShell"><main class="main"><div class="content">${section}</div></main></div>`);
 await page.addStyleTag({content:index.match(/<style>\n([\s\S]*?)<\/style>/)[1]});await page.addStyleTag({content:read('assets/manager-theme-v1.css')});await page.addStyleTag({content:read('assets/date-month-controls-v1.css')});await page.addStyleTag({content:read('assets/auto-plan-period-v1.css')});await page.addStyleTag({content:'.main{padding:20px}body{height:auto}#appShell{min-width:0}button:disabled{cursor:not-allowed}'});await page.evaluate(t=>document.documentElement.dataset.sfTheme=t,theme);
 await page.addScriptTag({content:`window.weekStart=new Date(2026,8,28);window.assignments=[];window.employees=[{id:'test',first:'Fiktive',last:'Person',status:'active',employment:'Vollzeit',shifts:['FD'],weeklyHours:40}];window.TYPES=[{id:'FD',name:'Frühdienst',start:'06:00',end:'14:00'}];window.absences=[];window.globalSoll={};window.dailySoll={};window.iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');window.addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};window.typeById=t=>TYPES.find(x=>x.id===t);window.getSoll=()=>1;window.assignmentsFor=(d,t)=>assignments.filter(a=>a.date===d&&a.type===t);window.absent=()=>false;window.plannedAssignmentHours=()=>8;window.employeeMonthlyTarget=()=>180;window.plannedMonthlyHoursForEmployee=(id,date,simulated=[])=>[...assignments,...simulated].filter(a=>a.employeeId===id&&a.date.startsWith(date.slice(0,7))).length*8;window.showSaveToast=()=>{};window.saveCalls=0;window.saveAll=()=>saveCalls++;window.renderCalendar=()=>{};window.openedView=null;window.showView=v=>openedView=v;window.SFBackend={companyId:${JSON.stringify(theme==='dark'?'a':'b')}};window.selectedMonth=null;window.SchichtFunkCalendarView={setMonth:v=>selectedMonth=v,setMode:()=>{}};`});
 await page.addScriptTag({content:read('assets/date-month-format-v1.js')});await page.addScriptTag({content:planning});await page.addScriptTag({content:read('assets/employee-rhythm-v1.js')});await page.addScriptTag({content:read('assets/supabase-auto-plan-guard-v1.js')});await page.addScriptTag({content:read('assets/auto-plan-workspace-v1.js')});
 await page.addScriptTag({content:read('assets/month-optimizer-core-v1.js')});await page.addScriptTag({content:read('assets/month-optimizer-v1.js')});
 await page.locator('#autoPlanPeriod').selectOption('month');await page.locator('#autoPlanMonth').fill('2026-12');await page.locator('#autoPlanMonth').dispatchEvent('change');
}
for(const theme of ['dark','light'])test(`clear month selection, preview review and confirmed draft in ${theme} theme`,async({page})=>{
 await fixture(page,theme);await expect(page.locator('#autoPlanWeekField')).toBeHidden();await expect(page.locator('#autoPlanDateField')).toBeHidden();await expect(page.locator('#autoPlanMonthField')).toBeVisible();await expect(page.locator('#autoPeriodRange')).toHaveText('Dezember 2026');await expect(page.locator('#autoPeriodDates')).toContainText('1.12.2026 bis 31.12.2026');await expect(page.locator('#autoStats')).toContainText('Analyse noch nicht gestartet');await expect(page.locator('#autoResults')).toBeHidden();const monthImage=await page.locator('#autoPlanMonth').evaluate(e=>getComputedStyle(e).backgroundImage);expect(monthImage).toContain('Dez.');if(theme==='light')expect(monthImage).toContain('%23172434');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`auto-ready-${theme}.png`),fullPage:true});
 await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoResults')).toBeVisible();await expect(page.locator('#autoSuggestionCount')).not.toHaveText('0');await expect(page.locator('#applyAutoPlanBtn')).toBeEnabled();expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await page.getByRole('button',{name:'Alle Tage öffnen',exact:true}).click();await page.locator('#autoSuggestions button').first().click();await expect(page.locator('#autoUnresolvedCount')).not.toHaveText('0');await page.screenshot({path:test.info().outputPath(`auto-reviewed-${theme}.png`),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await expect(page.getByRole('dialog')).toContainText('Als Entwurf speichern');await page.getByRole('dialog').getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();await expect(page.locator('#autoAnalysis')).toContainText('als Entwurf übernommen');expect(await page.evaluate(()=>assignments.every(a=>!a.publishedAt))).toBe(true);expect(await page.evaluate(()=>saveCalls)).toBe(1);expect(await page.evaluate(()=>selectedMonth)).toBe('2026-12');await page.locator('#autoOpenScheduleBtn').click();expect(await page.evaluate(()=>openedView)).toBe('schedule');
});
test('unresolved required rhythm gives a reason and links to the correct planning week',async({page})=>{
 await fixture(page);await page.evaluate(()=>{employees[0].rhythmMode='required';employees[0].rhythmStart='2026-12-01';employees[0].rhythmPattern='FREI'});await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoUnresolvedPanel')).toHaveAttribute('open','');await expect(page.locator('#autoUnresolved')).toContainText('verbindliche Rhythmus');await expect(page.locator('#autoAnalysis')).toContainText('kein passender Mitarbeiter');await expect(page.locator('#applyAutoPlanBtn')).toBeDisabled();await page.getByRole('button',{name:'Im Dienstplan prüfen',exact:true}).first().click();expect(await page.evaluate(()=>iso(weekStart))).toBe('2026-11-30');expect(await page.evaluate(()=>openedView)).toBe('schedule');
});
test('switching period invalidates a prior preview and Escape cancels the confirmation',async({page})=>{
 await fixture(page);await page.locator('#generateAutoPlanBtn').click();await page.locator('#autoPlanPeriod').selectOption('date');await expect(page.locator('#autoPlanMonthField')).toBeHidden();await expect(page.locator('#autoPlanDateField')).toBeVisible();await expect(page.locator('#autoResults')).toBeHidden();await expect(page.locator('#applyAutoPlanBtn')).toBeDisabled();await page.locator('#autoPlanDate').fill('2026-12-01');await page.locator('#autoPlanDate').dispatchEvent('change');await page.locator('#generateAutoPlanBtn').click();await page.locator('#applyAutoPlanBtn').click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>assignments.length)).toBe(0);await expect(page.locator('#applyAutoPlanBtn')).toBeEnabled();
});
test('a TL from RE fills one shared LE/RE position and no second TL remains mandatory',async({page})=>{
 await fixture(page);await page.addScriptTag({content:read('assets/shift-models-v1.js')});await page.evaluate(()=>{globalSoll={'TL-LE':1,'TL-RE':1};dailySoll={};SFShiftModels.apply(['TL-LE','TL-RE'].map((code,i)=>({code,name:code,active:true,default_start:'20:00',default_end:'06:00',coverage_group:'TL LE/RE',coverage_required:1,sort_order:i})),'a');employees=[{id:'re',first:'Fiktive',last:'TL RE',status:'active',shifts:['TL-RE'],weeklyHours:40}];getSoll=(date,type)=>SFShiftModels.requiredSoll(date,type,globalSoll[type]||0);plannedAssignmentHours=()=>10;renderAutoPlanning()});
 await page.locator('#autoPlanPeriod').selectOption('date');await page.locator('#autoPlanDate').fill('2026-12-01');await page.locator('#autoPlanDate').dispatchEvent('change');await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('1');await expect(page.locator('#autoUnresolvedCount')).toHaveText('0');await expect(page.locator('#autoSuggestions')).toContainText('TL-RE');await expect(page.locator('#autoSuggestions')).toContainText('Deckt TL LE/RE gemeinsam ab');await page.screenshot({path:test.info().outputPath('shared-tl-re-preview.png'),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();expect(await page.evaluate(()=>assignments.map(a=>a.type))).toEqual(['TL-RE']);expect(await page.evaluate(()=>autoOpenSlots().length)).toBe(0);await expect(page.locator('#autoAnalysis')).toContainText('als Entwurf übernommen');
});
test('separate weekly maximum allows a fifth ten-hour shift while 220 full-time monthly hours remain mandatory',async({page})=>{
 await fixture(page);await page.locator('#autoPlanPeriod').selectOption('date');await page.locator('#autoPlanDate').fill('2026-12-06');await page.evaluate(()=>{TYPES[0].start='20:00';TYPES[0].end='06:00';employees[0].maxWeeklyHours=50;plannedAssignmentHours=()=>10;employeeMonthlyTarget=()=>400;assignments=['2026-11-30','2026-12-01','2026-12-02','2026-12-03'].map(date=>({date,type:'FD',employeeId:'test',start:'20:00',end:'06:00'}));plannedMonthlyHoursForEmployee=(employeeId,date,sim=[])=>[...assignments,...sim].filter(a=>a.employeeId===employeeId&&a.date.startsWith(date.slice(0,7))).length*10});await page.locator('#autoPlanDate').dispatchEvent('change');
 await expect(page.getByText('Wochenmaximum berücksichtigen',{exact:true})).toBeVisible();await expect(page.locator('.sf-auto-protection')).toContainText('maximal 220 Stunden');await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('1');await expect(page.locator('#autoSuggestions')).toContainText('40.0 Std. / 50.0 Std. Maximum');await page.screenshot({path:test.info().outputPath('auto-fifth-ten-hour-shift.png'),fullPage:true});
 await page.locator('#autoRespectHours').uncheck();await page.evaluate(()=>plannedMonthlyHoursForEmployee=()=>210);await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('1');await expect(page.locator('#autoSuggestions')).toContainText('210.0 / 220.0 Std. Maximum');await page.evaluate(()=>plannedMonthlyHoursForEmployee=()=>215);await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('0');await expect(page.locator('#autoUnresolved')).toContainText('Vollzeit bis maximal 220 Monatsstunden');await expect(page.locator('#autoUnresolved')).toContainText('freiwillige Übernahme');await expect(page.locator('#applyAutoPlanBtn')).toBeDisabled();await page.screenshot({path:test.info().outputPath('auto-220h-month-cap.png'),fullPage:true});
});

for(const theme of ['dark','light'])test(`reserve Monday to Thursday O3 first, retain 180 SOLL and save 190 hours in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.evaluate(()=>{
  TYPES=[{id:'O3',name:'O3',start:'22:00',end:'08:00'}];employees=[{id:'flex',first:'Flexible',last:'Person',status:'active',employment:'Vollzeit',shifts:['O3'],weeklyHours:40,maxWeeklyHours:40,monthlyHours:180},{id:'115',first:'Feste',last:'O3',status:'active',employment:'Vollzeit',shifts:['O3'],weeklyHours:40,maxWeeklyHours:40,monthlyHours:180,rhythmMode:'required',rhythmStart:'2026-08-31',rhythmPattern:'O3, O3, O3, O3, FREI, FREI, FREI'}];employeeMonthlyTarget=e=>e.monthlyHours;plannedAssignmentHours=()=>10;plannedMonthlyHoursForEmployee=(id,date,sim=[])=>[...assignments,...sim].filter(a=>a.employeeId===id&&a.date.startsWith(date.slice(0,7))).length*10;
 });
 await page.locator('#autoPlanPeriod').selectOption('month');await page.locator('#autoPlanMonth').fill('2026-12');await page.locator('#generateAutoPlanBtn').click();
 const fixed=await page.evaluate(()=>autoPlanPreview.filter(a=>a.employeeId==='115'));expect(fixed).toHaveLength(19);expect(fixed.every(a=>[1,2,3,4].includes(new Date(a.date+'T12:00:00').getDay()))).toBe(true);expect(fixed.every(a=>a.type==='O3')).toBe(true);expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await expect(page.locator('.sf-auto-protection')).toContainText('Ziel 180, maximal 220');await expect(page.locator('#autoSuggestions')).toContainText('Feste Schichtvorgabe');await expect(page.locator('#autoSuggestions')).toContainText('Monats-SOLL 180.0');await page.screenshot({path:test.info().outputPath(`fixed-O3-190h-${theme}.png`),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();expect(await page.evaluate(()=>assignments.filter(a=>a.employeeId==='115').length)).toBe(19);expect(await page.evaluate(()=>saveCalls)).toBe(1);expect(errors).toEqual([]);
});
for(const theme of ['dark','light'])test(`staircase shows staggered workrest blocks and protects free days in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.evaluate(()=>{const pattern='ALLE, ALLE, ALLE, ALLE, FREI, FREI, FREI, ALLE, ALLE, ALLE, FREI, FREI';employees=Array.from({length:3},(_,i)=>({id:'cycle'+i,personnelNo:String(i+1),first:'Fiktive',last:'Person '+i,status:'active',employment:'Vollzeit',shifts:['FD'],weeklyHours:40,maxWeeklyHours:50,monthlyHours:180,rhythmMode:'required',rhythmStart:'2026-12-'+String(i+1).padStart(2,'0'),rhythmPattern:pattern}));});
 await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('.sf-auto-stair-table tbody tr')).toHaveCount(3);await expect(page.locator('.sf-auto-stair-table thead th')).toHaveCount(32);await expect(page.locator('#autoStaircase')).toContainText('Rhythmusfrei');await expect(page.locator('#autoSuggestions')).toContainText('Arbeitsblock');
 expect(await page.evaluate(()=>autoPlanPreview.every(a=>SFRhythm.check(employees.find(e=>e.id===a.employeeId),a.type,a.date).allowed))).toBe(true);expect(await page.evaluate(()=>assignments.length)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.locator('.sf-auto-staircase').screenshot({path:test.info().outputPath(`staircase-${theme}.png`)});await page.locator('.sf-auto-stair-scroll').evaluate(e=>e.scrollLeft=e.scrollWidth);await expect(page.locator('.sf-auto-stair-table tbody tr').first().locator('th')).toBeVisible();expect(errors).toEqual([]);
});
test('part-time limits and relative workload stay authoritative even with weekly maximum disabled',async({page})=>{
 await fixture(page);await page.locator('#autoRespectHours').uncheck();await page.evaluate(()=>{employees=[{id:'full',first:'Vollzeit',last:'180',status:'active',employment:'Vollzeit',shifts:['FD'],weeklyHours:40,monthlyHours:180},{id:'part',first:'Teilzeit',last:'162',status:'active',employment:'Teilzeit',shifts:['FD'],weeklyHours:40,monthlyHours:162}];employeeMonthlyTarget=e=>e.monthlyHours;plannedMonthlyHoursForEmployee=id=>id==='full'?180:150});await page.locator('#generateAutoPlanBtn').click();expect(await page.evaluate(()=>autoPlanPreview[0].employeeId)).toBe('part');
 await page.evaluate(()=>{employees[1].monthlyHours=144;plannedMonthlyHoursForEmployee=id=>id==='full'?210:140});await page.locator('#generateAutoPlanBtn').click();expect(await page.evaluate(()=>autoPlanPreview[0].employeeId)).toBe('full');await expect(page.locator('#autoSuggestions')).toContainText('210.0 / 220.0');
 await page.evaluate(()=>plannedMonthlyHoursForEmployee=id=>id==='full'?220:144);await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('0');await expect(page.locator('#autoUnresolved')).toContainText('220 Monatsstunden');await expect(page.locator('#autoUnresolved')).toContainText('162 oder 144');
});
test('atomic blocks cannot leave middle-day fragments and O3 cannot step back to TL',async({page})=>{
 await fixture(page);await page.evaluate(()=>{employees=[{id:'block',first:'Block',last:'Test',status:'active',employment:'Vollzeit',shifts:['FD'],weeklyHours:40,maxWeeklyHours:50,rhythmMode:'required',rhythmStart:'2026-12-01',rhythmPattern:'ALLE, ALLE, ALLE, ALLE, FREI, FREI, FREI, ALLE, ALLE, ALLE, FREI, FREI'}];getSoll=date=>Number(date>='2026-12-01'&&date<='2026-12-04')});
 await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('4');expect(await page.evaluate(()=>new Set(autoPlanPreview.map(x=>x.blockId)).size)).toBe(1);
 await page.locator('#autoSuggestions button').first().click();await expect(page.locator('#autoSuggestionCount')).toHaveText('0');await expect(page.locator('#autoUnresolvedCount')).toHaveText('4');
 await page.evaluate(()=>getSoll=date=>Number(['2026-12-01','2026-12-03','2026-12-04'].includes(date)));await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('0');await expect(page.locator('#autoUnresolved')).toContainText('Kein vollständiger Arbeitsblock');
 await page.evaluate(()=>{TYPES=[{id:'O3',start:'22:00',end:'08:00'},{id:'TL-LE',start:'20:00',end:'06:00'}];employees[0].shifts=['O3','TL-LE'];employees[0].rhythmMode='off';assignments=[{employeeId:'block',date:'2026-12-01',type:'O3'}]});expect(await page.evaluate(()=>autoEligibleEmployees('TL-LE','2026-12-02').length)).toBe(0);expect(await page.evaluate(()=>autoEligibleEmployees('TL-LE','2026-12-03').length)).toBe(1);
});

for(const theme of ['dark','light'])test(`monthly optimization redistributes unfair drafts only after confirmation in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.evaluate(()=>{
  employees=['a','b'].map(id=>({id,first:'Test',last:id,status:'active',employment:'Teilzeit',shifts:['FD'],weeklyHours:40,monthlyHours:16}));employeeMonthlyTarget=e=>e.monthlyHours;getSoll=date=>Number(date<='2026-12-04');
  assignments=['01','02','03','04'].map(d=>({id:d,date:'2026-12-'+d,type:'FD',employeeId:'a',start:'06:00',end:'14:00'}));
 });
 const original=await page.evaluate(()=>JSON.stringify(assignments));await page.locator('#optimizeAutoMonthBtn').click();await expect(page.locator('#autoMonthHours')).toContainText('Monatsstunden prüfen');await expect(page.locator('#autoMonthHours')).toContainText('32 h');await expect(page.locator('#autoSuggestionCount')).toHaveText('4');expect(await page.evaluate(()=>JSON.stringify(assignments))).toBe(original);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`month-optimization-${theme}.png`),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await expect(page.getByRole('dialog')).toContainText('4 bisherige flexible Entwürfe');await expect(page.getByRole('dialog')).toContainText('ersetzen');await page.getByRole('dialog').getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>JSON.stringify(assignments))).toBe(original);
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();expect(await page.evaluate(()=>employees.map(e=>assignments.filter(a=>a.employeeId===e.id).length))).toEqual([2,2]);expect(await page.evaluate(()=>saveCalls)).toBe(1);expect(errors).toEqual([]);
});

test('confirmed January optimization opens the saved January plan with its actual calendar and month totals',async({page})=>{
 await fixture(page);
 await page.evaluate(()=>{
  document.querySelector('.content').insertAdjacentHTML('beforeend','<section id="view-schedule" class="view"><div class="page-head"><h1>Wochenplanung</h1></div><div><b id="statShifts"></b><em></em><b id="statEmployees"></b><b id="statOpen"></b><b id="statCoverage"></b></div><span id="availableTxt"></span><div class="cal-toolbar"><div class="seg"><button>Woche</button><button>Monat</button></div><button id="prevWeek">Zurück</button><button id="nextWeek">Weiter</button><button id="todayBtn">Heute</button><span id="weekLabel"></span></div><div><div id="calendarGrid"></div><div id="sollList"></div></div></section>');
  showView=v=>{openedView=v;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id==='view-'+v))};
  employees=['a','b'].map(id=>({id,first:'Test',last:id,status:'active',employment:'Teilzeit',shifts:['FD'],weeklyHours:40,monthlyHours:16}));employeeMonthlyTarget=e=>e.monthlyHours;getSoll=date=>Number(date>='2027-01-01'&&date<='2027-01-04');
  assignments=['01','02','03','04'].map(d=>({id:d,date:'2027-01-'+d,type:'FD',employeeId:'a',start:'06:00',end:'14:00'}));
 });
 await page.addScriptTag({content:read('assets/schedule-month-view-v1.js')});await page.evaluate(()=>SchichtFunkCalendarView.setMonth('2026-12'));
 await page.locator('#autoPlanMonth').fill('2027-01');await page.locator('#autoPlanMonth').dispatchEvent('change');
 await page.locator('#optimizeAutoMonthBtn').click();await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();
 expect(await page.evaluate(()=>SchichtFunkCalendarView.getPeriod())).toEqual({mode:'month',start:'2027-01-01',end:'2027-01-31'});
 await page.locator('#autoOpenScheduleBtn').click();await expect(page.locator('#view-schedule')).toBeVisible();await expect(page.locator('#weekLabel')).toHaveText('Januar 2027');
 await expect(page.locator('#sfMonthView .sf-month-kpi').first()).toContainText('4');await expect(page.locator('[data-month-date="2027-01-01"]')).toContainText('FD · 1');await expect(page.locator('#statEmployees')).toHaveText('2');
});
test('three actual O3 from the previous night transfer OT1 to OT2 and removing one restores OT1',async({page})=>{
 await fixture(page);await page.addScriptTag({content:read('assets/shift-models-v1.js')});
 await page.evaluate(()=>{SFShiftModels.apply([{code:'O3',active:true,default_start:'22:00',default_end:'08:00'}, {code:'OT1',active:true,default_start:'06:00',default_end:'16:00'}, {code:'OT2',active:true,default_start:'08:00',default_end:'18:00',morning_ot_switch_min:3}],'a');globalSoll={O3:3,OT1:1,OT2:1};dailySoll={};employees=[{id:'day',first:'Tag',last:'Test',status:'active',employment:'Vollzeit',shifts:['OT1','OT2'],weeklyHours:40}];assignments=[1,2,3].map(employeeId=>({employeeId,type:'O3',date:'2026-11-30',start:'22:00',end:'08:00'}));});
 expect(await page.evaluate(()=>SFShiftModels.requiredSoll('2026-12-01','OT1',1))).toBe(0);expect(await page.evaluate(()=>SFShiftModels.requiredSoll('2026-12-01','OT2',1))).toBe(2);
 await page.evaluate(()=>{autoPlanPreview=[{id:'ot',employeeId:'day',date:'2026-12-01',type:'OT1',start:'06:00',end:'16:00'}];SFShiftModels.normalizeMorningOt(autoPlanPreview,assignments)});expect(await page.evaluate(()=>autoPlanPreview[0].type)).toBe('OT2');expect(await page.evaluate(()=>autoPlanPreview[0].start)).toBe('08:00');
 await page.evaluate(()=>{assignments.pop();SFShiftModels.normalizeMorningOt(autoPlanPreview,assignments)});expect(await page.evaluate(()=>autoPlanPreview[0].type)).toBe('OT1');expect(await page.evaluate(()=>autoPlanPreview[0].start)).toBe('06:00');
});

for(const theme of ['dark','light'])test(`draft counts and personal hour balances remain readable while scrolling in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.evaluate(()=>{getSoll=()=>0;employees=[{id:'one',personnelNo:'26',first:'Test',last:'Person',status:'active',weeklyHours:40,monthlyHours:16},{id:'two',first:'Ohne',last:'Dienst',status:'active',weeklyHours:40,monthlyHours:24}];employeeMonthlyTarget=e=>e.monthlyHours;assignments=[{employeeId:'one',date:'2026-12-01',type:'FD'}];autoPlanPreview=[{employeeId:'one',date:'2026-12-02',type:'FD'}];autoPlanAnalyzed=true;renderAutoPlanning()});
 await expect(page.locator('.sf-auto-draft-summary')).toContainText('1 / 2');await expect(page.locator('.sf-auto-draft-summary')).toContainText('2 Dienste');await expect(page.locator('.sf-auto-draft-summary')).toContainText('16 h');
 const person=page.locator('.sf-auto-stair-table tbody tr').first();await expect(person).toContainText('Plan-IST 16 h');await expect(person).toContainText('SOLL 16 h');await expect(person).toContainText('Differenz 0 h');await expect(page.locator('.sf-auto-stair-table tbody tr').nth(1)).toContainText('Differenz -24 h');
 await person.locator('.sf-auto-draft-metrics').scrollIntoViewIfNeeded();await page.locator('.sf-auto-stair-scroll').evaluate(e=>e.scrollLeft=e.scrollWidth);await expect(person.locator('.sf-auto-draft-metrics')).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await page.locator('.sf-auto-staircase').screenshot({path:test.info().outputPath(`draft-hours-${theme}.png`)});
 await page.evaluate(()=>removeAutoSuggestion(0));await expect(person).toContainText('Plan-IST 8 h');await expect(person).toContainText('Differenz -8 h');await expect(page.locator('.sf-auto-draft-summary')).toContainText('1 Dienst');expect(errors).toEqual([]);
});
