const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'../../'+p),'utf8');
const index=read('index.html'),section=index.slice(index.indexOf('<section id="view-auto"'),index.indexOf('\n  <section id="view-reports"',index.indexOf('<section id="view-auto"'))).replace('class="view sf-auto-workspace"','class="view active sf-auto-workspace"');
const planning=index.slice(index.indexOf('let autoPlanPreview=[];'),index.indexOf('\nfunction renderOverviewStats()',index.indexOf('let autoPlanPreview=[];')));
async function fixture(page,theme='dark'){
 await page.route('https://schichtfunk.de/__auto-plan-workspace-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__auto-plan-workspace-fixture');
 await page.setContent(`<meta name="viewport" content="width=device-width,initial-scale=1"><div id="appShell"><main class="main"><div class="content">${section}</div></main></div>`);
 await page.addStyleTag({content:index.match(/<style>\n([\s\S]*?)<\/style>/)[1]});await page.addStyleTag({content:read('assets/manager-theme-v1.css')});await page.addStyleTag({content:read('assets/date-month-controls-v1.css')});await page.addStyleTag({content:read('assets/auto-plan-period-v1.css')});await page.addStyleTag({content:'.main{padding:20px}body{height:auto}#appShell{min-width:0}button:disabled{cursor:not-allowed}'});await page.evaluate(t=>document.documentElement.dataset.sfTheme=t,theme);
 await page.addScriptTag({content:`window.weekStart=new Date(2026,8,28);window.assignments=[];window.employees=[{id:'test',first:'Fiktive',last:'Person',status:'active',employment:'Vollzeit',shifts:['FD'],weeklyHours:40}];window.TYPES=[{id:'FD',name:'Frühdienst',start:'06:00',end:'14:00'}];window.absences=[];window.iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');window.addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};window.typeById=t=>TYPES.find(x=>x.id===t);window.getSoll=()=>1;window.assignmentsFor=(d,t)=>assignments.filter(a=>a.date===d&&a.type===t);window.absent=()=>false;window.plannedAssignmentHours=()=>8;window.employeeMonthlyTarget=()=>180;window.plannedMonthlyHoursForEmployee=(id,date,simulated=[])=>[...assignments,...simulated].filter(a=>a.employeeId===id&&a.date.startsWith(date.slice(0,7))).length*8;window.showSaveToast=()=>{};window.saveCalls=0;window.saveAll=()=>saveCalls++;window.renderCalendar=()=>{};window.openedView=null;window.showView=v=>openedView=v;window.SFBackend={companyId:${JSON.stringify(theme==='dark'?'a':'b')}};window.selectedMonth=null;window.SchichtFunkCalendarView={setMonth:v=>selectedMonth=v,setMode:()=>{}};`});
 await page.addScriptTag({content:read('assets/date-month-format-v1.js')});await page.addScriptTag({content:planning});await page.addScriptTag({content:read('assets/employee-rhythm-v1.js')});await page.addScriptTag({content:read('assets/supabase-auto-plan-guard-v1.js')});await page.addScriptTag({content:read('assets/auto-plan-workspace-v1.js')});
 await page.locator('#autoPlanPeriod').selectOption('month');await page.locator('#autoPlanMonth').fill('2026-12');await page.locator('#autoPlanMonth').dispatchEvent('change');
}
for(const theme of ['dark','light'])test(`clear month selection, preview review and confirmed draft in ${theme} theme`,async({page})=>{
 await fixture(page,theme);await expect(page.locator('#autoPlanWeekField')).toBeHidden();await expect(page.locator('#autoPlanDateField')).toBeHidden();await expect(page.locator('#autoPlanMonthField')).toBeVisible();await expect(page.locator('#autoPeriodRange')).toHaveText('Dezember 2026');await expect(page.locator('#autoPeriodDates')).toContainText('1.12.2026 bis 31.12.2026');await expect(page.locator('#autoStats')).toContainText('Analyse noch nicht gestartet');await expect(page.locator('#autoResults')).toBeHidden();const monthImage=await page.locator('#autoPlanMonth').evaluate(e=>getComputedStyle(e).backgroundImage);expect(monthImage).toContain('Dez.');if(theme==='light')expect(monthImage).toContain('%23172434');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`auto-ready-${theme}.png`),fullPage:true});
 await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoResults')).toBeVisible();await expect(page.locator('#autoSuggestionCount')).not.toHaveText('0');await expect(page.locator('#applyAutoPlanBtn')).toBeEnabled();expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await page.getByRole('button',{name:'Alle Tage öffnen',exact:true}).click();await page.locator('#autoSuggestions button').first().click();await expect(page.locator('#autoUnresolvedCount')).not.toHaveText('0');await page.screenshot({path:test.info().outputPath(`auto-reviewed-${theme}.png`),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await expect(page.getByRole('dialog')).toContainText('Als Entwurf speichern');await page.getByRole('dialog').getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();await expect(page.locator('#autoAnalysis')).toContainText('als Entwurf übernommen');expect(await page.evaluate(()=>assignments.every(a=>!a.publishedAt))).toBe(true);expect(await page.evaluate(()=>saveCalls)).toBe(1);expect(await page.evaluate(()=>selectedMonth)).toBe('2026-12');await page.locator('#autoOpenScheduleBtn').click();expect(await page.evaluate(()=>openedView)).toBe('schedule');
});
test('unresolved required rhythm gives a reason and links to the correct planning week',async({page})=>{
 await fixture(page);await page.evaluate(()=>{employees[0].rhythmMode='required';employees[0].rhythmStart='2026-12-01';employees[0].rhythmPattern='FREI'});await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoUnresolvedPanel')).toHaveAttribute('open','');await expect(page.locator('#autoUnresolved')).toContainText('verbindliche Rhythmus');await expect(page.locator('#autoAnalysis')).toContainText('kein passender Mitarbeiter');await expect(page.locator('#applyAutoPlanBtn')).toBeDisabled();await page.getByRole('button',{name:'Im Dienstplan prüfen',exact:true}).first().click();expect(await page.evaluate(()=>iso(weekStart))).toBe('2026-11-30');expect(await page.evaluate(()=>openedView)).toBe('schedule');
});
test('switching period invalidates a prior preview and Escape cancels the confirmation',async({page})=>{
 await fixture(page);await page.locator('#generateAutoPlanBtn').click();await page.locator('#autoPlanPeriod').selectOption('date');await expect(page.locator('#autoPlanMonthField')).toBeHidden();await expect(page.locator('#autoPlanDateField')).toBeVisible();await expect(page.locator('#autoResults')).toBeHidden();await expect(page.locator('#applyAutoPlanBtn')).toBeDisabled();await page.locator('#autoPlanDate').fill('2026-12-01');await page.locator('#autoPlanDate').dispatchEvent('change');await page.locator('#generateAutoPlanBtn').click();await page.locator('#applyAutoPlanBtn').click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>assignments.length)).toBe(0);await expect(page.locator('#applyAutoPlanBtn')).toBeEnabled();
});
test('a TL from RE fills one shared LE/RE position and no second TL remains mandatory',async({page})=>{
 await fixture(page);await page.addScriptTag({content:read('assets/shift-models-v1.js')});await page.evaluate(()=>{globalSoll={'TL-LE':1,'TL-RE':1};dailySoll={};SFShiftModels.apply(['TL-LE','TL-RE'].map((code,i)=>({code,name:code,active:true,default_start:'20:00',default_end:'06:00',coverage_group:'TL LE/RE',coverage_required:1,sort_order:i})),'a');employees=[{id:'re',first:'Fiktive',last:'TL RE',status:'active',shifts:['TL-RE'],weeklyHours:40}];getSoll=(date,type)=>SFShiftModels.requiredSoll(date,type,globalSoll[type]||0);plannedAssignmentHours=()=>10;renderAutoPlanning()});
 await page.locator('#autoPlanPeriod').selectOption('date');await page.locator('#autoPlanDate').fill('2026-12-01');await page.locator('#autoPlanDate').dispatchEvent('change');await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('1');await expect(page.locator('#autoUnresolvedCount')).toHaveText('0');await expect(page.locator('#autoSuggestions')).toContainText('TL-RE');await expect(page.locator('#autoSuggestions')).toContainText('Deckt TL LE/RE gemeinsam ab');await page.screenshot({path:test.info().outputPath('shared-tl-re-preview.png'),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();expect(await page.evaluate(()=>assignments.map(a=>a.type))).toEqual(['TL-RE']);expect(await page.evaluate(()=>autoOpenSlots().length)).toBe(0);await expect(page.locator('#autoAnalysis')).toContainText('als Entwurf übernommen');
});
test('separate weekly maximum allows a fifth ten-hour shift while 220 full-time monthly hours remain mandatory',async({page})=>{
 await fixture(page);await page.locator('#autoPlanPeriod').selectOption('date');await page.locator('#autoPlanDate').fill('2026-12-06');await page.evaluate(()=>{TYPES[0].start='20:00';TYPES[0].end='06:00';employees[0].maxWeeklyHours=50;plannedAssignmentHours=()=>10;employeeMonthlyTarget=()=>400;assignments=['2026-11-30','2026-12-01','2026-12-02','2026-12-03'].map(date=>({date,type:'FD',employeeId:'test',start:'20:00',end:'06:00'}));plannedMonthlyHoursForEmployee=(employeeId,date,sim=[])=>[...assignments,...sim].filter(a=>a.employeeId===employeeId&&a.date.startsWith(date.slice(0,7))).length*10});await page.locator('#autoPlanDate').dispatchEvent('change');
 await expect(page.getByText('Wochenmaximum berücksichtigen',{exact:true})).toBeVisible();await expect(page.locator('.sf-auto-protection')).toContainText('maximal 220 Stunden');await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('1');await expect(page.locator('#autoSuggestions')).toContainText('40.0 Std. / 50.0 Std. Maximum');await page.screenshot({path:test.info().outputPath('auto-fifth-ten-hour-shift.png'),fullPage:true});
 await page.locator('#autoRespectHours').uncheck();await page.evaluate(()=>plannedMonthlyHoursForEmployee=()=>210);await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('1');await expect(page.locator('#autoSuggestions')).toContainText('210.0 / 220.0 Std. Maximum');await page.evaluate(()=>plannedMonthlyHoursForEmployee=()=>215);await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('0');await expect(page.locator('#autoUnresolved')).toContainText('Vollzeit bis maximal 220 Monatsstunden');await expect(page.locator('#autoUnresolved')).toContainText('freiwillige Übernahme');await expect(page.locator('#applyAutoPlanBtn')).toBeDisabled();await page.screenshot({path:test.info().outputPath('auto-220h-month-cap.png'),fullPage:true});
});

for(const theme of ['dark','light'])test(`reserve Monday to Thursday O3 first, retain 180 SOLL and save 190 hours in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.evaluate(()=>{
  TYPES=[{id:'O3',name:'O3',start:'22:00',end:'08:00'}];employees=[{id:'flex',first:'Flexible',last:'Person',status:'active',employment:'Vollzeit',shifts:['O3'],weeklyHours:40,maxWeeklyHours:40,monthlyHours:180},{id:'115',first:'Feste',last:'O3',status:'active',employment:'Vollzeit',shifts:['O3'],weeklyHours:40,maxWeeklyHours:40,monthlyHours:180,rhythmMode:'required',rhythmStart:'2026-08-31',rhythmPattern:'O3, O3, O3, O3, FREI, FREI, FREI'}];employeeMonthlyTarget=e=>e.monthlyHours;plannedAssignmentHours=()=>10;plannedMonthlyHoursForEmployee=(id,date,sim=[])=>[...assignments,...sim].filter(a=>a.employeeId===id&&a.date.startsWith(date.slice(0,7))).length*10;
 });
 await page.locator('#autoPlanPeriod').selectOption('month');await page.locator('#autoPlanMonth').fill('2026-12');await page.locator('#generateAutoPlanBtn').click();
 const fixed=await page.evaluate(()=>autoPlanPreview.filter(a=>a.employeeId==='115'));expect(fixed).toHaveLength(19);expect(fixed.every(a=>[1,2,3,4].includes(new Date(a.date+'T12:00:00').getDay()))).toBe(true);expect(fixed.every(a=>a.type==='O3')).toBe(true);expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await expect(page.locator('.sf-auto-protection')).toContainText('Ziel 180, maximal 220');await expect(page.locator('#autoSuggestions')).toContainText('Feste Schichtvorgabe');await expect(page.locator('#autoSuggestions')).toContainText('Monats-SOLL 180.0');await page.screenshot({path:test.info().outputPath(`fixed-O3-190h-${theme}.png`),fullPage:true});
 await page.locator('#applyAutoPlanBtn').click();await page.getByRole('dialog').getByRole('button',{name:'Als Entwurf übernehmen',exact:true}).click();expect(await page.evaluate(()=>assignments.filter(a=>a.employeeId==='115').length)).toBe(19);expect(await page.evaluate(()=>saveCalls)).toBe(1);expect(errors).toEqual([]);
});
test('part-time limits and relative workload stay authoritative even with weekly maximum disabled',async({page})=>{
 await fixture(page);await page.locator('#autoRespectHours').uncheck();await page.evaluate(()=>{employees=[{id:'full',first:'Vollzeit',last:'180',status:'active',employment:'Vollzeit',shifts:['FD'],weeklyHours:40,monthlyHours:180},{id:'part',first:'Teilzeit',last:'162',status:'active',employment:'Teilzeit',shifts:['FD'],weeklyHours:40,monthlyHours:162}];employeeMonthlyTarget=e=>e.monthlyHours;plannedMonthlyHoursForEmployee=id=>id==='full'?180:150});await page.locator('#generateAutoPlanBtn').click();expect(await page.evaluate(()=>autoPlanPreview[0].employeeId)).toBe('part');
 await page.evaluate(()=>{employees[1].monthlyHours=144;plannedMonthlyHoursForEmployee=id=>id==='full'?210:140});await page.locator('#generateAutoPlanBtn').click();expect(await page.evaluate(()=>autoPlanPreview[0].employeeId)).toBe('full');await expect(page.locator('#autoSuggestions')).toContainText('210.0 / 220.0');
 await page.evaluate(()=>plannedMonthlyHoursForEmployee=id=>id==='full'?220:144);await page.locator('#generateAutoPlanBtn').click();await expect(page.locator('#autoSuggestionCount')).toHaveText('0');await expect(page.locator('#autoUnresolved')).toContainText('220 Monatsstunden');await expect(page.locator('#autoUnresolved')).toContainText('162 oder 144');
});
