const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'../../'+p),'utf8');
const index=read('index.html'),auto=index.slice(index.indexOf('<section id="view-auto"'),index.indexOf('\n  <section id="view-reports"',index.indexOf('<section id="view-auto"')));
const planning=index.slice(index.indexOf('let autoPlanPreview=[];'),index.indexOf('\nfunction renderOverviewStats()',index.indexOf('let autoPlanPreview=[];')));
const management=read('assets/employee-management-v2.js').replace(/\}\)\(\);\s*$/,'window.teamFixture={css,normalizeAll,renderList,renderProfile};})();');
async function fixture(page,theme){
 await page.route('https://schichtfunk.de/__planning-team-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__planning-team-fixture');
 await page.setContent(`<meta name="viewport" content="width=device-width,initial-scale=1"><div id="appShell"><main class="main"><div class="content"><section id="view-employees" class="view active"><button id="addEmployeeBtn">Mitarbeiter anlegen</button><div class="panel-grid"></div></section>${auto}</div></main></div><p id="toast"></p>`);
 await page.addStyleTag({content:index.match(/<style>\n([\s\S]*?)<\/style>/)[1]});await page.addStyleTag({content:read('assets/manager-theme-v1.css')});await page.addStyleTag({content:'.main{margin-left:0;padding:16px}body{height:auto}#appShell{min-width:0}'});await page.evaluate(t=>document.documentElement.dataset.sfTheme=t,theme);
 await page.addScriptTag({content:`Object.defineProperty(document,'readyState',{get:()=> 'loading'});window.makeEmployee=(id,team='')=>({id,_dbId:'db-'+id,first:'Fiktive',last:'Person '+id,personnelNo:id,status:'active',role:'Sicherheitsmitarbeiter',employment:'Vollzeit',shifts:['FD','SD','ND'],qualifications:['FD','SD','ND'],team:'Objekt Nord',planningTeam:team,rhythmMode:'required',rhythmKind:'cycle',rhythmStart:'2026-12-01',rhythmPattern:'FD, FD, SD, SD, FREI, ND, ND, FREI, FREI, FREI',weeklyHours:48,maxWeeklyHours:48});window.employees=[makeEmployee('S'),makeEmployee('A','A')];window.assignments=[];window.absences=[];window.timeEntries={};window.selectedEmployeeId='S';window.weekStart=new Date(2026,11,1);window.TYPES=[{id:'FD',name:'Frühdienst',start:'06:00',end:'14:00'},{id:'SD',name:'Spätdienst',start:'14:00',end:'22:00'},{id:'ND',name:'Nachtdienst',start:'22:00',end:'06:00'}];window.iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');window.addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};window.typeById=t=>TYPES.find(x=>x.id===t);window.getSoll=()=>4;window.assignmentsFor=(d,t)=>assignments.filter(a=>a.date===d&&a.type===t);window.absent=(id,date)=>absences.some(a=>a.employeeId===id&&a.date===date);window.plannedAssignmentHours=()=>8;window.employeeMonthlyTarget=()=>240;window.plannedMonthlyHoursForEmployee=()=>0;window.renderEmployees=()=>{};window.renderCalendar=()=>{};window.renderPlanEmployeePool=()=>{};window.updateStats=()=>{};window.showSaveToast=(a,b)=>document.querySelector('#toast').textContent=a+' '+(b||'');window.saveAll=()=>{};window.manualCalls=[];window.alerts=[];window.alert=x=>alerts.push(x);window.assignEmployeeByDrop=(id,type,date)=>manualCalls.push({id,type,date});window.calls=[];window.failSave=false;window.SFBackend={ready:true,role:'OWNER',companyId:${JSON.stringify(theme==='dark'?'company-a':'company-b')},client:{from(table){const q={table,filters:[]};return{update(payload){q.payload=payload;return this},eq(k,v){q.filters.push([k,v]);return this},select(){return this},async single(){calls.push(q);return failSave?{error:{message:'Speichern fehlgeschlagen'}}:{data:{id:'db-S',legacy_id:'S'}}}}}}};window.SFShiftModels={isCompanyLoaded:()=>true,activeCodes:()=>TYPES.map(t=>t.id),knownCodes:()=>TYPES.map(t=>t.id)};`});
 await page.addScriptTag({content:read('assets/supabase-data-v1.js')});await page.addScriptTag({content:read('assets/employee-rhythm-v1.js')});await page.addScriptTag({content:planning});await page.addScriptTag({content:read('assets/supabase-auto-plan-guard-v1.js')});await page.addScriptTag({content:read('assets/auto-plan-workspace-v1.js')});await page.addScriptTag({content:management});await page.evaluate(()=>{teamFixture.css();teamFixture.normalizeAll();teamFixture.renderList();teamFixture.renderProfile()});
}
for(const theme of ['dark','light'])test(`assign and persist a planning team, enforce manual and automatic rules in ${theme}`,async({page})=>{
 await fixture(page,theme);await page.locator('#spPlanningTeam').selectOption('B');await expect(page.locator('#spPlanningTeamSummary')).toContainText('Einstieg an Tag 3');await expect(page.locator('#spPlanningTeamSummary')).toContainText('Spätdienst');await expect(page.locator('#spRhythmStart')).toHaveValue('2026-12-01');await expect(page.locator('#spRhythmMode')).toHaveValue('required');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`employee-team-${theme}.png`),fullPage:true});
 await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter gespeichert');expect(await page.evaluate(()=>calls[0].payload.qualifications)).toContain('__sp:planningTeam=B');expect(await page.evaluate(()=>calls[0].filters)).toContainEqual(['company_id',theme==='dark'?'company-a':'company-b']);expect(await page.evaluate(()=>calls[0].filters)).toContainEqual(['id','db-S']);
 await page.evaluate(()=>{const payload=calls[0].payload;employees[0]={...makeEmployee('S'),planningTeam:undefined,rhythmMode:undefined,rhythmKind:undefined,rhythmStart:undefined,rhythmPattern:undefined,qualifications:payload.qualifications};renderEmployees()});await expect(page.locator('#spPlanningTeam')).toHaveValue('B');await expect(page.locator('#spTeam')).toHaveValue('Objekt Nord');await page.locator('#spEmpTeam').selectOption('__planning_B');await expect(page.locator('#spEmpCount')).toHaveText('1 von 2');
 await page.evaluate(()=>{assignEmployeeByDrop('S','FD','2026-12-01');assignEmployeeByDrop('S','SD','2026-12-01')});expect(await page.evaluate(()=>manualCalls.map(x=>x.type))).toEqual(['SD']);expect(await page.evaluate(()=>alerts[0])).toContain('Team B');
 expect(await page.evaluate(()=>autoEligibleEmployees('SD','2026-12-01').map(x=>x.e.id))).toEqual(['S']);expect(await page.evaluate(()=>autoEligibleEmployees('ND','2026-12-01').map(x=>x.e.id))).toEqual([]);
 await page.locator('#spPlanningTeam').selectOption('C');await page.evaluate(()=>failSave=true);await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Speichern fehlgeschlagen');expect(await page.evaluate(()=>employees[0].planningTeam)).toBe('B');
});
test('staggered teams fill December, absences stay binding and another company has separate teams',async({page})=>{
 await fixture(page,'dark');await page.evaluate(()=>{employees=['A','B','C','D','E'].flatMap(team=>Array.from({length:4},(_,i)=>makeEmployee(team+i,team)));document.getElementById('autoPlanPeriod').value='month';document.getElementById('autoPlanMonth').value='2026-12';document.getElementById('autoRespectHours').checked=false;generateAutoPlanPreview();});
 expect(await page.evaluate(()=>document.querySelector('#autoSuggestionCount').textContent)).toBe('372');expect(await page.evaluate(()=>document.querySelector('#autoUnresolvedCount').textContent)).toBe('0');expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await page.evaluate(()=>{absences=[{employeeId:'B0',date:'2026-12-01'}];generateAutoPlanPreview()});expect(await page.evaluate(()=>document.querySelector('#autoUnresolvedCount').textContent)).not.toBe('0');
 await page.evaluate(()=>{SFBackend.companyId='other-company';employees=[makeEmployee('S')];selectedEmployeeId='S';renderEmployees()});await expect(page.locator('#spPlanningTeam')).toHaveValue('');await expect(page.locator('#spPlanningTeamCounts')).toContainText('Team A: 0 aktiv');
});
