const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8').split('\n').find(l=>l.startsWith('function renderPlanEmployeePool(){'));
async function fixture(page){
 await page.route('https://schichtfunk.de/__pool-models',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__pool-models');
 await page.setContent('<section id="view-schedule"><div class="shift-row"><button class="shift-chip"><b>FD</b></button><button class="shift-chip"><b>SD</b></button></div><div class="employee-pool-head"><input id="planEmployeeSearch"></div><div id="planEmployeePool"></div></section>');
 await page.addScriptTag({content:`window.TYPES=[{id:'FD'},{id:'SD'},{id:'ND'}];window.employees=[{id:'team',first:'Team',last:'Person',status:'active',shifts:['O1','O2','FD','SD','ND'],role:'Sicherheitsmitarbeiter'},{id:'fd',first:'Nur',last:'Frühdienst',status:'active',shifts:['O1','FD']}];window.absences=[];window.selectedPlanEmployeeId=null;window.currentWeekDates=()=>[new Date('2026-12-01T12:00:00')];window.iso=d=>d.toISOString().slice(0,10);window.showSaveToast=()=>{};`+source});
 await page.evaluate(()=>renderPlanEmployeePool());
}
test('pool displays only current permitted models and preserves stored historical permissions',async({page})=>{await fixture(page);await expect(page.locator('[data-employee-id="team"] .pool-shift-tag')).toHaveText(['FD','SD','ND']);await expect(page.locator('[data-employee-id="fd"] .pool-shift-tag')).toHaveText(['FD']);expect(await page.evaluate(()=>employees[0].shifts)).toEqual(['O1','O2','FD','SD','ND']);});
test('pool switches models with the company and responds to archive or restore',async({page})=>{await fixture(page);await page.evaluate(()=>{TYPES=[{id:'O1'}];renderPlanEmployeePool()});await expect(page.locator('[data-employee-id="team"] .pool-shift-tag')).toHaveText(['O1']);await page.evaluate(()=>{TYPES=[{id:'FD'},{id:'SD',active:false}];renderPlanEmployeePool()});await expect(page.locator('[data-employee-id="team"] .pool-shift-tag')).toHaveText(['FD']);await page.evaluate(()=>{TYPES[1].active=true;renderPlanEmployeePool()});await expect(page.locator('[data-employee-id="team"] .pool-shift-tag')).toHaveText(['FD','SD']);});
test('pool search excludes obsolete models and empty permissions do not grant a current model',async({page})=>{await fixture(page);await page.locator('#planEmployeeSearch').fill('O1');await page.evaluate(()=>renderPlanEmployeePool());await expect(page.locator('.employee-drag')).toHaveCount(0);await page.locator('#planEmployeeSearch').fill('SD');await page.evaluate(()=>renderPlanEmployeePool());await expect(page.locator('.employee-drag')).toHaveCount(1);await page.locator('#planEmployeeSearch').fill('');await page.evaluate(()=>{employees[0].shifts=['O1'];renderPlanEmployeePool()});await expect(page.locator('[data-employee-id="team"] .pool-shift-tag')).toHaveText(['Keine Freigabe']);});
test('dynamic shift filter uses the corrected badges including FD-only employees',async({page})=>{await fixture(page);await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'../../assets/dynamic-employee-pool-v1.js'),'utf8')});await page.getByRole('button',{name:'SD',exact:true}).evaluate(b=>b.classList.add('selected'));await page.locator('#planEmployeeSearch').dispatchEvent('input');await expect(page.locator('[data-employee-id="fd"]')).toHaveClass(/sp-dynpool-hidden/);await expect(page.locator('[data-employee-id="team"]')).not.toHaveClass(/sp-dynpool-hidden/);});
