const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../assets/employee-management-v2.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.statusFixture={overviewTab,bindTab};})();');
const dataSource=fs.readFileSync(path.join(__dirname,'../../assets/supabase-data-v1.js'),'utf8');
async function fixture(page,company){
 await page.route('https://schichtfunk.de/__employee-status-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__employee-status-fixture');
 await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:14px Arial;background:#06101b;color:#edf6ff;padding:12px}.sp-profile-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}label span{display:block}input,select,textarea{box-sizing:border-box;width:100%;min-height:44px}button{min-height:44px;margin:6px;padding:10px}h3{margin-top:25px}</style><div id="fixtureProfile"></div><div id="pool"></div><p id="toast"></p>');
 await page.addScriptTag({content:`Object.defineProperty(document,'readyState',{get:()=> 'loading'});window.employees=[{id:'test',_dbId:'test-db',first:'Fiktiver',last:'Mitarbeiter',personnelNo:'TEST',status:'inactive',availabilityStatus:'red',shifts:['FD'],qualifications:['FD','__sp:availability=red'],weeklyHours:40,maxWeeklyHours:40}];window.assignments=[];window.absences=[];window.timeEntries={};window.selectedEmployeeId='test';window.calls=[];window.failSave=false;window.renderPlanEmployeePool=()=>document.querySelector('#pool').textContent=employees[0].status==='active'&&employees[0].availabilityStatus!=='red'?'Fiktiver Mitarbeiter einplanbar':'Nicht im Planungspool';window.showSaveToast=(s,e)=>document.querySelector('#toast').textContent=s+(e?' · '+e:'');window.renderEmployees=()=>{document.querySelector('#fixtureProfile').innerHTML=statusFixture.overviewTab(employees[0],false);statusFixture.bindTab(employees[0],false)};window.SFBackend={companyId:${JSON.stringify(company)},ready:true,role:'OWNER',empDb:new Map(),empLocal:new Map(),client:{from(table){const q={table,filters:[]};return{update(payload){q.payload=payload;return this},eq(k,v){q.filters.push([k,v]);return this},is(k,v){q.filters.push([k,v]);return this},select(){return this},async single(){calls.push(q);return failSave?{error:{message:'Speichern fehlgeschlagen'}}:{data:{id:'test-db',status:q.payload.status}}}}}}};`});
 await page.addScriptTag({content:dataSource});await page.addScriptTag({content:source});await page.evaluate(()=>{renderEmployees();renderPlanEmployeePool()});
 if(company==='b')await page.addStyleTag({content:':root{--bg:#eef3f7;--panel:#ffffff;--text:#172434;--muted:#536474;--line:#d8e1e9}body{background:#eef3f7;color:#172434}'});
}
for(const company of ['a','b'])test(`reactivate and deactivate an employee in company ${company}`,async({page})=>{
 await fixture(page,company);await expect(page.getByRole('button',{name:'Aktivieren',exact:true})).toBeVisible();await page.getByRole('button',{name:'Aktivieren',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>calls.length)).toBe(0);
 await page.getByRole('button',{name:'Aktivieren',exact:true}).click();const dialog=page.getByRole('dialog'),bounds=await dialog.boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(page.viewportSize().width);await expect(dialog).toContainText('SchichtFunk');await expect(dialog).toContainText('Fiktiver Mitarbeiter');await dialog.screenshot({path:test.info().outputPath(`status-confirm-${company}.png`)});await page.getByRole('button',{name:'Ja, aktivieren',exact:true}).click();await expect(page.getByRole('button',{name:'Deaktivieren',exact:true})).toBeVisible();await expect(page.locator('#spStatus')).toHaveValue('active');await expect(page.locator('#pool')).toHaveText('Fiktiver Mitarbeiter einplanbar');expect(await page.evaluate(()=>calls[0].filters)).toEqual([['company_id',company],['id','test-db'],['deleted_at',null]]);
 await page.getByRole('button',{name:'Deaktivieren',exact:true}).click();await page.getByRole('button',{name:'Ja, deaktivieren',exact:true}).click();await expect(page.getByRole('button',{name:'Aktivieren',exact:true})).toBeVisible();await expect(page.locator('#pool')).toHaveText('Nicht im Planungspool');
 await page.locator('#spStatus').selectOption('active');await expect(page.locator('#spAvailabilityStatus')).toHaveValue('green');
});
test('failed activation keeps an employee inactive and reports the error',async({page})=>{
 await fixture(page,'a');await page.evaluate(()=>failSave=true);await page.getByRole('button',{name:'Aktivieren',exact:true}).click();await page.getByRole('button',{name:'Ja, aktivieren',exact:true}).click();await expect(page.locator('#toast')).toContainText('Speichern fehlgeschlagen');await expect(page.locator('#spStatus')).toHaveValue('inactive');await expect(page.locator('#pool')).toHaveText('Nicht im Planungspool');
});

test('confirmation can be closed using Escape without changing the employee',async({page})=>{
 await fixture(page,'a');await page.getByRole('button',{name:'Aktivieren',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>calls.length)).toBe(0);await expect(page.getByRole('button',{name:'Aktivieren',exact:true})).toBeEnabled();expect(await page.evaluate(()=>SFBackend.employeeStatusConfirming)).toBe(false);
});

for(const company of ['a','b'])test(`personal file is visible in the modern profile and records course deadlines in company ${company}`,async({page})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('https://schichtfunk.de/__personnel-fixture',route=>route.fulfill({contentType:'text/html',body:'<html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__personnel-fixture');
 await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box}body{margin:0;padding:16px;font:14px Arial;background:#07111d;color:#edf6ff}#spEmployeeV2{display:block}button{cursor:pointer}</style><section id="view-employees" class="active"><header><h1>Mitarbeiter</h1><div><button id="addEmployeeBtn">Mitarbeiter anlegen</button></div></header><div id="spEmployeeV2"><div aria-hidden="true" style="display:none"><div id="employeeSummary"></div></div><section id="spEmployeeProfile"></section></div></section>');
 await page.addScriptTag({content:`Object.defineProperty(document,'readyState',{get:()=> 'loading'});window.employees=[{id:'one',_dbId:'db-one',first:'Erster',last:'Mitarbeiter',personnelNo:'1',employment:'Vollzeit',status:'active',shifts:['O3'],qualifications:['O3']},{id:'two',_dbId:'db-two',first:'Zweiter',last:'Mitarbeiter',personnelNo:'2',employment:'Vollzeit',status:'active',shifts:['O3'],qualifications:['O3']}];window.selectedEmployeeId='one';window.assignments=[];window.absences=[];window.timeEntries={};window.savedCourses=[];window.calls=[];window.SFBackend={role:'OWNER',companyId:${JSON.stringify(company)},client:{async rpc(name,args){calls.push({name,args});if(name==='manager_save_personnel_qualification'){savedCourses.push({id:'course',employee_id:args.p_employee_id,title:args.p_title,category:args.p_category,issued_on:args.p_issued_on,expires_on:args.p_expires_on,validity_status:'VALID'});return{data:'course'}}if(name==='manager_personnel_file_bundle'){const e=employees.find(e=>e._dbId===args.p_employee_id);return{data:{employee:{first_name:e.first,last_name:e.last,personnel_no:e.personnelNo,status:e.status},qualifications:savedCourses.filter(q=>q.employee_id===args.p_employee_id),documents:[],notes:[],history:[]}}}if(name==='manager_personnel_deadline_dashboard')return{data:{stats:{total:savedCourses.length,employees:1,qualifications:savedCourses.length,documents:0,expired:0,d30:0,d60:0,d90:0,later:savedCourses.length,no_expiry:0},rows:savedCourses.map(q=>({...q,employee_name:'Erster Mitarbeiter',personnel_no:'1',employee_status:'active',entity_type:'QUALIFICATION',urgency:'LATER',days_until_expiry:120}))}};return{data:{}}}}};`});
 const modernSource=fs.readFileSync(path.join(__dirname,'../../assets/employee-management-v2.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.personnelFixture={render(){activeTab="qualifications";renderProfile()},css};})();');
 await page.addScriptTag({content:modernSource});await page.evaluate(()=>{personnelFixture.css();personnelFixture.render()});
 for(const file of ['supabase-personnel-file-observer-guard-v1.js','supabase-personnel-file-v1.js','supabase-personnel-deadline-dashboard-v1.js','supabase-personnel-deadline-dashboard-button-order-fix-v1.js','supabase-personnel-deadline-dashboard-header-v1.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'../../assets',file),'utf8')});
 await page.evaluate(()=>SFBackend.personnelFile.ensureLaunch());
 await expect(page.locator('#spEmployeeProfile #sfPersonnelOpen')).toBeVisible();await expect(page.locator('#employeeSummary')).toBeHidden();
 await expect(page.locator('#sfDeadlineDashboardOpen')).toBeVisible();await page.screenshot({path:test.info().outputPath(`personnel-visible-${company}.png`),fullPage:true});
 await page.locator('#sfPersonnelOpen').click();await page.locator('[data-pftab="qualifications"]').click();await page.locator('#sfPfAddQualification').click();await page.locator('#sfQCategory').selectOption('Schulung');await page.locator('#sfQTitle').fill('Erste-Hilfe-Lehrgang');await page.locator('#sfQIssued').fill('2026-10-03');await page.locator('#sfQExpires').fill('2028-10-03');await page.locator('#sfQSave').click();await expect(page.locator('#sfPfBody')).toContainText('Erste-Hilfe-Lehrgang');await expect(page.locator('#sfPfBody')).toContainText(/Ablauf 0?3\.10\.2028/);await page.locator('#sfPfClose').click();
 await page.locator('#sfDeadlineDashboardOpen').click();await expect(page.locator('#sfPersonnelDeadlineDashboard')).toContainText('Erste-Hilfe-Lehrgang');await page.locator('#sfDeadlineDashboardClose').click();
 await page.evaluate(()=>{selectedEmployeeId='two';personnelFixture.render()});await expect(page.locator('#sfPersonnelOpen')).toContainText('Zweiter Mitarbeiter');await page.locator('#sfPersonnelOpen').click();await expect(page.locator('#sfPersonnelFile h2')).toHaveText('Zweiter Mitarbeiter');await page.locator('[data-pftab="qualifications"]').click();await expect(page.locator('#sfPfBody')).not.toContainText('Erste-Hilfe-Lehrgang');
 expect(await page.evaluate(()=>calls.find(call=>call.name==='manager_save_personnel_qualification').args.p_employee_id)).toBe('db-one');expect(errors).toEqual([]);
});
