const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../assets/employee-removal-v1.js'),'utf8');
async function fixture(page,company='a',light=false){
  await page.route('https://schichtfunk.de/__employee-removal-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__employee-removal-fixture');
  await page.setContent(`<meta name="viewport" content="width=device-width,initial-scale=1"><style>:root{--bg:${light?'#f5f8fc':'#06101b'};--panel:${light?'#ffffff':'#0d1928'};--text:${light?'#162c40':'#edf6ff'};--muted:${light?'#52697e':'#9bb0c6'};--line:${light?'#bdccd9':'#29455e'}}body{background:var(--bg);color:var(--text);font:14px Arial;margin:16px}button{padding:10px 14px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text);cursor:pointer}.danger{background:#a52336;color:white}</style><p id="employee">Fiktiver Mitarbeiter</p><button id="open">Mitarbeiter löschen</button>`);
  await page.addScriptTag({content:`window.selectedEmployeeId='fixture';window.selectedPlanEmployeeId='fixture';window.removalCalls=[];window.fixtureError=false;window.SFBackend={companyId:${JSON.stringify(company)},ready:true,role:'OWNER',hydrate:async()=>{document.querySelector('#employee').remove()},client:{rpc:async(name,args)=>{if(name==='manager_remove_employee'){removalCalls.push(args);if(fixtureError)return{error:{message:'Die betroffenen Daten wurden inzwischen geändert. Bitte die Löschübersicht erneut öffnen.'}};return{data:{removed:true}}}return{data:{employee_id:'fixture-db',employee_name:'Fiktiver Mitarbeiter',personnel_no:'TEST-001',company_name:${JSON.stringify(company==='a'?'SchichtFunk':'Secontec Services - 8h')},fingerprint:'v1',cancel_shifts:3,delete_absences:2,retained_shifts:5,retained_absences:1}}}}};`});
  await page.addScriptTag({content:source});await page.evaluate(()=>{document.querySelector('#open').onclick=()=>SFEmployeeRemoval.open({id:'fixture',_dbId:'fixture-db',first:'Fiktiver',last:'Mitarbeiter'})});
}
for(const company of ['a','b'])test(`separate name and checkbox confirmation in company ${company}`,async({page})=>{
  await fixture(page,company,company==='b');await page.getByRole('button',{name:'Mitarbeiter löschen',exact:true}).click();const confirm=page.getByRole('button',{name:'Mitarbeiter jetzt löschen',exact:true});await expect(confirm).toBeDisabled();await expect(page.getByText(company==='a'?'SchichtFunk · Personalnummer TEST-001':'Secontec Services - 8h · Personalnummer TEST-001',{exact:true})).toBeVisible();
  await page.locator('#sfRemoveEmployeeAck').check();await expect(confirm).toBeDisabled();await page.getByLabel('Vollständiger Name zur Löschbestätigung',{exact:true}).fill('Falscher Name');await expect(confirm).toBeDisabled();await page.getByLabel('Vollständiger Name zur Löschbestätigung',{exact:true}).fill('Fiktiver Mitarbeiter');await expect(confirm).toBeEnabled();await page.locator('#sfRemoveEmployeeAck').uncheck();await expect(confirm).toBeDisabled();await page.locator('#sfRemoveEmployeeAck').check();
  const bounds=await page.getByRole('dialog').boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(page.viewportSize().width);await page.screenshot({path:test.info().outputPath(`employee-removal-${company}.png`)});
  await page.getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>removalCalls.length)).toBe(0);await expect(page.locator('#employee')).toBeVisible();await page.locator('#open').click();await page.getByLabel('Vollständiger Name zur Löschbestätigung',{exact:true}).fill('Fiktiver Mitarbeiter');await page.locator('#sfRemoveEmployeeAck').check();await confirm.click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('#employee')).toHaveCount(0);expect(await page.evaluate(()=>removalCalls)).toEqual([{p_company_id:company,p_employee_id:'fixture-db',p_confirmation:'Fiktiver Mitarbeiter',p_acknowledged:true,p_fingerprint:'v1'}]);
});
test('stale data prevents deletion and keeps employee visible',async({page})=>{
  await fixture(page);await page.evaluate(()=>fixtureError=true);await page.locator('#open').click();await page.getByLabel('Vollständiger Name zur Löschbestätigung',{exact:true}).fill('Fiktiver Mitarbeiter');await page.locator('#sfRemoveEmployeeAck').check();await page.getByRole('button',{name:'Mitarbeiter jetzt löschen',exact:true}).click();await expect(page.getByRole('alert')).toContainText('inzwischen geändert');await expect(page.locator('#employee')).toBeVisible();await page.getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>SFBackend.employeeRemovalBusy)).toBe(false);
});
