const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'../../'+p),'utf8');
const index=read('index.html'),auto=index.slice(index.indexOf('<section id="view-auto"'),index.indexOf('\n  <section id="view-reports"',index.indexOf('<section id="view-auto"')));
const planning=index.slice(index.indexOf('let autoPlanPreview=[];'),index.indexOf('\nfunction renderOverviewStats()',index.indexOf('let autoPlanPreview=[];')));
const management=read('assets/employee-management-v2.js').replace(/\}\)\(\);\s*$/,'window.teamFixture={css,normalizeAll,renderList,renderProfile};})();');
async function fixture(page,theme){
 await page.route('https://schichtfunk.de/__planning-team-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__planning-team-fixture');
 await page.setContent(`<meta name="viewport" content="width=device-width,initial-scale=1"><div id="appShell"><main class="main"><div class="content"><section id="view-employees" class="view active"><button id="addEmployeeBtn">Mitarbeiter anlegen</button><div class="panel-grid"></div></section>${auto}</div></main></div><p id="toast"></p>`);
 await page.addStyleTag({content:index.match(/<style>\n([\s\S]*?)<\/style>/)[1]});await page.addStyleTag({content:read('assets/manager-theme-v1.css')});await page.addStyleTag({content:'.main{margin-left:0;padding:16px}body{height:auto}#appShell{min-width:0}'});await page.evaluate(t=>document.documentElement.dataset.sfTheme=t,theme);
 await page.addScriptTag({content:`Object.defineProperty(document,'readyState',{get:()=> 'loading'});window.makeEmployee=(id,team='')=>({id,_dbId:'db-'+id,first:'Fiktive',last:'Person '+id,personnelNo:id,status:'active',role:'Sicherheitsmitarbeiter',employment:'Vollzeit',shifts:['FD','SD','ND'],qualifications:['FD','SD','ND'],team:'Objekt Nord',planningTeam:team,rhythmMode:'required',rhythmKind:'cycle',rhythmStart:'2026-12-01',rhythmPattern:'FD, FD, SD, SD, FREI, ND, ND, FREI, FREI, FREI',weeklyHours:48,maxWeeklyHours:48});window.employees=[makeEmployee('S'),makeEmployee('A','A')];window.assignments=[];window.absences=[];window.timeEntries={};window.selectedEmployeeId='S';window.weekStart=new Date(2026,11,1);window.TYPES=[{id:'FD',name:'Frühdienst',start:'06:00',end:'14:00'},{id:'SD',name:'Spätdienst',start:'14:00',end:'22:00'},{id:'ND',name:'Nachtdienst',start:'22:00',end:'06:00'}];window.iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');window.addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};window.typeById=t=>TYPES.find(x=>x.id===t);window.getSoll=()=>4;window.assignmentsFor=(d,t)=>assignments.filter(a=>a.date===d&&a.type===t);window.absent=(id,date)=>absences.some(a=>a.employeeId===id&&a.date===date);window.plannedAssignmentHours=()=>8;window.employeeMonthlyTarget=e=>e.monthlyHours??240;window.plannedMonthlyHoursForEmployee=()=>0;window.renderEmployees=()=>{};window.renderCalendar=()=>{};window.renderPlanEmployeePool=()=>{};window.updateStats=()=>{};window.showSaveToast=(a,b)=>document.querySelector('#toast').textContent=a+' '+(b||'');window.saveAll=()=>{};window.manualCalls=[];window.alerts=[];window.alert=x=>alerts.push(x);window.assignEmployeeByDrop=(id,type,date)=>manualCalls.push({id,type,date});window.calls=[];window.failSave=false;window.SFBackend={ready:true,role:'OWNER',companyId:${JSON.stringify(theme==='dark'?'company-a':'company-b')},client:{from(table){const q={table,filters:[]};return{update(payload){q.payload=payload;return this},upsert(payload,options){q.payload=payload;q.options=options;q.operation='upsert';return this},eq(k,v){q.filters.push([k,v]);return this},select(){return this},async single(){calls.push(q);return failSave?{error:{message:'Speichern fehlgeschlagen'}}:{data:{id:q.operation==='upsert'?'db-'+q.payload.legacy_id:'db-S',legacy_id:q.payload.legacy_id||'S'}}}}}}};window.SFShiftModels={isCompanyLoaded:()=>true,activeCodes:()=>TYPES.map(t=>t.id),knownCodes:()=>TYPES.map(t=>t.id)};`});
 await page.addScriptTag({content:read('assets/supabase-data-v1.js')});await page.addScriptTag({content:read('assets/employee-rhythm-v1.js')});await page.addScriptTag({content:planning});await page.addScriptTag({content:read('assets/supabase-auto-plan-guard-v1.js')});await page.addScriptTag({content:read('assets/auto-plan-workspace-v1.js')});await page.addScriptTag({content:management});await page.evaluate(()=>{teamFixture.css();teamFixture.normalizeAll();teamFixture.renderList();teamFixture.renderProfile()});
}
for(const theme of ['dark','light'])test(`assign and persist a planning team, enforce manual and automatic rules in ${theme}`,async({page})=>{
 await fixture(page,theme);await page.locator('#spEmpTeam').selectOption('__no_planning_team__');await expect(page.locator('#spEmpCount')).toHaveText('1 von 2');await expect(page.locator('#spEmployeeList')).toContainText('Person S');await expect(page.locator('#spEmployeeList')).not.toContainText('Person A');await page.locator('#spEmpTeam').selectOption('all');await page.locator('#spPlanningTeam').selectOption('B');await expect(page.locator('#spPlanningTeamSummary')).toContainText('Einstieg an Tag 3');await expect(page.locator('#spPlanningTeamSummary')).toContainText('Spätdienst');await expect(page.locator('#spRhythmStart')).toHaveValue('2026-12-01');await expect(page.locator('#spRhythmMode')).toHaveValue('required');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`employee-team-${theme}.png`),fullPage:true});
 await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter gespeichert');expect(await page.evaluate(()=>calls[0].payload.qualifications)).toContain('__sp:planningTeam=B');expect(await page.evaluate(()=>calls[0].filters)).toContainEqual(['company_id',theme==='dark'?'company-a':'company-b']);expect(await page.evaluate(()=>calls[0].filters)).toContainEqual(['id','db-S']);
 await page.evaluate(()=>{const payload=calls[0].payload;employees[0]={...makeEmployee('S'),planningTeam:undefined,rhythmMode:undefined,rhythmKind:undefined,rhythmStart:undefined,rhythmPattern:undefined,qualifications:payload.qualifications};renderEmployees()});await expect(page.locator('#spPlanningTeam')).toHaveValue('B');await expect(page.locator('#spTeam')).toHaveValue('Objekt Nord');await page.locator('#spEmpTeam').selectOption('__planning_B');await expect(page.locator('#spEmpCount')).toHaveText('1 von 2');
 await page.evaluate(()=>{assignEmployeeByDrop('S','FD','2026-12-01');assignEmployeeByDrop('S','SD','2026-12-01')});expect(await page.evaluate(()=>manualCalls.map(x=>x.type))).toEqual(['SD']);expect(await page.evaluate(()=>alerts[0])).toContain('Team B');
 expect(await page.evaluate(()=>autoEligibleEmployees('SD','2026-12-01').map(x=>x.e.id))).toEqual(['S']);expect(await page.evaluate(()=>autoEligibleEmployees('ND','2026-12-01').map(x=>x.e.id))).toEqual([]);
 await page.locator('#spPlanningTeam').selectOption('C');await page.evaluate(()=>failSave=true);await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Speichern fehlgeschlagen');expect(await page.evaluate(()=>employees[0].planningTeam)).toBe('B');
});
test('staggered teams fill December, absences stay binding and another company has separate teams',async({page})=>{
 await fixture(page,'dark');await page.evaluate(()=>{employees=['A','B','C','D','E'].flatMap(team=>Array.from({length:4},(_,i)=>makeEmployee(team+i,team)));document.getElementById('autoPlanPeriod').value='month';document.getElementById('autoPlanMonth').value='2026-12';document.getElementById('autoRespectHours').checked=false;generateAutoPlanPreview();});
 expect(await page.evaluate(()=>document.querySelector('#autoSuggestionCount').textContent)).toBe('372');expect(await page.evaluate(()=>document.querySelector('#autoUnresolvedCount').textContent)).toBe('0');expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await page.evaluate(()=>{absences=[{employeeId:'B0',date:'2026-12-01'}];generateAutoPlanPreview()});expect(await page.evaluate(()=>document.querySelector('#autoUnresolvedCount').textContent)).not.toBe('0');
 await page.evaluate(()=>{SFBackend.companyId='other-company';employees=[makeEmployee('S')];selectedEmployeeId='S';renderEmployees()});await expect(page.locator('#spPlanningTeam')).toHaveValue('');await expect(page.locator('#spPlanningTeamCounts')).toContainText('Team A: 0 aktiv');
});
for(const theme of ['dark','light'])test(`create employee with editable tabs, team and permissions; preserve draft on failure in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);await page.locator('#addEmployeeBtn').click();
 await page.locator('#spFirst').fill('Neue');await page.locator('#spLast').fill('Testperson');await page.locator('#spPersonnel').fill('NEW-TEST');await page.locator('#spEmail').fill('synthetic@example.invalid');await page.locator('#spMonthlyHours').fill('180');await page.locator('#spStart').fill('2026-12-01');await page.locator('#spPlanningTeam').selectOption('E');
 await page.locator('[data-tab="qualifications"]').click();await expect(page.locator('#spExclusiveShift')).toBeVisible();for(const type of ['FD','SD','ND'])await page.locator(`[data-qual][value="${type}"]`).check();await page.locator('#spSaveQualifications').click();await expect(page.locator('#spFirst')).toHaveValue('Neue');await expect(page.locator('#spLast')).toHaveValue('Testperson');await expect(page.locator('#spMonthlyHours')).toHaveValue('180.00');await expect(page.locator('#spPlanningTeam')).toHaveValue('E');
 await page.locator('[data-tab="settings"]').click();await page.locator('#spSetMaxWeekly').fill('48');await page.locator('#spSetConsecutive').fill('8');await page.locator('#spSaveSettings').click();await expect(page.locator('#spMaxWeekly')).toHaveValue('48');
 for(const tab of ['planning','time','absences']){await page.locator(`[data-tab="${tab}"]`).click();await expect(page.locator('#spTabBody')).toContainText('Lege zuerst das Mitarbeiterprofil an.');await page.locator('#spBackToOverview').click();await expect(page.locator('#spPersonnel')).toHaveValue('NEW-TEST');}
 expect(await page.evaluate(()=>calls.length)).toBe(0);expect(await page.evaluate(()=>employees.length)).toBe(2);await page.evaluate(()=>failSave=true);await page.locator('#spSave').click();await expect(page.locator('#spFormError')).toContainText('Speichern fehlgeschlagen');await expect(page.locator('#spFirst')).toHaveValue('Neue');await expect(page.locator('#spSave')).toBeEnabled();expect(await page.evaluate(()=>employees.length)).toBe(2);
 await page.evaluate(()=>failSave=false);await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter angelegt');await expect(page.locator('#spEmployeeProfile h2')).toHaveText('Neue Testperson');expect(await page.evaluate(()=>employees.length)).toBe(3);
 const payload=await page.evaluate(()=>calls.at(-1).payload);expect(payload.first_name).toBe('Neue');expect(payload.company_id).toBe(theme==='dark'?'company-a':'company-b');expect(payload.shift_permissions).toEqual(['FD','SD','ND']);expect(payload.qualifications).toContain('__sp:planningTeam=E');expect(payload.qualifications).toContain('__sp:monthlyHours=180');expect(payload.qualifications).toContain('__sp:maxConsecutive=8');expect(payload.qualifications).toContain('__sp:rhythmStart=2026-12-01');
 await page.locator('[data-tab="qualifications"]').click();await expect(page.locator('#spSaveQualifications')).toHaveText('Qualifikationen speichern');await expect(page.locator('[data-qual][value="ND"]')).toBeChecked();expect(errors).toEqual([]);
});
test('new FD-only employee can configure the fixed week, see validation and discard the draft safely',async({page})=>{
 await fixture(page,'dark');await page.locator('#addEmployeeBtn').click();await page.locator('#spSave').click();await expect(page.locator('#spFormError')).toContainText('Vorname fehlt.');expect(await page.evaluate(()=>calls.length)).toBe(0);
 await page.locator('#spFirst').fill('Frühdienst');await page.locator('#spLast').fill('Test');await page.locator('#spPersonnel').fill('FD-TEST');await page.locator('#spRhythmMode').selectOption('required');await page.locator('#spRhythmStart').fill('2026-11-30');for(let i=0;i<7;i++)await page.locator(`[data-rhythm-day="${i}"]`).selectOption(i<5?'FD':'FREI');
 await page.locator('[data-tab="qualifications"]').click();await page.locator('#spExclusiveShift').selectOption('FD');await page.locator('[data-tab="overview"]').click();await expect(page.locator('#spFirst')).toHaveValue('Frühdienst');await expect(page.locator('[data-rhythm-day="0"]')).toHaveValue('FD');await expect(page.locator('[data-rhythm-day="6"]')).toHaveValue('FREI');await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter angelegt');expect(await page.evaluate(()=>calls.at(-1).payload.shift_permissions)).toEqual(['FD']);
 await page.locator('#addEmployeeBtn').click();await page.locator('#spFirst').fill('Nicht speichern');await page.locator('#spCancelNew').click();await expect(page.locator('#spEmployeeProfile')).toContainText('Noch kein Mitarbeiter gewählt');await page.locator('#addEmployeeBtn').click();await expect(page.locator('#spFirst')).toHaveValue('');
 await page.locator('#spFirst').fill('Firma A Entwurf');await page.evaluate(()=>{SFBackend.companyId='company-other';employees=[makeEmployee('OTHER')];selectedEmployeeId=null;renderEmployees()});await expect(page.locator('#spEmployeeProfile')).toContainText('Noch kein Mitarbeiter gewählt');await page.locator('#addEmployeeBtn').click();await expect(page.locator('#spFirst')).toHaveValue('');
});

async function centralFixture(page,theme){
 await fixture(page,theme);
 await page.addScriptTag({content:read('assets/planning-teams-v1.js')});
 await page.addScriptTag({content:read('assets/settings-management-v2.js').replace(/\}\)\(\);\s*$/,'window.centralSettingsFixture={planning,css};})();')});
 await page.evaluate(()=>{
  window.DAYS=['Mo','Di','Mi','Do','Fr','Sa','So'];window.globalSoll={FD:4,SD:4,ND:4};window.dailySoll={};window.centralRows=[];window.previewClears=0;
  window.clearAutoPlanPreview=()=>previewClears++;SFShiftModels.enhance=()=>{};
  SFBackend.client.rpc=async(name,args)=>{calls.push({name,args});if(failSave)return{error:{message:'Teamregel offline'}};const row={team_code:args.p_team_code,start_date:args.p_start_date,pattern:args.p_pattern,start_offset:args.p_start_offset};centralRows=centralRows.filter(r=>r.team_code!==row.team_code).concat(row);return{data:row};};
  centralRows=['A','B','C','D','E'].map((team,i)=>({team_code:team,start_date:'2026-12-01',pattern:['FD','FD','SD','SD','FREI','ND','ND','FREI','FREI','FREI'],start_offset:i*2}));
  SFPlanningTeams.apply(centralRows,SFBackend.companyId);
  const host=document.createElement('section');host.id='view-settings';host.className='view active';host.innerHTML='<div id="sfSettingBody"></div>';document.querySelector('.content').appendChild(host);centralSettingsFixture.css();centralSettingsFixture.planning(document.querySelector('#sfSettingBody'));
 });
}
for(const theme of ['dark','light'])test(`4/3/3/2 workrest cycle persists editable OT exceptions in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.evaluate(()=>{for(const id of ['OT1','OT2','OT3'])TYPES.push({id,name:id,start:'08:00',end:'16:00'});const e=employees[0];Object.assign(e,{rhythmPattern:'ALLE, ALLE, ALLE, ALLE, FREI, FREI, FREI, ALLE, ALLE, ALLE, FREI, FREI',rhythmExemptOt:true,maxWeeklyHours:50,monthlyHours:180,shifts:TYPES.map(t=>t.id)});renderEmployees()});
 await expect(page.locator('#spRhythmExemptOt')).toBeChecked();await expect(page.locator('#spMaxWeekly')).toHaveValue('50');
 await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter gespeichert');expect(await page.evaluate(()=>calls.at(-1).payload.qualifications)).toContain('__sp:rhythmExemptOt=true');
 await page.evaluate(()=>{const q=calls.at(-1).payload.qualifications;employees[0]={...makeEmployee('S'),rhythmMode:undefined,rhythmKind:undefined,rhythmStart:undefined,rhythmPattern:undefined,maxWeeklyHours:undefined,qualifications:q,shifts:TYPES.map(t=>t.id)};renderEmployees()});
 await expect(page.locator('#spRhythmExemptOt')).toBeChecked();await expect(page.locator('#spRhythmKind')).toHaveValue('cycle');await expect(page.locator('#spMaxWeekly')).toHaveValue('50');
 await page.evaluate(()=>{assignEmployeeByDrop('S','FD','2026-12-07');assignEmployeeByDrop('S','OT1','2026-12-07')});expect(await page.evaluate(()=>manualCalls.map(x=>x.type))).toEqual(['OT1']);
 expect(await page.evaluate(()=>autoEligibleEmployees('FD','2026-12-07').some(x=>x.e.id==='S'))).toBe(false);expect(await page.evaluate(()=>autoEligibleEmployees('OT2','2026-12-07').some(x=>x.e.id==='S'))).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`workrest-${theme}.png`),fullPage:true});
 await page.locator('#spRhythmExemptOt').uncheck();await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter gespeichert');expect(await page.evaluate(()=>calls.at(-1).payload.qualifications)).not.toContain('__sp:rhythmExemptOt=true');expect(await page.evaluate(()=>autoEligibleEmployees('OT2','2026-12-07').some(x=>x.e.id==='S'))).toBe(false);expect(errors).toEqual([]);
});
for(const theme of ['dark','light'])test(`central team editor persists independent rhythms and inherited staff rules in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await centralFixture(page,theme);
 await expect(page.locator('#sfPlanningTeams [data-edit-team]')).toHaveCount(5);await page.locator('[data-edit-team="A"]').click();await page.locator('#sfTeamStart').fill('2026-12-01');
 await page.locator('[data-preset]').click();for(let i=9;i>=3;i--)await page.locator(`[data-remove-day="${i}"]`).click();
 await page.locator('[data-day="0"]').selectOption('ND');await page.locator('[data-day="1"]').selectOption('FREI');await page.locator('[data-day="2"]').selectOption('SD');await page.locator('#sfTeamOffset').selectOption('1');
 await expect(page.locator('.sf-team-preview')).toContainText('1.12.2026: Frei');await expect(page.locator('.sf-team-preview')).toContainText('2.12.2026: SD');
 await page.evaluate(()=>document.querySelector('#view-employees').classList.remove('active'));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`central-team-${theme}.png`),fullPage:true});
 const before=await page.evaluate(()=>JSON.stringify(employees));await page.getByRole('button',{name:'Team A speichern',exact:true}).click();await expect(page.locator('#toast')).toContainText('Team A gespeichert');
 expect(await page.evaluate(()=>JSON.stringify(employees))).toBe(before);expect(await page.evaluate(()=>previewClears)).toBe(1);expect(await page.evaluate(()=>calls.at(-1).args.p_company_id)).toBe(theme==='dark'?'company-a':'company-b');
 expect(await page.evaluate(()=>SFRhythm.check(employees[1],'ND','2026-12-03').allowed)).toBe(true);expect(await page.evaluate(()=>SFRhythm.check(employees[0],'FD','2026-12-01').allowed)).toBe(true);expect(await page.evaluate(()=>SFPlanningTeams.get('B').offset)).toBe(2);
 await page.evaluate(()=>{document.querySelector('#view-employees').classList.add('active');document.querySelector('#view-settings').classList.remove('active');selectedEmployeeId='A';renderEmployees()});await expect(page.locator('#spRhythmStart')).toBeDisabled();await expect(page.locator('#spPlanningTeamSummary')).toContainText('Einstieg an Tag 2');await expect(page.locator('#spPlanningTeamSummary')).toContainText('Frei');
 await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter gespeichert');expect(await page.evaluate(()=>calls.at(-1).payload.qualifications)).toContain('__sp:rhythmPattern=ND, FREI, SD');
 await page.evaluate(()=>{assignEmployeeByDrop('A','FD','2026-12-03');assignEmployeeByDrop('A','ND','2026-12-03')});expect(await page.evaluate(()=>manualCalls.map(x=>x.type))).toEqual(['ND']);expect(await page.evaluate(()=>autoEligibleEmployees('ND','2026-12-03').map(x=>x.e.id))).toEqual(['A']);
 await page.locator('#spPlanningTeam').selectOption('');await expect(page.locator('#spRhythmStart')).toBeEnabled();await expect(page.locator('#spRhythmMode')).toBeEnabled();
 await page.evaluate(()=>{document.querySelector('#view-settings').classList.add('active');document.querySelector('#view-employees').classList.remove('active')});await page.locator('[data-edit-team="B"]').click();await page.locator('[data-day="0"]').selectOption('ND');await page.evaluate(()=>failSave=true);await page.getByRole('button',{name:'Team B speichern',exact:true}).click();await expect(page.locator('.sf-team-message')).toContainText('Teamregel offline');await expect(page.getByRole('button',{name:'Team B speichern',exact:true})).toBeEnabled();expect(await page.evaluate(()=>SFPlanningTeams.get('B').pattern[0])).toBe('FD');
 await page.evaluate(()=>{SFPlanningTeams.apply(centralRows,SFBackend.companyId);SFBackend.companyId='different-company'});expect(await page.evaluate(()=>SFPlanningTeams.get('A'))).toBeNull();expect(errors).toEqual([]);
});
test('central editor supports adding/removing days and refuses unavailable permissions without a cloud call',async({page})=>{
 await centralFixture(page,'dark');await page.locator('[data-edit-team="A"]').click();await page.locator('[data-add-day]').click();await expect(page.locator('[data-day]')).toHaveCount(11);await page.locator('[data-remove-day="10"]').click();await expect(page.locator('[data-day]')).toHaveCount(10);
 await page.evaluate(()=>employees[1].shifts=['FD']);await page.getByRole('button',{name:'Team A speichern',exact:true}).click();await expect(page.locator('.sf-team-message')).toContainText('Schichtfreigaben');expect(await page.evaluate(()=>calls.length)).toBe(0);await page.locator('[data-cancel]').click();await expect(page.locator('.sf-team-editor')).toBeHidden();
});

for(const theme of ['dark','light'])test(`employment models apply monthly hours, save safely and retain old contracts in ${theme}`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,theme);
 await page.locator('#addEmployeeBtn').click();await expect(page.locator('#spEmployment option')).toHaveCount(3);
 expect(await page.locator('#spEmployment option').allTextContents()).toEqual(['Vollzeit 180','Teilzeit 162','Teilzeit 144']);await expect(page.locator('#spEmployment')).toHaveValue('Vollzeit 180');await expect(page.locator('#spMonthlyHours')).toHaveValue('180.00');
 await page.locator('#spEmployment').selectOption('Teilzeit 162');await expect(page.locator('#spMonthlyHours')).toHaveValue('162.00');await expect(page.locator('#spWeekly')).toHaveValue('40');await expect(page.locator('#spMaxWeekly')).toHaveValue('40');
 await page.locator('[data-tab="qualifications"]').click();await page.locator('[data-tab="overview"]').click();await expect(page.locator('#spEmployment')).toHaveValue('Teilzeit 162');await expect(page.locator('#spMonthlyHours')).toHaveValue('162.00');
 await page.locator('#spEmployment').selectOption('Teilzeit 144');await expect(page.locator('#spMonthlyHours')).toHaveValue('144.00');await page.locator('#spEmployment').selectOption('Vollzeit 180');await expect(page.locator('#spMonthlyHours')).toHaveValue('180.00');await page.locator('#spCancelNew').click();
 await page.evaluate(()=>{employees[0].employment='Teilzeit';employees[0].monthlyHours=160;selectedEmployeeId='S';teamFixture.renderProfile()});await expect(page.locator('#spEmployment option:checked')).toHaveText('Bisher: Teilzeit · 160 h/Monat');
 await page.locator('#spSave').click();await expect(page.locator('#toast')).toContainText('Mitarbeiter gespeichert');expect(await page.evaluate(()=>calls.at(-1).payload.employment)).toBe('Teilzeit');expect(await page.evaluate(()=>calls.at(-1).payload.qualifications)).toContain('__sp:monthlyHours=160');
 const before=await page.evaluate(()=>JSON.stringify(employees[0]));await page.locator('#spEmployment').selectOption('Teilzeit 144');await page.evaluate(()=>failSave=true);await page.locator('#spSave').click();await expect(page.locator('#spFormError')).toContainText('Speichern fehlgeschlagen');expect(await page.evaluate(()=>JSON.stringify(employees[0]))).toBe(before);await expect(page.locator('#spMonthlyHours')).toHaveValue('144.00');
 await page.evaluate(()=>failSave=false);await page.locator('#spSave').click();await expect(page.locator('#spEmployment')).toHaveValue('Teilzeit 144');expect(await page.evaluate(()=>calls.at(-1).payload.employment)).toBe('Teilzeit');expect(await page.evaluate(()=>calls.at(-1).payload.weekly_hours)).toBe(48);expect(await page.evaluate(()=>calls.at(-1).payload.company_id)).toBe(theme==='dark'?'company-a':'company-b');expect(await page.evaluate(()=>calls.at(-1).payload.qualifications)).toContain('__sp:monthlyHours=144');
 await page.evaluate(()=>{const payload=calls.at(-1).payload;employees[0]={...makeEmployee('S'),employment:payload.employment,qualifications:payload.qualifications};teamFixture.normalizeAll();teamFixture.renderProfile();window.plannedMonthlyHoursForEmployee=()=>142});await expect(page.locator('#spEmployment')).toHaveValue('Teilzeit 144');await expect(page.locator('#spMonthlyHours')).toHaveValue('144.00');expect(await page.evaluate(()=>autoEligibleEmployees('FD','2026-12-01').some(x=>x.e.id==='S'))).toBe(false);
 await page.evaluate(()=>window.plannedMonthlyHoursForEmployee=()=>136);expect(await page.evaluate(()=>autoEligibleEmployees('FD','2026-12-01').some(x=>x.e.id==='S'))).toBe(true);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`employment-models-${theme}.png`),fullPage:true});expect(errors).toEqual([]);
});
