const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../assets/employee-management-v2.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.statusFixture={overviewTab,bindTab};})();');
const dataSource=fs.readFileSync(path.join(__dirname,'../../assets/supabase-data-v1.js'),'utf8');
async function fixture(page,company){
 await page.route('https://schichtfunk.de/__employee-status-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__employee-status-fixture');
 await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:14px Arial;background:#06101b;color:#edf6ff;padding:12px}.sp-profile-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}label span{display:block}input,select,textarea{box-sizing:border-box;width:100%;min-height:44px}button{min-height:44px;margin:6px;padding:10px}h3{margin-top:25px}</style><div id="fixtureProfile"></div><div id="pool"></div><p id="toast"></p>');
 await page.addScriptTag({content:`Object.defineProperty(document,'readyState',{get:()=> 'loading'});window.employees=[{id:'test',_dbId:'test-db',first:'Fiktiver',last:'Mitarbeiter',personnelNo:'TEST',status:'inactive',availabilityStatus:'red',shifts:['FD'],qualifications:['FD','__sp:availability=red'],weeklyHours:40,maxWeeklyHours:40}];window.assignments=[];window.absences=[];window.timeEntries={};window.selectedEmployeeId='test';window.calls=[];window.failSave=false;window.renderPlanEmployeePool=()=>document.querySelector('#pool').textContent=employees[0].status==='active'&&employees[0].availabilityStatus!=='red'?'Fiktiver Mitarbeiter einplanbar':'Nicht im Planungspool';window.showSaveToast=(s,e)=>document.querySelector('#toast').textContent=s+(e?' · '+e:'');window.renderEmployees=()=>{document.querySelector('#fixtureProfile').innerHTML=statusFixture.overviewTab(employees[0],false);statusFixture.bindTab(employees[0],false)};window.SFBackend={companyId:${JSON.stringify(company)},ready:true,role:'OWNER',empDb:new Map(),empLocal:new Map(),client:{from(table){const q={table,filters:[]};return{update(payload){q.payload=payload;return this},eq(k,v){q.filters.push([k,v]);return this},is(k,v){q.filters.push([k,v]);return this},select(){return this},async single(){calls.push(q);return failSave?{error:{message:'Speichern fehlgeschlagen'}}:{data:{id:'test-db',status:q.payload.status}}}}}}};`});
 await page.addScriptTag({content:dataSource});await page.addScriptTag({content:source});await page.evaluate(()=>{renderEmployees();renderPlanEmployeePool()});
}
for(const company of ['a','b'])test(`reactivate and deactivate an employee in company ${company}`,async({page})=>{
 await fixture(page,company);await expect(page.getByRole('button',{name:'Aktivieren',exact:true})).toBeVisible();page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Aktivieren',exact:true}).click();expect(await page.evaluate(()=>calls.length)).toBe(0);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Aktivieren',exact:true}).click();await expect(page.getByRole('button',{name:'Deaktivieren',exact:true})).toBeVisible();await expect(page.locator('#spStatus')).toHaveValue('active');await expect(page.locator('#pool')).toHaveText('Fiktiver Mitarbeiter einplanbar');expect(await page.evaluate(()=>calls[0].filters)).toEqual([['company_id',company],['id','test-db'],['deleted_at',null]]);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Deaktivieren',exact:true}).click();await expect(page.getByRole('button',{name:'Aktivieren',exact:true})).toBeVisible();await expect(page.locator('#pool')).toHaveText('Nicht im Planungspool');
 await page.locator('#spStatus').selectOption('active');await expect(page.locator('#spAvailabilityStatus')).toHaveValue('green');
});
test('failed activation keeps an employee inactive and reports the error',async({page})=>{
 await fixture(page,'a');await page.evaluate(()=>failSave=true);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Aktivieren',exact:true}).click();await expect(page.locator('#toast')).toContainText('Speichern fehlgeschlagen');await expect(page.locator('#spStatus')).toHaveValue('inactive');await expect(page.locator('#pool')).toHaveText('Nicht im Planungspool');
});
