const {test,expect}=require('@playwright/test');
const fs=require('fs'),path=require('path'),{html,root}=require('../browser/planning-assistant-fixture.cjs');
test.use({launchOptions:process.env.SF_ASSISTANT_BROWSER_EXECUTABLE?{executablePath:process.env.SF_ASSISTANT_BROWSER_EXECUTABLE}:{}});
test('improvement preview, cancellation, confirmed draft, outage and scoped journal',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='sf-assistant.test')return route.abort();if(u.pathname.startsWith('/assets/')){const f=path.join(root,u.pathname);return route.fulfill({contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':'application/octet-stream',body:fs.readFileSync(f)});}if(u.pathname==='/qa-run.js')return route.fulfill({contentType:'application/javascript',body:''});return route.fulfill({contentType:'text/html',body:html});});
 await page.goto('http://sf-assistant.test/');
 await page.evaluate(()=>{sessionStorage.setItem('sf_demo_session_v1','active');SFCompliance.policy.solidPlanningRules={enabled:true,confirmedRulesVersion:2,timezone:'Europe/Berlin'};assignments=[];globalSoll={FD:0,SD:0,ND:0};dailySoll={'2026-12-02':{FD:1}};employees.forEach((e,i)=>{e.personnelNo=String(119+i);e.employment='Vollzeit';delete e.planningTeam;});});
 await page.getByRole('button',{name:'Planungsassistent',exact:true}).click();
 const ask=async q=>{await page.evaluate(()=>SFPlanningAssistant.open());await page.locator('#sfPlanningChatInput').fill(q);await page.getByRole('button',{name:'Frage senden'}).click();};
 await ask('Verbesserungsvorschläge erstellen');
 await expect(page.locator('#sfPlanningChatLog')).toContainText('Konkrete Verbesserungen – Vorschau');
 expect(await page.evaluate(()=>assignments.length)).toBe(0);
 const take=()=>page.getByRole('button',{name:'Vorschläge als Entwurf übernehmen',exact:true}).last();
 await take().click();await expect(page.getByRole('dialog',{name:'Geprüfte Änderungen als Entwurf übernehmen?'})).toBeVisible();
 await page.getByRole('button',{name:'Abbrechen',exact:true}).click();expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await take().click();await page.getByRole('button',{name:'Jetzt als Entwurf übernehmen',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>assignments.length)).toBe(1);expect(await page.evaluate(()=>assignments[0].publishedAt||assignments[0].status==='PUBLISHED')).toBeFalsy();
 await ask('Was passiert wenn Mitarbeiter 119 am 02.12.2026 ausfällt?');await expect(page.locator('#sfPlanningChatLog')).toContainText('Ausfall durchspielen – Simulation');expect(await page.evaluate(()=>assignments.length)).toBe(1);
 await page.evaluate(()=>{sessionStorage.removeItem('sf_demo_session_v1');document.dispatchEvent(new CustomEvent('sf:planning-analysis-ready',{detail:{dates:['2026-12-01','2026-12-02'],assignments:assignments.slice()}}));});
 await ask('Planungsprotokoll Dezember 2026');await expect(page.locator('#sfPlanningChatLog')).toContainText('Gespeicherte Planungsgründe');
 const stored=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('sf-planning-runs-v1|')).map(k=>localStorage.getItem(k)).join(''));expect(stored).not.toContain('Anna');expect(stored).toContain('Enddiagnose');
 await page.evaluate(()=>{
   assignments=[];window.assistantRefreshes=0;window.assistantRpcCalls=[];
   SFBackend.sync=async()=>{};
   SFBackend.hydrate=async()=>{SFBackend.suppressSync=true;await new Promise(resolve=>setTimeout(resolve,650));dailySoll['2026-12-02'].FD=2;window.assistantRefreshes++;SFBackend.suppressSync=false;};
   SFBackend.client={rpc:async(name)=>{window.assistantRpcCalls.push(name);return {data:{fingerprint:'fresh-data',protectedIds:[]}};}};
   document.body.append(document.createElement('span'));
 });
 await expect.poll(()=>page.evaluate(()=>!!SFBackend.hydrate.__sfChatGuard)).toBe(true);
 await ask('Verbesserungsvorschläge erstellen');
 await expect(page.locator('#sfPlanningChatLog')).toContainText(/Konkrete Verbesserungen\s*[-–]\s*Vorschau/);
 expect(await page.evaluate(()=>window.assistantRefreshes)).toBe(1);
 expect(await page.evaluate(()=>window.assistantRpcCalls)).toEqual(['preview_planning_period']);
 expect(await page.evaluate(()=>assignments.length)).toBe(0);
 await expect(page.locator('#sfPlanningChatLog')).toContainText('2 → 0');
 await page.evaluate(()=>{SFBackend.companyId='another-company';SFPlanningAssistant.reset();});await ask('Planungsprotokoll Dezember 2026');await expect(page.locator('#sfPlanningChatLog')).toContainText('Kein gespeichertes Planungsprotokoll');
 await page.evaluate(()=>{SFBackend.role='EMPLOYEE';});await expect(page.locator('#sfPlanningAssistantButton')).toBeHidden();expect(errors).toEqual([]);
});
