const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),source=fs.readFileSync(path.join(root,'index.html'),'utf8');
const section=id=>source.match(new RegExp('<section id="'+id+'"[\\s\\S]*?</section>'))[0];
const styles=[...source.matchAll(/<style[^>]*>[\s\S]*?<\/style>/g)].map(x=>x[0]).join('')+['manager-theme-v1.css','manager-typography-v1.css','manager-kpi-layout-v1.css','manager-schedule-time-layout-v1.css'].map(file=>'<style>'+fs.readFileSync(path.join(root,'assets',file),'utf8')+'</style>').join('');
const iso=h=>`2026-10-05T${String(h).padStart(2,'0')}:00:00Z`;
const data={as_of:iso(20),timezone:'Europe/Berlin',rows:[{assignment_id:'plan-a',employee_id:'person-a',employee_name:'Fiktive Testperson mit langem Namen',shift_code:'Fiktive Schicht',starts_at:iso(6),ends_at:iso(14),planned_break_minutes:0,actual_start:iso(6),actual_end:iso(14),actual_break_minutes:60,entry_status:'confirmed'}],qr_rows:[{id:'qr-a',employee_id:'person-a',employee_name:'Fiktive Testperson mit langem Namen',matched_assignment_id:'plan-a',started_at:iso(6),ended_at:iso(14),pause_minutes:60,terminal_name:'Fiktives Terminal',breaks:[{number:1,started_at:iso(10),ended_at:iso(11)}]},{id:'qr-extra',employee_id:'person-a',employee_name:'Fiktive Testperson mit langem Namen',started_at:iso(14),ended_at:iso(18),pause_minutes:0},{id:'qr-run',employee_id:'person-b',employee_name:'Fiktive laufende Testperson',started_at:iso(18),ended_at:null,pause_minutes:0}],confirmed_summary:[{employee_id:'person-a',employee_legacy_id:'person-a',confirmed_seconds:43200},{employee_id:'person-b',employee_legacy_id:'person-b',confirmed_seconds:0}]};
const setup=`window.__data=${JSON.stringify(data)};window.__calls=[];window.__mode='ok';window.__external=[];
window.SFBackend={role:'OWNER',ready:true,companyId:'company-a',companyTimeZone:'Europe/Berlin',empDb:new Map(),client:{rpc:async(name,args)=>{window.__calls.push({name,args});if(window.__mode==='hold'){window.__mode='ok';return new Promise(resolve=>window.__release=()=>resolve({data:window.__data}))}if(window.__mode==='error')return{error:{message:'Fiktiver Testfehler'}};return{data:args.p_company_id==='company-b'?{...window.__data,rows:[],qr_rows:[],confirmed_summary:[]}:window.__data}}}};
window.employees=[{id:'person-a',status:'active',first:'Fiktive',last:'Testperson',weeklyHours:40},{id:'person-b',status:'active',first:'Fiktive',last:'Laufende',weeklyHours:40}];
window.reportDates=()=>['2026-10-01','2026-10-31'];window.hoursForEmployeeDates=()=>8;window.reportTargetForEmployee=()=>160;
window.renderReports=()=>{document.getElementById('reportStats').innerHTML='<div class="stat"><div><small>Planstunden</small><strong>8,0</strong></div></div>';document.getElementById('reportHours').innerHTML='Planwerte'};`;
test.use({video:'off',launchOptions:process.env.SF_CENTRAL_BROWSER_EXECUTABLE?{executablePath:process.env.SF_CENTRAL_BROWSER_EXECUTABLE}:{}});
async function fixture(page){
 const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='qr-central.test'){external.push(u.href);return route.abort()}if(u.pathname.startsWith('/assets/'))return route.fulfill({contentType:'application/javascript',body:fs.readFileSync(path.join(root,u.pathname.slice(1)),'utf8')});return route.fulfill({contentType:'text/html',body:`<!doctype html><html data-sf-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${styles}</head><body><div id="appShell"><main class="main">${section('view-time')}${section('view-reports')}</main></div><script>${setup}</script><script src="/assets/central-time-core-v1.js"></script><script src="/assets/supabase-time-tracking-v1.js"></script><script src="/assets/central-time-reports-v1.js"></script></body></html>`})});
 await page.goto('http://qr-central.test/');
 await page.evaluate(()=>{document.getElementById('view-time').classList.add('active');document.getElementById('timePeriod').value='month';const input=document.createElement('input');input.id='sfTimeMonthPicker';input.type='month';input.value='2026-10';document.getElementById('timePeriod').after(input);return window.renderTimeTracking()});
 await expect(page.locator('#timeTableBody tr')).toHaveCount(3);return{errors,external};
}
test('completed, matched and unplanned QR are deduplicated; running remains provisional',async({page})=>{const c=await fixture(page);const cards=page.locator('#timeStats .stat');await expect(cards.nth(1).locator('strong')).toHaveText('12,0');await expect(cards.nth(1)).toContainText('2,0 Std. laufen');await expect(page.locator('#timeTableBody')).toContainText('Ohne Dienstplanschicht');await expect(page.locator('#timeTableBody')).toContainText('bezahlt');await expect(page.locator('#sfTimeBulkOpen')).toBeDisabled();expect(c.errors).toEqual([]);expect(c.external).toEqual([])});
test('QR detail retains original pauses and avoids a new editable QR record',async({page})=>{const c=await fixture(page);await page.locator('[data-time-qr="plan-a"]').click();const modal=page.locator('#sfTimeModal');await expect(modal).toContainText('Pausen gesamt: 60 Min.');await expect(modal).toContainText('Pause 1:');await expect(modal.getByRole('button',{name:'Schichtmeldung prüfen'})).toBeVisible();await modal.getByRole('button',{name:'Schließen'}).click();expect(await page.evaluate(()=>window.__calls.every(c=>c.name==='manager_central_time_entries'))).toBe(true);expect(c.errors).toEqual([])});
test('statistics stay readable in dark and light mode with larger text',async({page},info)=>{await fixture(page);for(const theme of ['dark','light']){await page.evaluate(t=>{document.documentElement.dataset.sfTheme=t;document.documentElement.style.fontSize='18px'},theme);const widths=await page.locator('#timeStats .stat>div').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().width));expect(Math.min(...widths)).toBeGreaterThan(120);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);expect(overflow).toBe(false);await page.screenshot({path:test.info().outputPath('central-'+theme+'.png'),fullPage:true})}});
test('dashboard actual hours use central confirmed values',async({page})=>{const c=await fixture(page);await page.evaluate(()=>{document.getElementById('view-time').classList.remove('active');document.getElementById('view-reports').classList.add('active');window.renderReports()});await expect(page.locator('#sfCentralReportHours strong')).toHaveText('12,0');await expect(page.locator('#reportHours')).toContainText('IST 12,0 / SOLL 160 Std.');await expect(page.locator('#reportHours')).toContainText('Plan 8 Std.');expect(c.errors).toEqual([])});
test('delayed response from previous company cannot overwrite the new company',async({page})=>{await fixture(page);await page.evaluate(()=>{window.__mode='hold';window.renderTimeTracking()});await page.evaluate(()=>{window.SFBackend.companyId='company-b';return window.renderTimeTracking()});await page.evaluate(()=>window.__release());await expect(page.locator('#timeTableBody')).toContainText('Keine Schichten oder QR-Buchungen');await expect(page.locator('#timeTableBody')).not.toContainText('Fiktive Testperson mit langem Namen')});
test('RPC failure displays unavailable hours and protects bulk action',async({page})=>{await fixture(page);await page.evaluate(()=>{window.__mode='error';return window.renderTimeTracking()});await expect(page.locator('#timeStats strong')).toHaveText('–');await expect(page.locator('#timeTableBody')).toContainText('Zeiten konnten nicht aktualisiert werden');await expect(page.locator('#sfTimeBulkOpen')).toBeDisabled()});
