const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
if(process.env.SF_EXPORT_LIB_ROOT)module.paths.unshift(path.join(process.env.SF_EXPORT_LIB_ROOT,'node_modules'));
const read=file=>fs.readFileSync(path.join(__dirname,'../../',file),'utf8');
let deps,dependencyError;
try{deps={xlsx:path.join(path.dirname(require.resolve('xlsx')),'dist/xlsx.full.min.js'),pdf:path.join(path.dirname(require.resolve('jspdf')),'jspdf.umd.min.js'),table:require.resolve('jspdf-autotable')};if(!Object.values(deps).every(p=>fs.existsSync(p)))throw Error('Browser distributions were not found.')}catch(error){deps=null;dependencyError=error.message}
if(process.env.SF_EXPORT_REAL_LIBRARIES==='1'&&!deps)throw Error('Real XLSX/PDF test dependencies are required: '+dependencyError);
async function fixture(page){
  await page.route('https://schichtfunk.de/__schedule-export',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="de"><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__schedule-export');
  await page.setContent('<div class="company-card"><b>Test GmbH</b></div><section id="view-schedule"><div class="page-head"><h1>Monatsplanung</h1><button>Veröffentlichen</button></div><input id="planEmployeeSearch" value="Anna"></section>');
  await page.addScriptTag({content:`window.SFBackend={companyId:'company-a',role:'PLANNER',ready:true};window.SchichtFunkCalendarView={getPeriod:()=>({mode:'month',start:'2026-12-01',end:'2026-12-31'})};window.employees=[{id:'A',first:'Anna',last:'Test',team:'Leipzig',status:'active',personnelNo:'001',planningTeam:'A',monthlyHours:180},{id:'B',first:'Berta',last:'Test',team:'Recklinghausen',status:'active',monthlyHours:162},{id:'C',first:'Chris',last:'Other',status:'active',company_id:'company-b'}];window.TYPES=[{id:'FD',name:'Frühdienst',start:'06:00',end:'14:00'},{id:'ND',name:'Nachtdienst',start:'22:00',end:'06:00'}];window.assignments=[{employeeId:'A',date:'2026-12-01',type:'FD'},{employeeId:'A',date:'2026-12-31',type:'ND'},{employeeId:'B',date:'2026-12-02',type:'FD',start:'07:00',end:'14:00'},{employeeId:'C',date:'2026-12-01',type:'FD',company_id:'company-b'}];window.absences=[];window.getSoll=()=>2;`});
  await page.addStyleTag({content:read('assets/schedule-export-v1.css')});
  await page.addScriptTag({content:read('assets/schedule-export-core-v1.js')});await page.addScriptTag({content:read('assets/schedule-export-v1.js')});
}
async function cloudFixture(page,extra={}){
 await fixture(page);
 await page.evaluate(extra=>{
  window.cloudCalls=[];window.cloudFailure=null;window.cloudCompanySwitch=false;
  window.cloudTables={companies:[{id:'company-a',name:'Aktuelle Firma',timezone:'Europe/Berlin'}],employees:[{id:'db-a',legacy_id:'A',company_id:'company-a',first_name:'Anna',last_name:'Aktuell',personnel_no:'001',status:'active',weekly_hours:40,qualifications:['__sp:monthlyHours=180','__sp:team=Leipzig','__sp:planningTeam=B']}],shift_assignments:[{id:'d1',company_id:'company-a',employee_id:'db-a',status:'DRAFT',shift_code:'ND',starts_at:'2027-01-31T21:00:00Z',ends_at:'2027-02-01T05:00:00Z'},{id:'d2',company_id:'company-a',employee_id:'db-a',status:'CANCELLED',shift_code:'FD',starts_at:'2027-01-01T05:00:00Z',ends_at:'2027-01-01T13:00:00Z'},{id:'d3',company_id:'company-b',employee_id:'db-a',status:'DRAFT',shift_code:'FD',starts_at:'2027-01-01T05:00:00Z',ends_at:'2027-01-01T13:00:00Z'},{id:'d4',company_id:'company-a',employee_id:'db-a',status:'DRAFT',shift_code:'ND',starts_at:'2026-12-31T21:00:00Z',ends_at:'2027-01-01T05:00:00Z'}],absences:[],global_staffing_requirements:[{company_id:'company-a',shift_code:'ND',required_count:2}],daily_staffing_overrides:[],shift_templates:[{id:'t1',company_id:'company-a',code:'ND',name:'Nachtdienst',default_start:'22:00:00',default_end:'06:00:00',active:true}],...extra};
  SFBackend.client={from(table){const filters=[];let size=500,offset=0,isSingle=false,orders=[];const q={select(){return q},eq(k,v){filters.push(row=>row[k]===v);return q},neq(k,v){filters.push(row=>row[k]!==v);return q},gte(k,v){filters.push(row=>row[k]>=v);return q},lt(k,v){filters.push(row=>row[k]<v);return q},gt(k,v){filters.push(row=>row[k]>v);return q},order(key){orders.push(key);return q},range(start,end){offset=start;size=end-start+1;return q},limit(n){size=n;return q},single(){isSingle=true;return q},then(resolve,reject){cloudCalls.push(table);if(cloudCompanySwitch)SFBackend.companyId='company-b';const rows=cloudTables[table].filter(row=>filters.every(f=>f(row))).sort((a,b)=>{for(const key of orders){const diff=String(a[key]||'').localeCompare(String(b[key]||''));if(diff)return diff}return 0}).slice(offset,offset+size);return Promise.resolve({data:isSingle?rows[0]:rows,error:cloudFailure===table?{message:'Cloud-Lesefehler'}:null}).then(resolve,reject)}};return q}};
  employees=[];assignments=[];SchichtFunkCalendarView.getPeriod=()=>({mode:'month',start:'2027-01-01',end:'2027-01-31'});
 },extra);
}
test('January export reads current drafts despite an empty calendar cache and preserves local state',async({page})=>{
 await cloudFixture(page);const result=await page.evaluate(async()=>{const before=SFScheduleExport.snapshot('2027-01'),plan=await SFScheduleExport.freshSnapshot('2027-01');return {before:before.shiftCount,count:plan.shiftCount,hours:plan.hours,status:plan.status,row:plan.rows[0],employees,assignments,calls:cloudCalls}});
 expect(result.before).toBe(0);expect(result.count).toBe(1);expect(result.hours).toBe(8);expect(result.status).toBe('Entwurf');expect(result.row.person.name).toBe('Anna Aktuell');expect(result.row.person.team).toBe('B');expect(result.row.person.site).toBe('Leipzig');expect(result.row.targetHours).toBe(180);expect(result.row.cells[30].pdf).toBe('ND');expect(result.employees).toEqual([]);expect(result.assignments).toEqual([]);expect(result.calls.sort()).toEqual(['absences','companies','daily_staffing_overrides','employees','global_staffing_requirements','shift_assignments','shift_templates']);
});
test('cloud export reads all pages without the 1000-assignment cap',async({page})=>{
 const shift_assignments=Array.from({length:1001},(_,i)=>({id:String(i).padStart(5,'0'),company_id:'company-a',employee_id:'db-a',status:'DRAFT',shift_code:'ND',starts_at:'2027-01-01T21:00:00Z',ends_at:'2027-01-02T05:00:00Z'}));await cloudFixture(page,{shift_assignments});
 const result=await page.evaluate(async()=>{const p=await SFScheduleExport.freshSnapshot('2027-01');return {count:p.shiftCount,hours:p.hours,pages:cloudCalls.filter(t=>t==='shift_assignments').length}});expect(result).toEqual({count:1001,hours:8008,pages:3});
});
test('read failures, company changes and pending edits block stale downloads and restore controls',async({page})=>{
 await cloudFixture(page);await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();await expect(page.getByRole('button',{name:'PDF herunterladen'})).toBeEnabled();let downloads=0;page.on('download',()=>downloads++);
 for(const [state,message] of [['failure','Cloud-Lesefehler'],['pending','noch gespeichert'],['switch','Unternehmen wurde gewechselt']]){
  await page.evaluate(state=>{SFBackend.companyId='company-a';cloudFailure=state==='failure'?'shift_assignments':null;SFBackend.syncTimer=state==='pending'?1:null;cloudCompanySwitch=state==='switch'},state);
  await page.getByRole('button',{name:'PDF herunterladen'}).click();await expect(page.locator('.sf-plan-export-status')).toContainText(message);await expect(page.locator('#sfPlanExportMonth')).toBeEnabled();
 }expect(downloads).toBe(0);
});
test('real January PDF includes fresh drafts, employee count and IST/SOLL hours',async({page})=>{
 test.skip(!deps,'Real export libraries run in CI.');await cloudFixture(page);for(const lib of [deps.pdf,deps.table])await page.addScriptTag({content:fs.readFileSync(lib,'utf8')});await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();
 const ready=page.waitForEvent('download');await page.getByRole('button',{name:'PDF herunterladen'}).click();const file=await ready;expect(file.suggestedFilename()).toBe('SchichtFunk_Gesamtdienstplan_2027-01.pdf');const raw=fs.readFileSync(await file.path()).toString('latin1');for(const text of ['Anna Aktuell','Januar 2027','Entwurf','1 / 1 Mitarbeiter','8,00 h','180,00 h','ND','Gesamtobjekt','496,00','488,00','Offene Dienste - Datum'])expect(raw).toContain(text);await expect(page.locator('.sf-plan-export-summary')).toContainText('1 Mitarbeiter · 1 Dienste · 8 Planstunden');
});
test('one export action selects the complete month and ignores employee search; company boundaries and roles are enforced',async({page})=>{
  await fixture(page);await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();await expect(page.locator('#sfPlanExportMonth')).toHaveValue('2026-12');await expect(page.locator('.sf-plan-export-summary')).toContainText('31 Tage · 2 Mitarbeiter · 3 Dienste · 23 Planstunden');
  const plan=await page.evaluate(()=>SFScheduleExport.snapshot('2026-12'));expect(plan.rows.map(r=>r.person.id)).toEqual(['A','B']);expect(plan.days).toHaveLength(31);
  await page.evaluate(()=>SFBackend.role='EMPLOYEE');const denied=await page.evaluate(()=>{try{SFScheduleExport.snapshot('2026-12');return false}catch{return true}});expect(denied).toBe(true);
});
test('library failures show a retryable message and restore the controls',async({page})=>{
  await fixture(page);await page.route('https://cdn.jsdelivr.net/**',route=>route.abort());await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();await page.getByRole('button',{name:'Excel herunterladen'}).click();await expect(page.locator('.sf-plan-export-status')).toContainText('konnte nicht geladen werden');await expect(page.getByRole('button',{name:'Excel herunterladen'})).toBeEnabled();await expect(page.locator('#sfPlanExportMonth')).toBeEnabled();
});
test('real XLSX and PDF downloads contain the complete December plan and the PDF appendix',async({page})=>{
  test.skip(!deps,'Real export libraries run in CI.');await fixture(page);for(const lib of [deps.xlsx,deps.pdf,deps.table])await page.addScriptTag({content:fs.readFileSync(lib,'utf8')});
  await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();
  const xlsxReady=page.waitForEvent('download');await page.getByRole('button',{name:'Excel herunterladen'}).click();const xlsx=await xlsxReady;expect(xlsx.suggestedFilename()).toBe('SchichtFunk_Gesamtdienstplan_2026-12.xlsx');await xlsx.saveAs(test.info().outputPath('Gesamt.xlsx'));const bytes=fs.readFileSync(await xlsx.path()),X=require('xlsx'),wb=X.read(bytes,{type:'buffer'});expect(wb.SheetNames).toEqual(['Monatsplan','Schichtdetails','Besetzung','Hinweise']);const matrix=X.utils.sheet_to_json(wb.Sheets.Monatsplan,{header:1});expect(matrix[6]).toHaveLength(38);expect(matrix[7][0]).toBe('001');expect(matrix[7][33]).toContain('ND 22:00');expect(matrix[8][1]).toBe('Berta Test');expect(matrix[7].slice(-4)).toEqual([2,16,180,-164]);expect(matrix[8].slice(-4)).toEqual([1,7,162,-155]);expect(wb.Sheets.Monatsplan.AL8.f).toBe('AJ8-AK8');
  const pdfReady=page.waitForEvent('download');await page.getByRole('button',{name:'PDF herunterladen'}).click();const pdf=await pdfReady;expect(pdf.suggestedFilename()).toBe('SchichtFunk_Gesamtdienstplan_2026-12.pdf');await pdf.saveAs(test.info().outputPath('Gesamt.pdf'));const raw=fs.readFileSync(await pdf.path()).toString('latin1');expect(raw.startsWith('%PDF-')).toBe(true);expect(raw).toContain('SchichtFunk');expect(raw).toContain('Anna Test');expect(raw).toContain('07:00');expect(raw).toContain('Berta Test');expect(raw).toContain('Plan-IST');expect(raw).toContain('SOLL');expect(raw).toContain('-164,00');expect(raw).toContain('180,00');
});

test('PDF location selector uses employee sites while overview and Excel retain all employees',async({page})=>{
 await fixture(page);await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();
 expect(await page.locator('#sfPlanExportScope option').allTextContents()).toEqual(['Leipzig','Recklinghausen','Gesamt']);await expect(page.locator('#sfPlanExportScope')).toHaveValue('Gesamt');
 const before=await page.evaluate(()=>JSON.stringify({employees,assignments,absences}));await page.locator('#sfPlanExportScope').selectOption('Leipzig');await expect(page.locator('.sf-plan-export-summary')).toContainText('1 Mitarbeiter · 2 Dienste · 16 Planstunden');
 await page.locator('#sfPlanExportScope').selectOption('Recklinghausen');await expect(page.locator('.sf-plan-export-summary')).toContainText('1 Mitarbeiter · 1 Dienste · 7 Planstunden');await expect(page.locator('#sfPlanExportScopeHint')).toContainText('Standort / Zugehörigkeit');await page.screenshot({path:test.info().outputPath('PDF-Auswahl.png'),fullPage:true});
 await page.evaluate(()=>employees[1].team='');await page.locator('#sfPlanExportScope').selectOption('Gesamt');await page.locator('#sfPlanExportScope').selectOption('Recklinghausen');await expect(page.locator('.sf-plan-export-summary')).toContainText('Keine Mitarbeiter');await expect(page.getByRole('button',{name:'PDF herunterladen'})).toBeDisabled();await expect(page.getByRole('button',{name:'Excel herunterladen'})).toBeEnabled();
 await page.evaluate(()=>employees[1].team='Recklinghausen');await page.locator('#sfPlanExportScope').selectOption('Gesamt');expect(await page.evaluate(()=>JSON.stringify({employees,assignments,absences}))).toBe(before);await expect(page.locator('#planEmployeeSearch')).toHaveValue('Anna');
 await page.getByRole('button',{name:'Schließen',exact:true}).click();await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();await expect(page.locator('#sfPlanExportScope')).toHaveValue('Gesamt');
});
test('real location PDFs exclude other-site employees and appendix data while Excel stays complete',async({page})=>{
 test.skip(!deps,'Real export libraries run in CI.');await fixture(page);for(const lib of [deps.xlsx,deps.pdf,deps.table])await page.addScriptTag({content:fs.readFileSync(lib,'utf8')});
 await page.getByRole('button',{name:'Gesamtdienstplan als Excel oder PDF exportieren'}).click();
 for(const [scope,included,excluded,hasAppendix] of [['Leipzig','Anna Test','Berta Test',false],['Recklinghausen','Berta Test','Anna Test',true]]){
  await page.locator('#sfPlanExportScope').selectOption(scope);const ready=page.waitForEvent('download');await page.getByRole('button',{name:'PDF herunterladen'}).click();const pdf=await ready;
  expect(pdf.suggestedFilename()).toBe(`SchichtFunk_Dienstplan_${scope}_2026-12.pdf`);await pdf.saveAs(test.info().outputPath(scope+'.pdf'));const raw=fs.readFileSync(await pdf.path()).toString('latin1');expect(raw.startsWith('%PDF-')).toBe(true);expect(raw).toContain(scope);expect(raw).toContain(included);expect(raw).not.toContain(excluded);expect(raw.includes('07:00')).toBe(hasAppendix);
 }
 await page.evaluate(()=>assignments=[]);await page.locator('#sfPlanExportScope').selectOption('Leipzig');const blankReady=page.waitForEvent('download');await page.getByRole('button',{name:'PDF herunterladen'}).click();const blank=await blankReady;await blank.saveAs(test.info().outputPath('Leipzig-ohne-Dienste.pdf'));expect(fs.readFileSync(await blank.path()).toString('latin1')).toContain('Anna Test');
 await page.evaluate(()=>assignments=[{employeeId:'A',date:'2026-12-01',type:'FD'},{employeeId:'B',date:'2026-12-02',type:'FD'}]);
 const ready=page.waitForEvent('download');await page.getByRole('button',{name:'Excel herunterladen'}).click();const file=await ready;expect(file.suggestedFilename()).toBe('SchichtFunk_Gesamtdienstplan_2026-12.xlsx');const X=require('xlsx'),wb=X.read(fs.readFileSync(await file.path()),{type:'buffer'}),matrix=X.utils.sheet_to_json(wb.Sheets.Monatsplan,{header:1});expect(matrix.some(row=>row.includes('Anna Test'))).toBe(true);expect(matrix.some(row=>row.includes('Berta Test'))).toBe(true);
});

test('fresh coverage ignores stale calendar targets and paginates daily overrides',async({page})=>{
 const daily_staffing_overrides=[...Array.from({length:501},(_,i)=>({company_id:'company-a',work_date:'2027-01-01',shift_code:'X'+String(i).padStart(4,'0'),required_count:99})),{company_id:'company-a',work_date:'2027-01-31',shift_code:'ND',required_count:0}];
 await cloudFixture(page,{daily_staffing_overrides});
 await page.evaluate(()=>getSoll=()=>99);
 const result=await page.evaluate(async()=>{const p=await SFScheduleExport.freshSnapshot('2027-01');return {totals:p.objectTotals,calls:cloudCalls.filter(x=>x==='daily_staffing_overrides').length,last:p.coverage.at(-1)}});
 expect(result.calls).toBe(2);expect(result.totals.requiredDuties).toBe(60);expect(result.totals.requiredHours).toBe(480);expect(result.last.required).toBe(0);expect(result.last.actual).toBe(1);expect(result.totals.openDuties).toBe(60);
});
