const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'../../'+p),'utf8');
async function fixture(page){
 await page.route('https://schichtfunk.de/__schedule-audit',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));
 await page.goto('https://schichtfunk.de/__schedule-audit');
 await page.setContent('<div id="view-schedule"><div class="page-head"><h1>Wochenplanung</h1><p></p></div><div class="stats"><div><b id="statShifts"></b><em></em></div><div><b id="statEmployees"></b><em></em></div><div><b id="statOpen"></b><em></em></div><div><b id="statCoverage"></b><em></em></div></div><span id="availableTxt"></span><div class="cal-toolbar"><div class="seg"><button>Woche</button><button>Monat</button></div><button id="prevWeek">Zurück</button><button id="nextWeek">Weiter</button><button id="todayBtn">Heute</button><span id="weekLabel"></span></div><div><div id="calendarGrid"></div><div id="sollList"></div></div></div>');
 await page.addScriptTag({content:`window.weekStart=new Date(2026,10,30);window.assignments=[];window.absences=[];window.TYPES=[{id:'FD',name:'Frühdienst',start:'06:00',end:'14:00'},{id:'SD',name:'Spätdienst',start:'14:00',end:'22:00'},{id:'ND',name:'Nachtdienst',start:'22:00',end:'06:00'}];window.employees=[{id:'A',first:'Fiktive',last:'Person',status:'active',shifts:['FD','SD','ND'],weeklyHours:40,monthlyHours:180,planningTeam:'A',qualifications:[]}];window.store={get:(k,d)=>d,set:()=>{}};window.iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');window.addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};window.typeById=id=>TYPES.find(t=>t.id===id)||window.archivedModel;window.getSoll=()=>4;window.assignmentsFor=(date,type)=>assignments.filter(a=>a.date===date&&a.type===type);window.employeeMonthlyTarget=e=>e.monthlyHours;window.plannedMonthlyHoursForEmployee=(id,date,sim=[],ignore)=>assignments.filter(a=>a.employeeId===id&&a.id!==ignore&&a.date.startsWith(date.slice(0,7))).reduce((n,a)=>n+8,0);window.saveAll=()=>{};window.renderCalendar=()=>{document.querySelector('#statOpen').textContent='84';document.querySelector('#weekLabel').textContent='Woche';};window.renderPlanEmployeePool=()=>{};window.renderOverview=()=>{};window.updateStats=()=>{};window.alerts=[];window.alert=x=>alerts.push(x);window.showSaveToast=()=>{};window.SFBackend={companyId:'fixture-company',ready:false};window.SFPlanningTeams={get:team=>({start:'2026-12-01',pattern:['FD','FD','SD','SD','FREI','ND','ND','FREI','FREI','FREI'],offset:'ABCDE'.indexOf(team)*2})};`});
 for(const p of ['assets/employee-rhythm-v1.js','assets/compliance-core-v2.js','assets/compliance-workflow-v2.js','assets/supabase-absence-planning-guard-v2.js'])await page.addScriptTag({content:read(p)});
}
test('manual assignment and edit enforce inherited team rhythm after the compliance modules load',async({page})=>{
 await fixture(page);await page.evaluate(()=>openAssign('ND','2026-12-01'));await expect(page.locator('[data-emp="A"]')).toBeDisabled();await expect(page.locator('#spAssignPeople')).toContainText('Team A');
 await page.evaluate(()=>{assignEmployeeByDrop('A','ND','2026-12-01');assignEmployeeByDrop('A','FD','2026-12-01')});expect(await page.evaluate(()=>assignments.map(a=>a.type))).toEqual(['FD']);
 await page.evaluate(()=>editAssignment(assignments[0].id));await page.locator('#spEditType').selectOption('SD');await expect(page.locator('#spEditCheck')).toContainText('Team A');await page.locator('#spSaveAssign').click();expect(await page.evaluate(()=>assignments[0].type)).toBe('FD');
});
test('month limits include the proposed shift and exclude the assignment being edited',async({page})=>{
 await fixture(page);const checks=await page.evaluate(()=>{employees[0].planningTeam='';employees[0].monthlyHours=8;assignments=[{id:'existing',employeeId:'A',type:'FD',date:'2026-12-01',start:'06:00',end:'14:00'}];return{newShift:SFCompliance.check(employees[0],'FD','2026-12-02','06:00','14:00'),edit:SFCompliance.check(employees[0],'FD','2026-12-01','06:00','14:00','existing')}});expect(checks.newShift.soft.join(' ')).toContain('Monats-SOLL');expect(checks.edit.soft.join(' ')).not.toContain('Monats-SOLL');
});
test('non-planable employees and invalid dates are rejected before changing the plan',async({page})=>{
 await fixture(page);const checks=await page.evaluate(()=>{employees[0].availabilityStatus='red';const red=SFCompliance.check(employees[0],'FD','2026-12-01','06:00','14:00');employees[0].availabilityStatus='green';return{red,invalidDate:SFCompliance.check(employees[0],'FD','2026-02-31','06:00','14:00'),invalidTime:SFCompliance.check(employees[0],'FD','2026-12-01','25:00','26:00')}});expect(checks.red.hard.length).toBeGreaterThan(0);expect(checks.invalidDate.hard.length).toBeGreaterThan(0);expect(checks.invalidTime.hard.length).toBeGreaterThan(0);
});
test('month KPI values, range absences and saved month refer to December',async({page})=>{
 await fixture(page);await page.evaluate(()=>absences=[{employeeId:'A',date:'2026-12-01',startDate:'2026-12-01',endDate:'2026-12-03',type:'Urlaub',status:'Genehmigt'}]);await page.addScriptTag({content:read('assets/schedule-month-view-v1.js')});await page.evaluate(()=>SchichtFunkCalendarView.setMonth('2026-12'));
 await expect(page.locator('#statOpen')).toHaveText('372');await expect(page.locator('#view-schedule h1')).toHaveText('Monatsplanung');await expect(page.locator('[data-month-date="2026-12-03"]')).toContainText('1 abwesend');
 expect(await page.evaluate(()=>sessionStorage.getItem('sf_schedule_month_cursor_v1'))).toBe('2026-12');
});
test('clicking a January day and returning to month opens January rather than stale December',async({page})=>{
 await fixture(page);await page.addScriptTag({content:read('assets/schedule-month-view-v1.js')});await page.evaluate(()=>SchichtFunkCalendarView.setMonth('2026-12'));await page.locator('[data-month-date="2027-01-04"]').click();await page.getByRole('button',{name:'Monat',exact:true}).click();await expect(page.locator('#weekLabel')).toHaveText('Januar 2027');
});
test('editing an archived existing model retains it without permitting a new assignment',async({page})=>{
 await fixture(page);await page.evaluate(()=>{employees[0].planningTeam='';employees[0].shifts.push('OLD');window.archivedModel={id:'OLD',start:'06:00',end:'14:00',active:false};assignments=[{id:'old',employeeId:'A',type:'OLD',date:'2026-12-01',start:'06:00',end:'14:00'}];editAssignment('old')});await expect(page.locator('#spEditType')).toHaveValue('OLD');expect(await page.evaluate(()=>SFCompliance.check(employees[0],'OLD','2026-12-03','06:00','14:00').hard.length)).toBeGreaterThan(0);
});

test('availability suggestions enforce rest and keep Team E placeholder eligible',async({page})=>{
 await fixture(page);const result=await page.evaluate(()=>{employees[0].planningTeam='';assignments=[{id:'night',employeeId:'A',type:'ND',date:'2026-12-01',start:'22:00',end:'06:00'}];const rest=isEligible(employees[0],'FD','2026-12-02');assignments=[];const placeholder={...employees[0],id:'placeholder-e-4',first:'Platzhalter',planningTeam:'E'};return{rest,placeholder:isEligible(placeholder,'FD','2026-12-03'),wrong:isEligible(placeholder,'ND','2026-12-03')}});expect(result).toEqual({rest:false,placeholder:true,wrong:false});
});
test('only effective absences block planning, including partial absences across midnight',async({page})=>{
 await fixture(page);const result=await page.evaluate(()=>{employees[0].planningTeam='';absences=[{employeeId:'A',date:'2026-12-02',startDate:'2026-12-02',endDate:'2026-12-02',fullDay:false,startTime:'01:00',endTime:'03:00',type:'Urlaub',status:'Beantragt'}];const pending=SFCompliance.check(employees[0],'ND','2026-12-01','22:00','06:00');absences[0].status='Genehmigt';return{pending,approved:SFCompliance.check(employees[0],'ND','2026-12-01','22:00','06:00')}});expect(result.pending.hard).toEqual([]);expect(result.approved.hard.join(' ')).toContain('Abwesenheit');
});
test('changing a shift model updates its times and monthly statistics survive a refresh',async({page})=>{
 await fixture(page);await page.evaluate(()=>{employees[0].planningTeam='';assignments=[{id:'shift',employeeId:'A',type:'FD',date:'2026-12-01',start:'06:00',end:'14:00'}];editAssignment('shift')});await page.locator('#spEditType').selectOption('ND');await expect(page.locator('#spEditStart')).toHaveValue('22:00');await expect(page.locator('#spEditEnd')).toHaveValue('06:00');await page.locator('#spSaveAssign').click();expect(await page.evaluate(()=>assignments[0].type)).toBe('ND');await page.addScriptTag({content:read('assets/schedule-month-view-v1.js')});await page.evaluate(()=>{SchichtFunkCalendarView.setMonth('2026-12');SFCompliance.refresh()});await expect(page.locator('#statOpen')).toHaveText('371');await expect(page.locator('#weekLabel')).toHaveText('Dezember 2026');
});
test('saved month is restored and weekly navigation selects the new month',async({page})=>{
 await fixture(page);await page.evaluate(()=>{sessionStorage.setItem('sf_schedule_period_v1','month');sessionStorage.setItem('sf_schedule_month_cursor_v1','2027-01')});await page.addScriptTag({content:read('assets/schedule-month-view-v1.js')});await expect(page.locator('#weekLabel')).toHaveText('Januar 2027');await page.evaluate(()=>{SchichtFunkCalendarView.setMonth('2026-12');SchichtFunkCalendarView.setMode('week');weekStart=new Date(2027,1,1);SchichtFunkCalendarView.setMode('month')});await expect(page.locator('#weekLabel')).toHaveText('Februar 2027');
});
