const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path');
const read=p=>fs.readFileSync(path.join(__dirname,'../../'+p),'utf8');
async function fixture(page){
 await page.route('https://schichtfunk.de/__publication-period-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body></body></html>'}));await page.goto('https://schichtfunk.de/__publication-period-fixture');
 await page.setContent('<meta name="viewport" content="width=device-width,initial-scale=1"><div id="view-schedule"><div class="cal-toolbar"><div class="seg"><button>Woche</button><button>Monat</button></div><button id="prevWeek">Zurück</button><button id="nextWeek">Weiter</button><button id="todayBtn">Heute</button><span id="weekLabel"></span></div><div><div id="calendarGrid"></div><div id="sollList"></div></div></div>');
 await page.addScriptTag({content:`window.weekStart=new Date(2026,8,28);window.assignments=['2026-09-28','2026-11-30','2026-12-01','2026-12-31','2027-01-01'].map((date,i)=>({id:i,date,type:'FD',employeeId:1,start:'06:00',end:'14:00'}));window.employees=[{id:1,first:'Fiktive',last:'Person'}];window.absences=[];window.TYPES=[{id:'FD'}];window.globalSoll={FD:0};window.getSoll=()=>0;window.renderCalendar=()=>{document.querySelector('#weekLabel').textContent='Woche';if(window.useWeekBoard){document.querySelector('#sfWeekBoardV2').classList.add('active');document.querySelector('#calendarGrid').style.display='none'}};window.calls=[];window.SFBackend={ready:true,companyId:'company-b',client:{rpc:async(name,args)=>{calls.push({name,args});return{data:{assignment_count:2}}}},hydrate:async()=>{assignments.filter(a=>a.date>='2026-12-01'&&a.date<='2026-12-31').forEach(a=>a.publishedAt='2026-10-01')}};window.SFCompliance={publications:{},iso:d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),fmt:d=>new Date(d+'T12:00:00').toLocaleDateString('de-DE'),weekKey:d=>d};`});
 await page.addScriptTag({content:read('assets/supabase-publish-v1.js')});await page.addScriptTag({content:read('assets/calendar-view-switch-v1.js')});await page.addScriptTag({content:read('assets/schedule-month-view-v1.js')});
 await page.evaluate(()=>SchichtFunkCalendarView.setMonth('2026-12'));
}
test('December navigation and publication use the displayed month and exact tenant boundaries',async({page})=>{
 await fixture(page);await expect(page.locator('#weekLabel')).toHaveText('Dezember 2026');await page.locator('#nextWeek').click();await expect(page.locator('#weekLabel')).toHaveText('Januar 2027');await page.locator('#prevWeek').click();await expect(page.locator('#weekLabel')).toHaveText('Dezember 2026');
 await page.evaluate(()=>{window.pendingPublication=spPublishCurrentWeek()});const dialog=page.getByRole('dialog');await expect(dialog).toContainText('Monat zur Veröffentlichung prüfen');await expect(dialog).toContainText('1.12.2026 bis 31.12.2026');await expect(dialog.locator('.sf-pub-stat').first().locator('b')).toHaveText('2');await dialog.screenshot({path:test.info().outputPath('december-publication.png')});await dialog.locator('.sf-pub-confirm').click();await page.evaluate(()=>pendingPublication);
 expect(await page.evaluate(()=>calls)).toEqual([{name:'publish_schedule_period',args:{p_company_id:'company-b',p_start_date:'2026-12-01',p_end_date:'2026-12-31'}}]);expect(await page.evaluate(()=>assignments.filter(a=>a.publishedAt).map(a=>a.date))).toEqual(['2026-12-01','2026-12-31']);
});
test('canceling a publication does not call the backend and returning to week view restores the grid',async({page})=>{
 await fixture(page);await page.evaluate(()=>{window.pendingPublication=spPublishCurrentWeek()});await page.getByRole('button',{name:'Zurück zur Planung',exact:true}).click();await page.evaluate(()=>pendingPublication);expect(await page.evaluate(()=>calls)).toEqual([]);await page.getByRole('button',{name:'Woche',exact:true}).click();await expect(page.locator('#calendarGrid')).toHaveCSS('display','block');expect(await page.evaluate(()=>SchichtFunkCalendarView.getPeriod())).toEqual({mode:'week',start:'2026-11-30',end:'2026-12-06'});
});

test('returning from month view preserves the selected compact week board',async({page})=>{
 await fixture(page);await page.evaluate(()=>{const board=document.createElement('div');board.id='sfWeekBoardV2';document.querySelector('#calendarGrid').before(board);window.useWeekBoard=true});await page.getByRole('button',{name:'Woche',exact:true}).click();await expect(page.locator('#sfWeekBoardV2')).toHaveClass('active');await expect(page.locator('#calendarGrid')).toHaveCSS('display','none');await page.getByRole('button',{name:'Monat',exact:true}).click();await expect(page.locator('#sfWeekBoardV2')).not.toHaveClass('active');await expect(page.locator('#weekLabel')).toHaveText('Dezember 2026');
});
