const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=f=>fs.readFileSync(require('node:path').join(__dirname,'..',f),'utf8');
function environment(){const events=[],B={ready:false,companyId:'company-a',user:{id:'owner'},role:'OWNER',accessRole:'OWNER',client:{rpc:async()=>({data:{company_id:B.companyId,name:'Company',timezone:'Europe/Berlin',sites:[],contacts:[],can_edit:true}})}};const w={SFBackend:B,addEventListener(){}};const c={window:w,document:{querySelectorAll:()=>[],querySelector:()=>null,getElementById:()=>null,dispatchEvent:e=>events.push(e),addEventListener(){}},structuredClone,Date,JSON,Intl,CustomEvent:function(type,options){this.type=type;this.detail=options?.detail},setTimeout,clearTimeout};vm.runInNewContext(read('assets/company-profile-v1.js'),c);B.ready=true;return {B,P:w.SFCompanyProfile,c,events}}
test('company reads are deduplicated and cached within the authenticated context',async()=>{const {B,P}=environment();let count=0;B.client.rpc=async()=>{count++;await new Promise(r=>setTimeout(r,5));return {data:{company_id:B.companyId,name:'Company',timezone:'Europe/Berlin',sites:[],contacts:[]}}};await Promise.all([P.load(),P.load()]);await P.load();assert.equal(count,1);await P.load({force:true});assert.equal(count,2)});
test('a company or user switch discards an in-flight response',async()=>{const {B,P}=environment();let finish;B.client.rpc=()=>new Promise(r=>finish=r);const pending=P.load();B.companyId='company-b';finish({data:{company_id:'company-a',name:'Old',timezone:'Europe/Berlin',sites:[],contacts:[]}});await assert.rejects(pending,/geändert/);assert.equal(P.current(),null)});
test('the returned profile must belong to the requested company',async()=>{const {B,P}=environment();B.client.rpc=async()=>({data:{company_id:'foreign',name:'Leak'}});await assert.rejects(P.load(),/Ungültige Unternehmensdaten/);assert.equal(P.current(),null)});
test('time-only and employee contexts cannot load manager profile data',async()=>{for(const role of ['EMPLOYEE','TIME_TRACKING']){const {B,P}=environment();B.role=role;let calls=0;B.client.rpc=async()=>{calls++;return {}};await assert.rejects(P.load());assert.equal(calls,0)}});
test('archived sites remain selectable only for their current binding',async()=>{const {B,P}=environment();B.client.rpc=async()=>({data:{company_id:B.companyId,name:'Company',timezone:'UTC',contacts:[],sites:[{id:'active',code:'A',name:'East',is_active:true},{id:'archived',code:'B',name:'West',is_active:false}]}});await P.load();assert.ok(P.siteOptions().includes('East'));assert.ok(!P.siteOptions().includes('West'));assert.ok(P.siteOptions('archived').includes('archiviert'))});
test('structured location exports isolate shifts and preserve full contractual targets',()=>{const core=require('../assets/schedule-export-core-v1.js');const source={month:'2026-10',company:'QA',sites:[{id:'east',name:'East'},{id:'west',name:'West'}],employees:[{id:'1',first:'QA',last:'Person',weeklyHours:40,status:'active'}],types:[{id:'E',start:'06:00',end:'14:00',siteId:'east'},{id:'W',start:'14:00',end:'22:00',siteId:'west'}],assignments:[{employeeId:'1',date:'2026-10-01',type:'E'},{employeeId:'1',date:'2026-10-02',type:'W'}],getSoll:()=>1};const full=core.buildPlan(source),p=core.selectPDFPlan(full,'site:east');assert.equal(full.hours,16);assert.equal(p.hours,8);assert.equal(p.rows[0].targetHours,173.92);assert.equal(p.rows[0].difference,-165.92);assert.equal(p.details.length,1);assert.equal(p.rows[0].cells[1].pdf,'-');assert.deepEqual(p.types.map(t=>t.id),['E']);assert.equal(p.objectTotals.requiredDuties,31);assert.match(p.scopeNote,/kein anteiliges/);assert.equal(full.details.length,2);assert.throws(()=>core.selectPDFPlan(full,'site:foreign'),/nicht verfügbar/)});
test('logo placement preserves both wide and tall aspect ratios',()=>{const {P}=environment();for(const [width,height,expected]of [[200,100,[0,10,40,20]],[100,200,[10,0,20,40]]]){let actual;const d={getImageProperties(){return {width,height}},setFillColor(){},roundedRect(){},addImage(...a){actual=a.slice(2,6)}};P.drawLogo(d,'png',0,0,40,40);assert.deepEqual(actual,expected)}});
