-- Run as an administrator. All fixtures and notifications are rolled back.
BEGIN;
DO $$
DECLARE manager uuid; users uuid[]; co uuid:=gen_random_uuid(); foreign_co uuid:=gen_random_uuid();
 e1 uuid:=gen_random_uuid(); e2 uuid:=gen_random_uuid(); e3 uuid:=gen_random_uuid();
 offer uuid; claim1 uuid; claim2 uuid; result jsonb; rows jsonb; blocked boolean; n integer;
BEGIN
 SELECT user_id INTO manager FROM public.company_members WHERE status='ACTIVE' AND role='OWNER' LIMIT 1;
 users:=ARRAY[gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
 INSERT INTO auth.users(id,aud,role,email,created_at,updated_at) SELECT u,'authenticated','authenticated','market-test-'||u::text||'@example.invalid',now(),now() FROM unnest(users) u;
 ASSERT manager IS NOT NULL AND cardinality(users)>=3,'Fixture accounts unavailable';
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 INSERT INTO public.companies(id,name,timezone,created_by) VALUES(co,'Marktplatz Integrationstest','Europe/Berlin',manager),(foreign_co,'Fremder Testmandant','Europe/Berlin',manager);
 INSERT INTO public.company_members(company_id,user_id,role,status) VALUES(co,manager,'OWNER','ACTIVE') ON CONFLICT(company_id,user_id) DO UPDATE SET role='OWNER',status='ACTIVE';
 INSERT INTO public.shift_templates(company_id,code,name,default_start,default_end) VALUES(co,'TESTFD','Test Frühdienst','06:00','14:00'),(co,'TESTND','Test Nachtdienst','22:00','06:00');
 INSERT INTO public.global_staffing_requirements(company_id,shift_code,required_count) VALUES(co,'TESTFD',2),(co,'TESTND',1);
 INSERT INTO public.daily_staffing_overrides(company_id,work_date,shift_code,required_count) VALUES(co,'2026-12-01','TESTFD',1);
 INSERT INTO public.employees(id,company_id,first_name,last_name,personnel_no,auth_user_id,status,weekly_hours,shift_permissions,qualifications) VALUES
 (e1,co,'Test','Eins','MARKET-TEST-1',users[1],'active',40,ARRAY['TESTFD','TESTND'],ARRAY['__sp:rhythmMode=required','__sp:rhythmStart=2026-12-01','__sp:rhythmPattern=FREI']),
 (e2,co,'Test','Zwei','MARKET-TEST-2',users[2],'active',40,ARRAY['TESTFD','TESTND'],ARRAY[]::text[]),
 (e3,co,'Test','Drei','MARKET-TEST-3',users[3],'active',40,ARRAY['TESTND'],ARRAY[]::text[]);
 result:=public.manager_publish_open_shifts(co,'[{"date":"2026-12-01","type":"TESTFD","count":50}]');
 ASSERT (result->>'published_positions')::integer=1,'Daily staffing override must cap publication';
 SELECT id INTO offer FROM public.open_shift_market_offers WHERE company_id=co;
 PERFORM public.manager_publish_open_shifts(co,'[{"date":"2026-12-01","type":"TESTFD","count":1}]');
 ASSERT (SELECT count(*) FROM public.open_shift_market_offers WHERE company_id=co)=1,'Republishing must not duplicate offers';
 PERFORM set_config('request.jwt.claim.sub',users[3]::text,true);
 blocked:=false;BEGIN PERFORM public.employee_claim_open_shift(offer);EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'Missing shift permission must block claim';
 PERFORM set_config('request.jwt.claim.sub',users[1]::text,true);
 blocked:=false;BEGIN PERFORM public.manager_publish_open_shifts(co,'[{"date":"2026-12-02","type":"TESTFD","count":1}]');EXCEPTION WHEN insufficient_privilege THEN blocked:=true;END;
 ASSERT blocked,'Employee cannot publish';
 result:=public.employee_claim_open_shift(offer,'Freiwillige Übernahme');claim1:=(result->>'id')::uuid;
 ASSERT result->>'status'='PENDING_MANAGER','Claim requires planner approval';
 ASSERT NOT EXISTS(SELECT 1 FROM public.shift_assignments WHERE company_id=co),'Claim must not write schedule';
 blocked:=false;BEGIN PERFORM public.employee_claim_open_shift(offer);EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'Duplicate claim must be rejected';
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 result:=public.employee_claim_open_shift(offer);claim2:=(result->>'id')::uuid;
 rows:=public.employee_list_open_shift_market();
 ASSERT NOT EXISTS(SELECT 1 FROM jsonb_array_elements(rows) x WHERE x->>'id'=claim1::text),'Employee must not see colleague claim';
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 blocked:=false;BEGIN PERFORM public.manager_review_open_shift_claim(claim1,'APPROVE');EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'Rhythm deviation requires explicit approval';
 ASSERT private.sf_open_market_extra_warning(offer,e1) LIKE '%freien Tag%','Additional shift on a free rhythm day must be marked';
 result:=public.manager_review_open_shift_claim(claim1,'APPROVE','Rhythmusabweichung geprüft',true);
 ASSERT result->>'status'='APPLIED','Planner approval must succeed';
 ASSERT (SELECT count(*) FROM public.shift_assignments WHERE company_id=co AND employee_id=e1 AND status='PUBLISHED')=1,'Approval must create one published assignment';
 result:=public.manager_review_open_shift_claim(claim2,'APPROVE');
 ASSERT result->>'status'='SUPERSEDED','Last place cannot be allocated twice';
 PERFORM public.manager_review_open_shift_claim(claim1,'APPROVE','',true);
 ASSERT (SELECT count(*) FROM public.shift_assignments WHERE company_id=co)=1,'Repeated approval must be idempotent';
 rows:=public.manager_list_open_shift_market(co);
 ASSERT NOT EXISTS(SELECT 1 FROM jsonb_array_elements(rows) x WHERE x->>'status'='MARKET_OPEN'),'Filled offers must disappear';
 blocked:=false;BEGIN PERFORM public.manager_list_open_shift_market(foreign_co);EXCEPTION WHEN insufficient_privilege THEN blocked:=true;END;
 ASSERT blocked,'Cross-company access must fail';
 PERFORM set_config('request.jwt.claim.sub','',true);
 blocked:=false;BEGIN PERFORM public.employee_list_open_shift_market();EXCEPTION WHEN insufficient_privilege THEN blocked:=true;END;
 ASSERT blocked,'Unauthenticated access must fail';
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 PERFORM public.manager_publish_open_shifts(co,'[{"date":"2026-12-03","type":"TESTND","count":1}]');
 SELECT id INTO offer FROM public.open_shift_market_offers WHERE company_id=co AND shift_code='TESTND' AND work_date='2026-12-03';
 ASSERT (SELECT ends_at-starts_at FROM public.open_shift_market_offers WHERE id=offer)=interval '8 hours','Overnight interval must be correct';
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 result:=public.employee_claim_open_shift(offer);claim2:=(result->>'id')::uuid;
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 result:=public.manager_review_open_shift_claim(claim2,'REJECT');
 ASSERT result->>'status'='REJECTED_MANAGER','Rejection must be recorded';
 ASSERT (SELECT status FROM public.open_shift_market_offers WHERE id=offer)='MARKET_OPEN','Rejected claim leaves place open';
 -- A manual assignment changes capacity and closes the offer at the next listing.
 INSERT INTO public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,created_by) VALUES(co,e3,'TESTND','2026-12-03T22:00:00+01:00','2026-12-04T06:00:00+01:00',manager);
 rows:=public.manager_list_open_shift_market(co);
 ASSERT NOT EXISTS(SELECT 1 FROM jsonb_array_elements(rows) x WHERE x->>'id'=offer::text AND x->>'status'='MARKET_OPEN'),'Manual fill must close offer';
 PERFORM public.manager_publish_open_shifts(co,'[{"date":"2026-12-05","type":"TESTFD","count":2},{"date":"2026-12-06","type":"TESTFD","count":2}]');
 SELECT id INTO offer FROM public.open_shift_market_offers WHERE company_id=co AND work_date='2026-12-05' AND shift_code='TESTFD';
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 result:=public.employee_claim_open_shift(offer);claim2:=(result->>'id')::uuid;
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 UPDATE public.employees SET weekly_hours=4 WHERE id=e2;
 blocked:=false;BEGIN PERFORM public.manager_review_open_shift_claim(claim2,'APPROVE');EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'New weekly overtime requires explicit planner confirmation';
 ASSERT (SELECT status FROM public.open_shift_market_claims WHERE id=claim2)='PENDING_MANAGER','Missing confirmation must retain pending request';
 ASSERT private.sf_open_market_extra_warning(offer,e2) LIKE '%Wochen-Soll%','Weekly target excess is a warning';
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 PERFORM public.employee_cancel_open_shift_claim(claim2);
 UPDATE public.employees SET weekly_hours=40,qualifications=ARRAY['__sp:monthlyHours=4'] WHERE id=e2;
 rows:=public.employee_list_open_shift_market();
 ASSERT EXISTS(SELECT 1 FROM jsonb_array_elements(rows) x WHERE x->>'id'=offer::text AND (x->>'can_take')::boolean AND x->>'additional_warning' LIKE '%Monats-Soll%'),'Monthly overtime must remain requestable with warning';
 result:=public.employee_claim_open_shift(offer,'Freiwilliger Zusatzdienst');claim2:=(result->>'id')::uuid;
 ASSERT result->>'status'='PENDING_MANAGER','Monthly overtime claim must await planner';
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 blocked:=false;BEGIN PERFORM public.manager_review_open_shift_claim(claim2,'APPROVE');EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'Monthly overtime approval needs explicit confirmation';
 BEGIN
  result:=public.manager_review_open_shift_claim(claim2,'APPROVE','Mehrstunden ausdrücklich freigegeben',true);
  ASSERT result->>'status'='APPLIED','Confirmed monthly overtime must be assigned';
  ASSERT (SELECT note FROM public.shift_assignments WHERE id=(result->>'assignment_id')::uuid) LIKE '%Zusatzdienst%','Additional assignment must be identified';
  RAISE EXCEPTION USING ERRCODE='Z0001',MESSAGE='Rollback confirmed additional-shift fixture';
 EXCEPTION WHEN SQLSTATE 'Z0001' THEN NULL; END;
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 PERFORM public.employee_cancel_open_shift_claim(claim2);
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 UPDATE public.employees SET qualifications=ARRAY[]::text[] WHERE id=e2;
 INSERT INTO public.absences(company_id,employee_id,start_date,end_date,absence_type,status) VALUES(co,e2,'2026-12-05','2026-12-05','Urlaub','Genehmigt');
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 blocked:=false;BEGIN PERFORM public.employee_claim_open_shift(offer);EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'Approved absence must prevent claim';
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 DELETE FROM public.absences WHERE company_id=co AND employee_id=e2;
 INSERT INTO public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,created_by) VALUES(co,e2,'TESTND','2026-12-04T22:00:00+01:00','2026-12-05T06:00:00+01:00',manager);
 PERFORM set_config('request.jwt.claim.sub',users[2]::text,true);
 blocked:=false;BEGIN PERFORM public.employee_claim_open_shift(offer);EXCEPTION WHEN OTHERS THEN blocked:=true;END;
 ASSERT blocked,'Missing rest period must prevent claim';
 SELECT id INTO offer FROM public.open_shift_market_offers WHERE company_id=co AND work_date='2026-12-06' AND shift_code='TESTFD';
 result:=public.employee_claim_open_shift(offer);claim2:=(result->>'id')::uuid;
 result:=public.employee_cancel_open_shift_claim(claim2);
 ASSERT result->>'status'='CANCELLED','Employee can withdraw pending claim';
 PERFORM set_config('request.jwt.claim.sub',manager::text,true);
 PERFORM public.manager_cancel_open_shift_offer(offer);
 ASSERT (SELECT status FROM public.open_shift_market_offers WHERE id=offer)='CANCELLED','Planner can withdraw published offer';
 INSERT INTO public.company_members(company_id,user_id,role,status) VALUES(co,users[3],'TIME_TRACKING','ACTIVE');
 PERFORM set_config('request.jwt.claim.sub',users[3]::text,true);
 blocked:=false;BEGIN PERFORM public.employee_list_open_shift_market();EXCEPTION WHEN insufficient_privilege THEN blocked:=true;END;
 ASSERT blocked,'Time-only account cannot use marketplace';
 ASSERT NOT has_function_privilege('anon','public.manager_publish_open_shifts(uuid,jsonb,text)','EXECUTE'),'Anonymous publication denied';
 ASSERT NOT has_table_privilege('authenticated','public.open_shift_market_claims','INSERT'),'Direct employee claim writes denied';
 PERFORM set_config('open_market.test_result','All marketplace integration assertions passed',true);
END $$;
SELECT current_setting('open_market.test_result') AS result;
ROLLBACK;

