const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../assets/reports-workspace-core-v1.js');
function fixture(){return{company_id:'qa-a',company_name:'QA Company',timezone:'Europe/Berlin',today:'2026-10-10',as_of:'2026-10-10T12:00:00Z',from:'2026-10-01',to:'2026-10-31',can_time:true,settings:{target_method:'PERSONAL_MONTHLY',target_method_from:'2026-01-01'},closed_month:false,
 employees:[{id:'a',first:'Anna',last:'Zweig',personnel_no:'100',team:'A',monthly_hours:'180',status:'active',target_minutes:10800,elapsed_target_minutes:3484,credit_minutes:0,elapsed_credit_minutes:0,confirmed_minutes:0,shifts:['FD','ND']},{id:'b',first:'Ben',last:'Adler',personnel_no:'101',team:'B',monthly_hours:'162',status:'active',target_minutes:9720,elapsed_target_minutes:3135,credit_minutes:0,elapsed_credit_minutes:0,confirmed_minutes:0,shifts:['FD']}],
 models:[{code:'FD',name:'Frühdienst',active:true,default_start:'06:00',default_end:'14:00',optional_weekdays:[1,2,3,4,5,6,7],site_id:'east',planning_mode:'required'}],sites:[{id:'east',code:'E',name:'QA East',is_active:true}],global:{FD:1},daily:[],rules:{},assignments:[],times:[],qr:[],absences:[]}}
function assignment(id,employee,date='2026-10-01',shift='FD',start=date+'T04:00:00Z',end=date+'T12:00:00Z'){return{id,employee_id:employee,date,shift,start,end,status:'PUBLISHED',site_id:'east',break_minutes:0}}
test('periods, leap years and bounded month portions',()=>{assert.deepEqual(C.period('week','2026-10-10'),{from:'2026-10-05',to:'2026-10-11'});assert.deepEqual(C.period('quarter','2026-10-10'),{from:'2026-10-01',to:'2026-12-31'});assert.equal(C.days('2024-01-01','2024-12-31').length,366);assert.equal(C.chunks('2024-01-01','2024-12-31').length,12);assert.deepEqual(C.previous('month','2026-10-01','2026-10-31'),{from:'2026-09-01',to:'2026-09-30'});assert.throws(()=>C.days('2026-10-10','2026-10-01'));assert.throws(()=>C.days('2025-01-01','2026-12-31'));assert.equal(C.valid('2026-02-30'),false)});
test('overstaffing on one day cannot fill another; duplicate staff count once',()=>{const d=fixture();d.to='2026-10-02';d.assignments=[assignment('1','a'),assignment('2','b'),assignment('3','a')];const r=C.analyze(d);assert.equal(r.summary.coverage,.5);assert.equal(r.summary.missing,1);assert.equal(r.calendar[0].filled,1);assert.equal(r.cells[0].filled,2);assert.equal(r.cells[1].missing,1)});
test('zero demand is distinct from full coverage; optional wishes remain separate',()=>{const d=fixture();d.global.FD=0;d.models[0].planning_mode='optional';d.models[0].optional_staffing=2;const r=C.analyze(d);assert.equal(r.summary.coverage,null);assert.equal(r.summary.missing,0);assert.equal(r.cells[0].optionalMissing,2);assert.equal(r.alerts.filter(a=>a.kind==='coverage').length,0)});
test('shared TL staffing counts once across sites and requires the complete interval',()=>{const d=fixture();d.to=d.from;d.models=['TL-E','TL-W'].map((code,i)=>({code,active:true,default_start:'20:00',default_end:'06:00',coverage_group:'TL E/W',coverage_required:1,optional_weekdays:[1,2,3,4,5,6,7],site_id:i?'west':'east'}));d.assignments=[assignment('1','a',d.from,'TL-W',d.from+'T18:00Z','2026-10-02T04:00Z')];let r=C.analyze(d);assert.equal(r.cells.length,1);assert.equal(r.summary.required,1);assert.equal(r.summary.coverage,1);r=C.analyze(d,{site:'east'});assert.equal(r.summary.coverage,1,'shared west duty covers east demand');d.assignments[0].end='2026-10-02T02:00Z';assert.equal(C.analyze(d).summary.missing,1)});
test('conditional staffing sees previous-day source shifts',()=>{const d=fixture();d.to=d.from;d.models=[{code:'OT1',active:true,default_start:'06:00',default_end:'16:00',optional_weekdays:[1,2,3,4,5]}];d.global={OT1:1};d.rules={enabled:true,conditionalStaffing:[{shift:'OT1',sourceShift:'O3',sourceDayOffset:-1,coverageStart:'06:00',coverageEnd:'08:00',minimum:3,fallbackCount:1}]};d.assignments=[1,2,3].map(i=>assignment(String(i),String(i),'2026-09-30','O3','2026-09-30T20:00Z','2026-10-01T06:00Z'));assert.equal(C.analyze(d).summary.required,0);d.assignments.pop();assert.equal(C.analyze(d).summary.required,1)});
test('QR and reported intervals are combined once, clipped to local calendar boundaries',()=>{const d=fixture();d.to='2026-10-01';d.employees[0].confirmed_minutes=420;d.times=[{id:'t1',employee_id:'a',start:'2026-09-30T22:00Z',end:'2026-10-01T06:00Z',status:'confirmed',break_minutes:60},{id:'t2',employee_id:'a',start:'2026-10-01T05:00Z',end:'2026-10-01T08:00Z',status:'recorded'}];d.qr=[{id:'q1',employee_id:'a',start:'2026-09-30T23:00Z',end:'2026-10-01T04:00Z',status:'qr_booked',shift:null,break_minutes:0},{id:'running',employee_id:'a',start:'2026-10-01T09:00Z',end:null,status:'qr_running'}];const r=C.analyze(d);assert.equal(r.summary.captured,600);assert.equal(r.summary.confirmed,420);assert.equal(r.summary.review,1);assert.equal(r.alerts.filter(a=>a.kind==='running').length,1);assert.equal(r.employeeRows.find(e=>e.id==='a').elapsedBalance,420-3484)});
test('DST calendar date boundaries use the company timezone',()=>{const d=fixture();d.from=d.to='2026-10-25';d.as_of='2026-10-26T12:00:00Z';d.today='2026-10-26';d.qr=[{id:'q',employee_id:'a',start:'2026-10-24T20:00Z',end:'2026-10-26T03:00Z',status:'qr_booked',shift:null}];assert.equal(C.analyze(d).summary.captured,25*60)});
test('team filters use planning A–E; site/shift scopes cannot fabricate contract deficits',()=>{const d=fixture();d.assignments=[assignment('1','a'),assignment('2','b')];const r=C.analyze(d,{team:'A',site:'east'});assert.equal(r.employeeRows.length,1);assert.equal(r.employeeRows[0].id,'a');assert.equal(r.employeeRows[0].remaining,null);assert.equal(r.summary.underTarget,null);assert.equal(r.summary.required,31,'company demand remains independent of team selection');assert.equal(r.employeeRows[0].target,10800);assert.deepEqual(C.analyze(d).employeeRows.map(e=>e.id),['b','a'])});
test('employment and approved absences affect availability, partial absence conflict is time aware',()=>{const d=fixture();d.employees[0].start_date='2026-10-02';d.employees[0].contract_end='2026-10-04';d.absences=[{id:'ab',employee_id:'a',from:'2026-10-03',to:'2026-10-03',full_day:true,type:'Urlaub',status:'APPROVED'},{id:'partial',employee_id:'b',from:'2026-10-01',to:'2026-10-01',full_day:false,start_time:'15:00',end_time:'16:00',type:'Sperrzeit',status:'Erfasst'}];d.assignments=[assignment('1','b')];const r=C.analyze(d);assert.equal(r.employeeRows.find(e=>e.id==='a').availableDays,2);assert.equal(r.summary.absenceConflicts,0);d.absences[1].start_time='10:00';assert.equal(C.analyze(d).summary.absenceConflicts,1)});
test('employees without time rights receive no actuals or time alerts',()=>{const d=fixture();d.can_time=false;d.times=[];d.qr=[];d.assignments=[assignment('1','a')];const r=C.analyze(d);assert.equal(r.summary.captured,null);assert.equal(r.employeeRows[0].confirmed,null);assert.equal(r.alerts.some(a=>a.kind==='missingTime'),false)});
test('monthly merging preserves complete targets and deduplicates boundary assignments',()=>{const a=fixture(),b=fixture();a.from='2026-10-30';a.to='2026-10-31';b.from='2026-11-01';b.to='2026-11-02';a.assignments=[assignment('same','a','2026-10-31')];b.assignments=[...a.assignments];const m=C.merge([a,b]);assert.equal(m.employees[0].target_minutes,21600);assert.equal(m.assignments.length,1);assert.equal(m.from,a.from);assert.equal(m.to,b.to);assert.throws(()=>C.merge([a,{...b,company_id:'other'}]))});
test('backend API guards tenant, membership, duration, and time permissions before data access',()=>{const sql=fs.readFileSync(path.join(__dirname,'../supabase/migrations/20261010154921_reports_workspace.sql'),'utf8');assert.match(sql,/auth\.uid\(\) is null or not private\.sf_is_manager/);assert.match(sql,/can_time:=private\.sf_can_manage_time/);assert.match(sql,/if can_time then/);assert.match(sql,/security invoker set search_path=''/);assert.match(sql,/from public,anon/);assert.match(sql,/p_end_date-p_start_date>30/);assert.match(sql,/sf_confirmed_work_minutes/)});
module.exports={fixture,assignment};
