const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../assets/staffing-simulator-core-v1.js'),S=require('../assets/solid-planning-core-v1.js'),{fixture,variant}=require('./fixtures/staffing-simulator-data.cjs');
const fast={iterations:1};
test('isolated scenario preserves source and enforces recovery/month/week boundaries',async()=>{const data=fixture(),original=JSON.stringify(data),r=await C.run(data,variant(),fast);assert.equal(JSON.stringify(data),original);assert.ok(r.open>0);assert.ok(r.preview.length>0);for(const e of data.employees){assert.deepEqual(S.errors(e,r.preview,data.rules),[]);for(const month of ['2027-01','2027-02','2027-03'])assert.ok(r.preview.filter(a=>a.employeeId===e.id&&a.date.startsWith(month)).length<=23)}assert.equal(r.cost,54000);assert.equal(r.byMonth.length,3)});
test('additional staff have unique hypothetical IDs, no personal authorizations, and separate cost',async()=>{const d=fixture(),r=await C.run(d,{...variant(),hires:2,templateId:'e0',hireHours:144,hireWeekly:32},fast);assert.equal(r.people,6);assert.equal(r.cost,54000+2*144*3*26);assert.equal(r.rows.filter(x=>x.hypothetical).length,2);assert.ok(r.preview.some(a=>a.employeeId.startsWith('simulation-hire-')));assert.ok(C.staff(d,{...variant(),hires:1,templateId:'e0',hireHours:180,hireWeekly:40}).at(-1).personnelNo==='')});
test('missing costs remain unknown instead of zero',async()=>{const d=fixture();d.to='2027-01-31';const r=await C.run(d,{...variant(),hourCost:''},fast);assert.equal(r.cost,null);const z=await C.run(d,{...variant(),hourCost:0},fast);assert.equal(z.cost,0)});
test('outages, approved partial absence crossing midnight and contract dates block actual overlap',async()=>{const d=fixture();d.to='2027-01-31';d.employees=d.employees.slice(0,1);d.absences=[{employeeId:'e0',from:'2027-01-03',to:'2027-01-03',fullDay:false,startTime:'23:00',endTime:'07:00'}];d.employees[0].startDate='2027-01-02';const r=await C.run(d,{...variant(),outageId:'e0',outageFrom:'2027-01-10',outageTo:'2027-01-20'},fast);assert.ok(r.preview.every(a=>a.date>='2027-01-02'));assert.ok(r.preview.every(a=>!(a.startMs<S.instant('2027-01-21','00:00',d.timezone)&&a.endMs>S.instant('2027-01-10','00:00',d.timezone))));assert.ok(!r.preview.some(a=>a.date==='2027-01-03'&&a.type==='ND'||a.date==='2027-01-04'&&a.type==='FD'));});
test('shared leadership coverage counted once and insufficient interval does not cover',()=>{const d=fixture();d.models=[...d.models.map(t=>({...t,coverage_group:'TL',coverage_required:1,default_start:'20:00',default_end:'06:00'}))];const cells=C.cells(d,variant(),['2027-01-01'],[]);assert.equal(cells.length,1);assert.equal(cells[0].required,1);const hired=S.duty({employeeId:'x',date:'2027-01-01',type:'FD',start:'22:00',end:'06:00'},d.rules);assert.equal(C.cells(d,variant(),['2027-01-01'],[hired])[0].missing,1)});
test('binding rhythm, planning team, exclusive personnel and holiday rules stay binding',()=>{const d=fixture(),e=d.employees[0],t=d.models[0];e.rhythms={'2027-01-01':{mode:'required',expected:'FREI'}};assert.match(C.eligibility(e,t,'2027-01-01',d,[]),/Rhythmus/);e.rhythms={};t.requires_planning_team=true;assert.match(C.eligibility(e,t,'2027-01-01',d,[]),/Planungsteam/);t.requires_planning_team=false;t.allowed_personnel_nos=['999'];assert.match(C.eligibility(e,t,'2027-01-01',d,[]),/Schichtbindung/);t.allowed_personnel_nos=null;t.code='OT';e.shifts=['OT'];d.rules.otHolidayStatesBySite={Leipzig:'SN'};e.qualifications.push('__sp:team=Leipzig');assert.match(C.eligibility(e,t,'2027-01-04',d,[]),/OT-Tag/);assert.equal(C.eligibility(e,t,'2027-01-01',d,[]),'')});
test('contract target and budget are prorated by calendar days at entry and exit',()=>{assert.equal(C.contractTarget({monthlyHours:180,startDate:'2027-01-16',contractEnd:'2027-01-31'},'2027-01'),180*16/31);assert.equal(C.contractTarget({monthlyHours:180,contractEnd:'2026-12-31'},'2027-01'),0)});
test('invalid employee references, fractional hires and costs fail closed',()=>{const d=fixture();assert.throws(()=>C.validate(d,{...variant(),hires:1,templateId:'foreign'}),/Referenzprofil/);assert.throws(()=>C.validate(d,{...variant(),hires:1.5}),/ganzzahlig/);assert.throws(()=>C.validate(d,{...variant(),hourCost:-1}),/Arbeitgeberkosten/);assert.throws(()=>C.validate(d,{...variant(),outageId:'e0',outageFrom:'2027-02-30',outageTo:'2027-03-01'}),/Ausfall/)});
test('DST actual duration and prior-month night shifts constrain the new month',async()=>{const d=fixture();d.from='2027-03-01';d.to='2027-03-31';d.employees=d.employees.slice(0,1);const b=S.duty({employeeId:'e0',date:'2027-02-28',type:'ND',start:'22:00',end:'06:00'},d.rules);d.boundary=[S.duty({...b,date:"2027-02-26",startMs:undefined,endMs:undefined},d.rules),S.duty({...b,date:"2027-02-27",startMs:undefined,endMs:undefined},d.rules),b];d.boundary.forEach(a=>delete a.day);const r=await C.run(d,variant(),fast);assert.ok(!r.preview.some(a=>a.date>='2027-03-01'&&a.date<='2027-03-04'));assert.deepEqual(S.errors(d.employees[0],[...d.boundary,...r.preview],d.rules),[]);assert.equal(S.duty({date:'2027-03-27',type:'ND',start:'22:00',end:'06:00'},d.rules).hours,7)});
test('additional conditional demand survives when source coverage removes the fallback',async()=>{const d=fixture();d.to='2027-01-07';d.models=[{...d.models[0],code:'O1',default_start:'18:00',default_end:'04:00'},{...d.models[0],code:'OT3',default_start:'18:00',default_end:'04:00'}];d.employees.forEach(e=>e.shifts=['O1','OT3']);d.rules.conditionalStaffing=[{shift:'OT3',sourceShift:'O1',sourceDayOffset:0,coverageStart:'18:00',coverageEnd:'23:00',minimum:1,fallbackCount:1}];d.global={O1:1,OT3:1};const r=await C.run(d,{...variant(),extraShift:'OT3',extraCount:1},fast);assert.ok(r.preview.filter(a=>a.type==='OT3').length>0);assert.equal(C.cells(d,{...variant(),extraShift:'OT3',extraCount:1},['2027-01-04'],[S.duty({employeeId:'e0',date:'2027-01-04',type:'O1',start:'18:00',end:'04:00'},d.rules)])[1].required,1)});

test('weekday public holidays create OT demand and shared critical minima survive zero daily override',()=>{const d=fixture();d.models=[{...d.models[0],code:'OT',optional_weekdays:[6,7]}];d.global={OT:2};d.rules.otHolidayStatesBySite={Leipzig:'SN'};assert.equal(C.cells(d,variant(),['2027-01-01'],[])[0].required,2);assert.deepEqual(C.cells(d,variant(),['2027-01-01'],[])[0].alternatives,['OT']);assert.equal(C.cells(d,variant(),['2027-01-04'],[])[0].required,0);d.models[0]={...d.models[0],code:'TL',coverage_group:'Leitung',coverage_required:1,optional_weekdays:[1,2,3,4,5,6,7]};d.daily=[{date:'2027-01-04',shift:'TL',required:0}];d.rules.criticalCoverageGroups=['Leitung'];assert.equal(C.cells(d,variant(),['2027-01-04'],[])[0].required,1)});
