from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
css=r'''
/* ===== ShiftPilot Landingpage ===== */
#landingPage{min-height:100vh;background:radial-gradient(circle at 78% 18%,rgba(23,200,224,.18),transparent 27%),linear-gradient(180deg,#02070d 0%,#071522 64%,#f5f8fb 64%,#f5f8fb 100%);color:#fff}
.landing-nav{height:96px;display:flex;align-items:center;gap:36px;padding:12px 4vw;border-bottom:1px solid rgba(255,255,255,.08);background:rgba(2,7,13,.88);backdrop-filter:blur(18px);position:sticky;top:0;z-index:30}.landing-logo{width:330px;max-width:34vw;height:78px;object-fit:contain;object-position:left center}.landing-links{margin-left:auto;display:flex;align-items:center;gap:28px}.landing-links a{color:#dce9f6;text-decoration:none;font-weight:650;font-size:14px}.landing-links a:hover{color:#36e2d0}.landing-actions{display:flex;gap:10px}.landing-btn{border-radius:10px;padding:12px 20px;font-weight:800;border:1px solid #2b4560;background:#0c1724;color:#eef7ff}.landing-btn.primary{background:linear-gradient(135deg,#00d8d2,#278cff);border:0;color:white;box-shadow:0 10px 30px rgba(0,201,220,.22)}
.landing-hero{max-width:1500px;margin:0 auto;display:grid;grid-template-columns:.78fr 1.22fr;gap:54px;align-items:center;padding:46px 4vw 54px}.hero-kicker{display:inline-flex;padding:8px 14px;border:1px solid rgba(49,222,211,.35);background:rgba(20,209,196,.09);color:#3de8da;border-radius:99px;font-size:12px;font-weight:900;letter-spacing:.08em}.hero-copy h1{font-size:clamp(46px,5vw,78px);line-height:1.03;margin:22px 0 20px;letter-spacing:-.045em}.hero-copy h1 span{background:linear-gradient(90deg,#19e4dc,#1d9ef6);-webkit-background-clip:text;background-clip:text;color:transparent}.hero-copy p{font-size:18px;line-height:1.7;color:#b8c9da;max-width:640px}.hero-buttons{display:flex;gap:14px;margin:28px 0}.hero-points{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:30px}.hero-point{display:flex;align-items:flex-start;gap:11px;color:#d8e5f1;font-size:13px}.hero-point i{font-style:normal;width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#0b2a37;color:#35ded2;border:1px solid #174a5a;flex:0 0 auto}.hero-point b{display:block;margin-bottom:3px;color:#fff}.hero-point small{color:#8fa7bb}
.hero-preview{position:relative}.preview-glow{position:absolute;inset:10% 0 0 8%;filter:blur(55px);background:linear-gradient(130deg,rgba(0,220,208,.18),rgba(57,121,255,.16));border-radius:40px}.preview-shell{position:relative;border-radius:20px;padding:15px;background:#0b1723;border:1px solid #1a3c51;box-shadow:0 36px 90px rgba(0,0,0,.48);transform:perspective(1200px) rotateY(-2deg)}.preview-window{background:#f7f9fc;border-radius:14px;overflow:hidden;color:#0c1725}.preview-top{height:58px;background:#06111c;display:flex;align-items:center;padding:0 16px;gap:12px}.preview-top img{width:170px;height:46px;object-fit:contain}.preview-top span{margin-left:auto;color:#c9d7e5;font-size:12px}.preview-body{display:grid;grid-template-columns:145px 1fr;min-height:490px}.preview-side{background:#07121d;color:#b6c8d8;padding:18px 12px}.preview-side b{display:block;color:#45d9d0;margin-bottom:18px}.preview-menu{display:flex;flex-direction:column;gap:7px}.preview-menu span{padding:9px 10px;border-radius:8px;font-size:11px}.preview-menu span:first-child{background:#103149;color:#58c6ff}.preview-main{padding:18px}.preview-main h3{margin:0 0 4px;font-size:18px}.preview-main>p{margin:0 0 16px;color:#7c8b99;font-size:11px}.preview-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.preview-stat{background:white;border:1px solid #e2e8ee;border-radius:10px;padding:12px}.preview-stat strong{font-size:20px}.preview-stat small{display:block;color:#7a8997;font-size:9px;margin-top:3px}.preview-row{display:grid;grid-template-columns:1.1fr 1fr;gap:10px;margin-top:10px}.preview-card{background:#fff;border:1px solid #e2e8ee;border-radius:10px;padding:13px;min-height:160px}.preview-card h4{font-size:11px;margin:0 0 10px}.mini-line{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #edf1f5;font-size:10px}.mini-line:last-child{border:0}.mini-badge{padding:3px 7px;border-radius:99px;background:#fff1e8;color:#e76820}.bars{display:flex;align-items:flex-end;gap:7px;height:95px;margin-top:10px}.bar{flex:1;border-radius:5px 5px 0 0;background:linear-gradient(#1da9ef,#2368dc)}.bar:nth-child(2){height:64%;background:linear-gradient(#36c78a,#17a86d)}.bar:nth-child(3){height:52%;background:linear-gradient(#ffc13b,#ee9712)}.bar:nth-child(4){height:38%;background:linear-gradient(#a96be5,#7e48c9)}.bar:nth-child(5){height:47%;background:linear-gradient(#23c5d4,#1698ad)}.bar:nth-child(6){height:56%;background:linear-gradient(#ff6f91,#e9486d)}
.landing-features{background:#f5f8fb;color:#0d1826;padding:54px 4vw 70px}.features-wrap{max-width:1450px;margin:0 auto}.features-head{display:grid;grid-template-columns:.7fr 1.3fr;gap:30px;align-items:end;margin-bottom:26px}.features-head .ey{color:#159b9f;font-weight:900;font-size:12px;letter-spacing:.12em}.features-head h2{font-size:38px;line-height:1.1;margin:8px 0 0}.features-head h2 span{color:#13aeb8}.features-head p{color:#718090;line-height:1.7;max-width:700px}.feature-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.feature-card{background:#fff;border:1px solid #e3e9ee;border-radius:14px;padding:22px;box-shadow:0 15px 40px rgba(11,31,48,.06)}.feature-icon{width:42px;height:42px;border-radius:10px;background:#e8f8f8;color:#149ca3;display:grid;place-items:center;font-size:20px;margin-bottom:16px}.feature-card h3{font-size:14px;margin:0 0 8px}.feature-card p{font-size:12px;color:#758493;line-height:1.55;margin:0}.landing-footer{background:#06111b;color:#72879b;text-align:center;padding:22px;font-size:12px}.app-brand-img{width:165px;height:55px;object-fit:contain;object-position:left center;display:block}
@media(max-width:1180px){.landing-links{display:none}.landing-hero{grid-template-columns:1fr}.hero-preview{max-width:900px}.feature-grid{grid-template-columns:repeat(2,1fr)}.features-head{grid-template-columns:1fr}.landing-logo{max-width:60vw}.preview-shell{transform:none}}
@media(max-width:700px){.landing-nav{height:auto;padding:10px 16px;flex-wrap:wrap}.landing-logo{width:230px;max-width:70vw;height:62px}.landing-actions{margin-left:auto}.landing-actions .landing-btn:first-child{display:none}.landing-hero{padding:32px 20px}.hero-copy h1{font-size:45px}.hero-points{grid-template-columns:1fr}.preview-body{grid-template-columns:1fr}.preview-side{display:none}.preview-stats{grid-template-columns:repeat(2,1fr)}.preview-row{grid-template-columns:1fr}.feature-grid{grid-template-columns:1fr}.landing-features{padding:42px 20px}}
'''
anchor='@media(max-width:1100px)'
if css not in s:
    s=s.replace(anchor,css+'\n'+anchor,1)
landing=r'''
<section id="landingPage">
  <header class="landing-nav">
    <img src="assets/shiftpilot-logo.webp" alt="ShiftPilot – Dienstplanung. Smart. Effizient." class="landing-logo">
    <nav class="landing-links"><a href="#features">Funktionen</a><a href="#advantages">Vorteile</a><a href="#features">Lösung</a><a href="#contact">Kontakt</a></nav>
    <div class="landing-actions"><button class="landing-btn" onclick="openApp('overview')">Anmelden</button><button class="landing-btn primary" onclick="openApp('overview')">Dashboard öffnen →</button></div>
  </header>
  <main>
    <section class="landing-hero">
      <div class="hero-copy">
        <span class="hero-kicker">SMART. FLEXIBEL. ZUVERLÄSSIG.</span>
        <h1>Dienstplanung,<br>die <span>mitdenkt.</span><br>Für Teams, die<br>mehr bewegen.</h1>
        <p>ShiftPilot ist die smarte Lösung für moderne Dienstplanung. Weniger Aufwand, mehr Überblick – jeden Tag.</p>
        <div class="hero-buttons"><button class="landing-btn primary" onclick="openApp('schedule')">Jetzt testen →</button><button class="landing-btn" onclick="document.getElementById('features').scrollIntoView({behavior:'smooth'})">Funktionen entdecken →</button></div>
        <div class="hero-points" id="advantages"><div class="hero-point"><i>✓</i><div><b>Einfach & intuitiv</b><small>Schnell starten, sofort verstehen</small></div></div><div class="hero-point"><i>◷</i><div><b>Zeit sparen</b><small>Weniger Planung, mehr Zeit fürs Team</small></div></div><div class="hero-point"><i>◇</i><div><b>Fehler vermeiden</b><small>Automatische Prüfungen sorgen für Sicherheit</small></div></div><div class="hero-point"><i>▥</i><div><b>Immer im Blick</b><small>Alle Infos in Echtzeit – überall verfügbar</small></div></div></div>
      </div>
      <div class="hero-preview"><div class="preview-glow"></div><div class="preview-shell"><div class="preview-window"><div class="preview-top"><img src="assets/shiftpilot-logo.webp" alt="ShiftPilot"><span>Administrator · geschützter Bereich</span></div><div class="preview-body"><aside class="preview-side"><b>ShiftPilot</b><div class="preview-menu"><span>⌂ Übersicht</span><span>▣ Dienstplan</span><span>♧ Mitarbeiter</span><span>☼ Abwesenheiten</span><span>⚙ Einstellungen</span></div></aside><div class="preview-main"><h3>Guten Morgen, Administrator!</h3><p>Hier ist die Übersicht deiner Dienstplanung.</p><div class="preview-stats"><div class="preview-stat"><strong>24</strong><small>Aktive Mitarbeiter</small></div><div class="preview-stat"><strong>82%</strong><small>Planungsfortschritt</small></div><div class="preview-stat"><strong>18</strong><small>Offene Positionen</small></div><div class="preview-stat"><strong>0</strong><small>Warnungen</small></div></div><div class="preview-row"><div class="preview-card"><h4>Handlungsbedarf / Unterbesetzung</h4><div class="mini-line"><span>Mi · O1</span><span class="mini-badge">2 offen</span></div><div class="mini-line"><span>Do · OT2</span><span class="mini-badge">1 offen</span></div><div class="mini-line"><span>Sa · Teamleiter</span><span class="mini-badge">1 offen</span></div></div><div class="preview-card"><h4>Schichtverteilung</h4><div class="bars"><div class="bar" style="height:80%"></div><div class="bar"></div><div class="bar"></div><div class="bar"></div><div class="bar"></div><div class="bar"></div></div></div></div></div></div></div></div></div>
    </section>
    <section class="landing-features" id="features"><div class="features-wrap"><div class="features-head"><div><div class="ey">FUNKTIONEN</div><h2>Alles, was du für eine<br><span>effiziente Dienstplanung</span><br>brauchst</h2></div><p>Von der Schichtplanung über Mitarbeiterprofile und Abwesenheiten bis zur Auswertung: ShiftPilot bündelt die wichtigsten Abläufe in einer klaren, schnellen Oberfläche.</p></div><div class="feature-grid"><article class="feature-card"><div class="feature-icon">▣</div><h3>Intelligente Dienstplanung</h3><p>Erstelle Dienstpläne in wenigen Minuten – automatisch geprüft und optimal besetzt.</p></article><article class="feature-card"><div class="feature-icon">♧</div><h3>Mitarbeiterverwaltung</h3><p>Verwalte Team, Qualifikationen, Wochenstunden und Verfügbarkeiten an einem Ort.</p></article><article class="feature-card"><div class="feature-icon">☼</div><h3>Abwesenheiten im Blick</h3><p>Urlaub, Krankheit und Sperrzeiten werden direkt in der Planung berücksichtigt.</p></article><article class="feature-card"><div class="feature-icon">▥</div><h3>Aussagekräftige Berichte</h3><p>Mehr Überblick durch Kennzahlen, Auslastungen und Schichtverteilungen.</p></article><article class="feature-card"><div class="feature-icon">◇</div><h3>Sicher & zuverlässig</h3><p>Geschützter Zugriff, klare Rollen und eine solide Grundlage für DSGVO-konforme Prozesse.</p></article></div></div></section>
  </main>
  <footer class="landing-footer" id="contact">© 2026 ShiftPilot – Dienstplanung. Smart. Effizient.</footer>
</section>
'''
if '<section id="landingPage">' not in s:
    s=s.replace('<div class="app">',landing+'\n<div class="app" id="appShell" style="display:none">',1)
else:
    s=s.replace('<div class="app">','<div class="app" id="appShell" style="display:none">',1)
oldbrand='<div class="brand"><div class="logo">S</div><span>Shift<em>Pilot</em></span></div>'
newbrand='<div class="brand"><img src="assets/shiftpilot-logo.webp" alt="ShiftPilot" class="app-brand-img"></div>'
s=s.replace(oldbrand,newbrand,1)
js=r'''
function openApp(view='overview'){const landing=document.getElementById('landingPage'),app=document.getElementById('appShell');if(landing)landing.style.display='none';if(app)app.style.display='grid';switchView(view);window.scrollTo({top:0,behavior:'instant'});history.replaceState(null,'','#app')}
function openLanding(){const landing=document.getElementById('landingPage'),app=document.getElementById('appShell');if(app)app.style.display='none';if(landing)landing.style.display='block';history.replaceState(null,'','#home');window.scrollTo({top:0,behavior:'instant'})}
window.addEventListener('load',()=>{if(location.hash==='#app')openApp('overview')})
'''
anchorjs='renderLibrary();renderPlanEmployeePool();'
if 'function openApp(' not in s:
    s=s.replace(anchorjs,js+'\n'+anchorjs,1)
p.write_text(s,encoding='utf-8')
print('Homepage integriert')
