from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')

# CSS erweitern
css_anchor='.employee-drag.selected:after{content:"✓ AUSGEWÄHLT";position:absolute;right:8px;top:7px;color:#72f0d1;font-size:8px;font-weight:900;letter-spacing:.05em}'
css_extra='''\n.employee-drag{min-width:270px;align-items:flex-start}.employee-drag .employee-pool-info{min-width:0;flex:1}.employee-drag .employee-pool-info>small{padding-right:68px}.pool-detail-label{display:block;color:#7890aa;font-size:9px;font-weight:800;letter-spacing:.05em;text-transform:uppercase;margin-top:7px;margin-bottom:4px}.pool-shifts{display:flex;flex-wrap:wrap;gap:3px}.pool-shift-tag{font-size:9px;padding:2px 5px;border-radius:999px;background:#162b3d;border:1px solid #2a465f;color:#b9cee0}.pool-absence{margin-top:6px;font-size:10px;padding:4px 6px;border-radius:6px;border:1px solid #244237;background:#102b25;color:#8fe0c6}.pool-absence.has-absence{border-color:#76532a;background:#302414;color:#ffd08a}.pool-absence strong{font-weight:800}\n'''
if css_extra.strip() not in s:
    if css_anchor not in s: raise SystemExit('CSS-Anker nicht gefunden')
    s=s.replace(css_anchor,css_anchor+css_extra,1)

start=s.find('function renderPlanEmployeePool(){')
end=s.find('\nfunction renderCalendar()',start)
if start<0 or end<0: raise SystemExit('renderPlanEmployeePool nicht gefunden')
new_func=r'''function renderPlanEmployeePool(){const el=document.getElementById('planEmployeePool');if(!el)return;const q=(document.getElementById('planEmployeeSearch')?.value||'').toLowerCase();const weekDates=currentWeekDates().map(iso);const list=employees.filter(e=>e.status==='active'&&(`${e.first} ${e.last} ${e.personnelNo||''} ${e.role||''} ${(e.shifts||[]).join(' ')}`).toLowerCase().includes(q));el.innerHTML=list.map(e=>{const weekAbsences=absences.filter(a=>a.employeeId===e.id&&weekDates.includes(a.date)).sort((a,b)=>a.date.localeCompare(b.date));const absenceHtml=weekAbsences.length?`<div class="pool-absence has-absence"><strong>Abwesend:</strong> ${weekAbsences.map(a=>`${a.type} · ${new Date(a.date+'T00:00:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}`).join(' · ')}</div>`:`<div class="pool-absence">✓ Keine Abwesenheit in dieser Woche</div>`;const shifts=(e.shifts||[]).length?(e.shifts||[]).map(sh=>`<span class="pool-shift-tag">${sh}</span>`).join(''):'<span class="pool-shift-tag">Keine Freigabe</span>';return `<div class="employee-drag ${selectedPlanEmployeeId===e.id?'selected':''}" draggable="true" data-employee-id="${e.id}" aria-pressed="${selectedPlanEmployeeId===e.id}"><div class="avatar">${(e.first?.[0]||'')+(e.last?.[0]||'')}</div><div class="employee-pool-info"><b>${e.first} ${e.last}</b><small>${e.personnelNo||''} · ${e.role||e.employment||''}</small><span class="pool-detail-label">Mögliche Schichten</span><div class="pool-shifts">${shifts}</div>${absenceHtml}</div></div>`}).join('')||'<div class="empty" style="padding:8px">Keine aktiven Mitarbeiter gefunden.</div>';document.querySelectorAll('.employee-drag').forEach(card=>{card.addEventListener('click',()=>{selectedPlanEmployeeId=card.dataset.employeeId;renderPlanEmployeePool();const emp=employees.find(e=>e.id===selectedPlanEmployeeId);if(emp)showSaveToast('Mitarbeiter ausgewählt',`${emp.first} ${emp.last} ist aktuell ausgewählt.`)});card.addEventListener('dragstart',e=>{selectedPlanEmployeeId=card.dataset.employeeId;card.classList.add('dragging');e.dataTransfer.setData('text/plain','employee:'+card.dataset.employeeId)});card.addEventListener('dragend',()=>{card.classList.remove('dragging');renderPlanEmployeePool()})})}'''
s=s[:start]+new_func+s[end:]
p.write_text(s,encoding='utf-8')
print('Mitarbeiter-Pool um Schichtfreigaben und Wochen-Abwesenheiten erweitert')
