-- Real RPC grants and synthetic identities only. Every fixture and event is rolled back.
begin;
do $test$
declare owner_u uuid:=gen_random_uuid(); first_u uuid:=gen_random_uuid(); next_u uuid:=gen_random_uuid(); outsider_u uuid:=gen_random_uuid(); time_u uuid:=gen_random_uuid(); lead_u uuid:=gen_random_uuid(); uid uuid;
 company_ uuid; foreign_ uuid; site_ uuid; other_site uuid; first_e uuid; next_e uuid; outsider_e uuid;
 first_a uuid; next_a uuid; outsider_a uuid; draft_a uuid; b uuid; target_b uuid; item_id uuid:=gen_random_uuid(); internal_id uuid:=gen_random_uuid(); r_id uuid; old_r uuid;
 d date:=(now() at time zone 'Europe/Berlin')::date-2; rev bigint:=1; q jsonb; out_ jsonb; next_assignment uuid; denied integer:=0; snapshot_ jsonb; preview_ jsonb; job_ jsonb;
begin
 foreach uid in array array[owner_u,first_u,next_u,outsider_u,time_u,lead_u] loop
 insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values(uid,'authenticated','authenticated','handover-qa-'||uid||'@example.invalid','{}','{}',now(),now());end loop;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_u,'role','authenticated','aal','aal2')::text,true);perform set_config('request.jwt.claim.sub',owner_u::text,true);
 insert into public.companies(name,created_by) values('Handover Rollback QA',owner_u) returning id into company_;
 insert into public.companies(name,created_by) values('Foreign Handover QA',outsider_u) returning id into foreign_;
 insert into public.company_members(company_id,user_id,role,status,access_role,extra_permissions) values(company_,owner_u,'OWNER','ACTIVE','OWNER','{}'),(company_,time_u,'TIME_TRACKING','ACTIVE','EMPLOYEE',array['manage_time']),(company_,lead_u,'PLANNER','ACTIVE','TEAM_LEAD','{}') on conflict(company_id,user_id) do update set role=excluded.role,access_role=excluded.access_role;
 insert into public.employees(company_id,auth_user_id,first_name,last_name,personnel_no,access_status,shift_permissions,weekly_hours) values(company_,first_u,'First','Synthetic','QA-HO1','ACTIVE',array['HO1','HO2'],40) returning id into first_e;
 insert into public.employees(company_id,auth_user_id,first_name,last_name,personnel_no,access_status,shift_permissions,weekly_hours) values(company_,next_u,'Next','Synthetic','QA-HO2','ACTIVE',array['HO1','HO2'],40) returning id into next_e;
 insert into public.employees(company_id,auth_user_id,first_name,last_name,personnel_no,access_status,shift_permissions,weekly_hours) values(company_,outsider_u,'Outsider','Synthetic','QA-HO3','ACTIVE',array['HO3'],40) returning id into outsider_e;
 insert into public.company_locations(company_id,code,name) values(company_,'HO','QA Site') returning id into site_;
 insert into public.company_locations(company_id,code,name) values(company_,'HO-OTHER','Other QA Site') returning id into other_site;
 insert into public.shift_templates(company_id,code,name,default_start,default_end,site_id) values(company_,'HO1','Test first','06:00','14:00',site_),(company_,'HO2','Test next','14:00','22:00',site_),(company_,'HO3','Test foreign site','14:00','22:00',other_site);
 insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status,published_at) values(company_,first_e,'HO1',d::timestamp at time zone 'Europe/Berlin'+interval '6 hours',d::timestamp at time zone 'Europe/Berlin'+interval '14 hours','PUBLISHED',now()) returning id into first_a;
 insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status,published_at) values(company_,next_e,'HO2',d::timestamp at time zone 'Europe/Berlin'+interval '14 hours',d::timestamp at time zone 'Europe/Berlin'+interval '22 hours','PUBLISHED',now()) returning id into next_a;
 insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status,published_at) values(company_,outsider_e,'HO3',d::timestamp at time zone 'Europe/Berlin'+interval '14 hours',d::timestamp at time zone 'Europe/Berlin'+interval '22 hours','PUBLISHED',now()) returning id into outsider_a;
 insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status) values(company_,first_e,'HO1',(d+1)::timestamp at time zone 'Europe/Berlin'+interval '6 hours',(d+1)::timestamp at time zone 'Europe/Berlin'+interval '14 hours','DRAFT') returning id into draft_a;
 insert into public.time_entries(company_id,assignment_id,actual_start,actual_end,break_minutes,status,confirmed_at,confirmed_by) values(company_,first_a,d::timestamp at time zone 'Europe/Berlin'+interval '6 hours',d::timestamp at time zone 'Europe/Berlin'+interval '13 hours',0,'confirmed',now(),owner_u);
 set local role authenticated;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',first_u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',first_u::text,true);
 q:=public.shift_handover_action(company_,'OPEN',null,null,jsonb_build_object('assignment_id',first_a));b:=(q->>'id')::uuid;
 if(public.shift_handover_action(company_,'OPEN',null,null,jsonb_build_object('assignment_id',first_a))->>'id')::uuid<>b then raise exception 'Duplicate shared board';end if;
 begin perform public.shift_handover_action(company_,'OPEN',null,null,jsonb_build_object('assignment_id',next_a));raise exception 'Foreign employee shift opened';exception when insufficient_privilege then denied:=denied+1;end;
 begin perform public.shift_handover_action(company_,'OPEN',null,null,jsonb_build_object('assignment_id',draft_a));raise exception 'Draft shift opened';exception when insufficient_privilege then denied:=denied+1;end;
 begin perform public.shift_handover_bundle(foreign_,d,d+1);raise exception 'Other company read';exception when insufficient_privilege then denied:=denied+1;end;
 begin select to_jsonb(x) into q from public.shift_handover_items x;raise exception 'Direct table read accepted';exception when insufficient_privilege then denied:=denied+1;end;
 begin perform public.shift_handover_action(company_,'ADD',b,rev,jsonb_build_object('client_id',gen_random_uuid(),'kind','TASK','title','Missing deadline','critical',true));raise exception 'Critical validation missing';exception when check_violation then denied:=denied+1;end;
 begin perform public.shift_handover_action(company_,'ADD',b,rev,jsonb_build_object('client_id',gen_random_uuid(),'kind','TASK','title','Foreign responsible','responsible_employee_id',next_e));raise exception 'Responsible scope missing';exception when raise_exception then if sqlerrm not like 'Verantwortliche%' then raise;end if;denied:=denied+1;end;
 perform public.shift_handover_action(company_,'ADD',b,rev,jsonb_build_object('client_id',item_id,'kind','TASK','title','Tor kontrollieren','detail','Exported service','critical',true,'due_at',d::timestamp at time zone 'Europe/Berlin'+interval '8 hours','escalation','Diensthabende Einsatzleitung','report_include',true,'responsible_employee_id',first_e));rev:=rev+1;
 begin perform public.shift_handover_action(company_,'ADD',b,1,jsonb_build_object('client_id',gen_random_uuid(),'kind','TASK','title','Stale revision'));raise exception 'Stale accepted';exception when serialization_failure then denied:=denied+1;end;
 perform public.shift_handover_action(company_,'ADD',b,rev,jsonb_build_object('client_id',internal_id,'kind','NOTE','title','INTERNAL SECRET','detail','PRIVATE CONTENT','status','DONE'));rev:=rev+1;
 begin perform public.shift_handover_action(company_,'DRAFT',b,rev,'{}');raise exception 'Employee drafted report';exception when insufficient_privilege then denied:=denied+1;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',outsider_u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',outsider_u::text,true);
 q:=public.shift_handover_bundle(company_,d,d+1);if jsonb_array_length(q->'boards')<>0 then raise exception 'Foreign site board visible';end if;
 begin perform public.shift_handover_action(company_,'UPDATE',b,rev,jsonb_build_object('item_id',item_id,'title','Cross site'));raise exception 'Outsider modified board';exception when insufficient_privilege then denied:=denied+1;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',first_u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',first_u::text,true);
 q:=public.shift_handover_bundle(company_,d,d+1);if q->'boards'->0->'next_shift'->>'assignment_id'<>next_a::text then raise exception 'Cross-site or draft selected as next';end if;
 begin perform public.shift_handover_action(company_,'SEND',b,rev,jsonb_build_object('confirmed',true,'target_assignment_id',outsider_a));raise exception 'Wrong target accepted';exception when serialization_failure then denied:=denied+1;end;
 perform public.shift_handover_action(company_,'SEND',b,rev,jsonb_build_object('confirmed',true,'target_assignment_id',next_a));rev:=rev+1;
 begin perform public.shift_handover_action(company_,'ADD',b,rev,jsonb_build_object('client_id',gen_random_uuid(),'kind','TASK','title','Changed after send'));raise exception 'Sent board editable';exception when raise_exception then if sqlerrm not like 'Die gesendete%' then raise;end if;denied:=denied+1;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',next_u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',next_u::text,true);
 q:=public.shift_handover_bundle(company_,d,d+1);if jsonb_array_length(q->'boards')<>1 then raise exception 'Incoming team scope incorrect';end if;target_b:=(q->'boards'->0->>'id')::uuid;
 if jsonb_array_length(q->'boards'->0->'items')<>1 or q->'boards'->0->'items'->0->>'source_id'<>item_id::text or q->'boards'->0->'items'->0->>'responsible_employee_id' is not null then raise exception 'Carryforward incorrect';end if;
 if jsonb_array_length(q->'boards'->0->'reports')<>0 then raise exception 'Employee report access';end if;
 begin perform public.shift_handover_action(company_,'RECEIVE',target_b,(q->'boards'->0->>'revision')::bigint,jsonb_build_object('source_id',b));raise exception 'Unconfirmed receipt';exception when raise_exception then if sqlerrm not like 'Übernahme bitte%' then raise;end if;denied:=denied+1;end;
 perform public.shift_handover_action(company_,'RECEIVE',target_b,(q->'boards'->0->>'revision')::bigint,jsonb_build_object('source_id',b,'confirmed',true));rev:=rev+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',lead_u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',lead_u::text,true);
 q:=public.shift_handover_bundle(company_,d,d+1);if q->>'can_report'<>'false' then raise exception 'Lead read confirmed time';end if;
 begin perform public.shift_handover_action(company_,'DRAFT',b,rev,'{}');raise exception 'Lead bypassed time permission';exception when insufficient_privilege then denied:=denied+1;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_u,'role','authenticated','aal','aal2')::text,true);perform set_config('request.jwt.claim.sub',owner_u::text,true);
 out_:=public.shift_handover_action(company_,'DRAFT',b,rev,'{}');rev:=rev+1;r_id:=(out_->>'result_id')::uuid;old_r:=r_id;
 q:=public.shift_handover_bundle(company_,d,d+1);select x->'reports'->0->'snapshot' into snapshot_ from jsonb_array_elements(q->'boards')x where x->>'id'=b::text;
 if snapshot_->>'planned_minutes'<>'480' or snapshot_->>'confirmed_minutes'<>'420' or snapshot_->>'handover_received' is null or jsonb_array_length(snapshot_->'items')<>1 or snapshot_::text like '%PRIVATE CONTENT%' then raise exception 'Report content/evidence invalid: %',snapshot_;end if;
 perform public.shift_handover_action(company_,'APPROVE',b,rev,jsonb_build_object('report_id',r_id,'review_note','Inhalt sorgfältig geprüft','confirmed',true));rev:=rev+1;
 begin perform public.shift_handover_action(company_,'REJECT',b,rev,jsonb_build_object('report_id',r_id,'review_note','Approved rewrite'));raise exception 'Approved decision changed';exception when raise_exception then if sqlerrm not like 'Nur Berichtsentwürfe%' then raise;end if;denied:=denied+1;end;
 out_:=public.shift_handover_action(company_,'DRAFT',b,rev,'{}');rev:=rev+1;r_id:=(out_->>'result_id')::uuid;
 reset role;
 update public.time_entries set actual_end=actual_end-interval '1 hour' where assignment_id=first_a;
 set local role authenticated;
 begin perform public.shift_handover_action(company_,'APPROVE',b,rev,jsonb_build_object('report_id',r_id,'review_note','Changed evidence','confirmed',true));raise exception 'Changed basis approved';exception when serialization_failure then denied:=denied+1;end;
 perform public.shift_handover_action(company_,'REJECT',b,rev,jsonb_build_object('report_id',r_id,'review_note','Zeitnachweis inzwischen geändert'));rev:=rev+1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',time_u,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',time_u::text,true);
 begin perform public.shift_handover_bundle(company_,d,d+1);raise exception 'Time only read board';exception when insufficient_privilege then denied:=denied+1;end;
 reset role;
 begin update public.shift_handover_reports set review_note='Rewrite' where id=old_r;raise exception 'Approved snapshot mutated';exception when raise_exception then if sqlerrm not like 'Entschiedene Leistungsberichte%' then raise;end if;denied:=denied+1;end;
 if (select snapshot from public.shift_handover_reports where id=old_r) is distinct from snapshot_ then raise exception 'Approved snapshot changed after correction';end if;
 if (select count(*) from private.sf_erasure_relations(company_,array[first_e],array[first_a],array[]::uuid[],array[]::uuid[],array[]::uuid[],array[]::uuid[],array[]::uuid[]) where table_name in ('shift_handover_items','shift_handover_events','shift_handover_reports'))<>3 then raise exception 'Erasure manifest missing';end if;
 if (select count(*) from pg_trigger where tgname='a00_employee_erasure_freeze' and tgrelid in('public.shift_handovers'::regclass,'public.shift_handover_items'::regclass,'public.shift_handover_reports'::regclass,'public.shift_handover_events'::regclass))<>4 then raise exception 'Erasure freeze missing';end if;
 if denied<>17 then raise exception 'Deny checks incomplete: %',denied;end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_u,'role','service_role','aal','aal2')::text,true);perform set_config('request.jwt.claim.sub',owner_u::text,true);perform set_config('request.jwt.claim.role','service_role',true);
 preview_:=public.owner_employee_erasure_preview(company_,first_e);
 if coalesce((preview_->'counts'->>'shift_handover_items')::integer,0)<>3 or coalesce((preview_->'counts'->>'shift_handover_reports')::integer,0)<>2 then raise exception 'Erasure does not include carried task/report content: %',preview_->'counts';end if;
 job_:=public.server_stage_employee_erasure(company_,first_e,owner_u,gen_random_uuid(),'First Synthetic',true,preview_->>'fingerprint');
 begin update public.shift_handover_items set detail='Late write' where id=item_id;raise exception 'Pending erasure edited task';exception when raise_exception then if sqlerrm not like 'Für diesen Mitarbeiter läuft%' then raise;end if;end;
 perform public.server_commit_employee_erasure((job_->>'job_id')::uuid,owner_u);
 if exists(select 1 from public.employees where id=first_e) or exists(select 1 from public.shift_handover_items where employee_id=first_e) or exists(select 1 from public.shift_handover_reports where board_id=b) then raise exception 'Erasure left personal tasks/reports';end if;
 if not exists(select 1 from public.shift_handovers where id=target_b) or not exists(select 1 from public.employees where id=next_e) then raise exception 'Erasure lost colleague board/profile';end if;
 preview_:=public.owner_employee_erasure_preview(company_,next_e);
 job_:=public.server_stage_employee_erasure(company_,next_e,owner_u,gen_random_uuid(),'Next Synthetic',true,preview_->>'fingerprint');
 perform public.server_commit_employee_erasure((job_->>'job_id')::uuid,owner_u);
 if not exists(select 1 from public.shift_handovers where id=b and employee_id is null and received_at is not null) then raise exception 'Receipt not anonymized/preserved';end if;

 set constraints all immediate;
 perform set_config('app.handover_qa_result','PASS: shared published duty, private employee/site/company scope, task deadline/responsibility, exact next shift, carryforward/receipt, time permission, internal exclusion, confirmed evidence, immutable version, stale basis/revision, actual erasure/freeze/receipt anonymization and 17 deny cases. All synthetic data rolled back.',true);
end $test$;
select current_setting('app.handover_qa_result') result;
rollback;
