-- Synthetic fixture only; all data and audit events roll back.
begin;
do $test$
declare manager_ uuid:=gen_random_uuid();employee_user uuid:=gen_random_uuid();other_user uuid:=gen_random_uuid();time_user uuid:=gen_random_uuid();uid uuid;
 company_ uuid;foreign_company uuid;employee_ uuid;other_employee uuid;w jsonb;second_ jsonb;body_ jsonb;client_ uuid:=gen_random_uuid();d date:=(date_trunc('month',now())+interval '2 months')::date+10;
 wish_ uuid;rev integer;denied integer:=0;old_fingerprint text;result_ jsonb;
begin
 foreach uid in array array[manager_,employee_user,other_user,time_user] loop
  insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) values(uid,'authenticated','authenticated','wish-qa-'||uid||'@example.invalid','{}','{}',now(),now());
 end loop;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',manager_,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',manager_::text,true);
 insert into public.companies(name,created_by) values('Wunschplanung Rollback QA',manager_) returning id into company_;
 insert into public.companies(name,created_by) values('Wunschplanung Foreign QA',other_user) returning id into foreign_company;
 insert into public.company_members(company_id,user_id,role,status) values(company_,manager_,'OWNER','ACTIVE'),(foreign_company,other_user,'OWNER','ACTIVE'),(company_,time_user,'TIME_TRACKING','ACTIVE') on conflict(company_id,user_id) do update set role=excluded.role,status='ACTIVE';
 insert into public.employees(company_id,auth_user_id,first_name,last_name,personnel_no,access_status,shift_permissions,weekly_hours) values(company_,employee_user,'Synthetic','Adler','QA-1','ACTIVE',array['QA-WISH'],40) returning id into employee_;
 insert into public.employees(company_id,auth_user_id,first_name,last_name,personnel_no,access_status,shift_permissions,weekly_hours) values(foreign_company,other_user,'Synthetic','Foreign','QA-2','ACTIVE',array['QA-WISH'],40) returning id into other_employee;
 insert into public.shift_templates(company_id,code,name,default_start,default_end) values(company_,'QA-WISH','Testdienst','06:00','14:00');
 body_:=jsonb_build_object('client_id',client_,'employee_id',employee_,'kind','OFF','from',d,'to',d,'priority','IMPORTANT','note','Synthetic wish');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee_user,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',employee_user::text,true);
 set local role authenticated;
 w:=public.planning_wish_action(company_,'SUBMIT',null,null,body_);wish_:=(w->>'id')::uuid;
 if w->>'status'<>'PENDING' then raise exception 'Submission failed';end if;
 second_:=public.planning_wish_action(company_,'SUBMIT',null,null,body_);if second_->>'id'<>w->>'id' then raise exception 'Retry created duplicate';end if;
 begin perform public.planning_wish_action(company_,'APPROVE',wish_,1,'{}');raise exception 'Employee approved own wish';exception when insufficient_privilege then denied:=denied+1;end;
 begin update public.planning_wishes set status='PROMISED' where id=wish_;raise exception 'Direct update accepted';exception when insufficient_privilege then denied:=denied+1;end;
 begin perform public.planning_wish_action(foreign_company,'SUBMIT',null,null,body_||jsonb_build_object('employee_id',other_employee,'client_id',gen_random_uuid()));raise exception 'Foreign submission accepted';exception when insufficient_privilege then denied:=denied+1;end;
 begin perform public.planning_wish_bundle(foreign_company,date_trunc('month',d)::date);raise exception 'Foreign bundle accepted';exception when insufficient_privilege then denied:=denied+1;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',manager_,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',manager_::text,true);
 old_fingerprint:=private.sf_month_optimization_snapshot(company_,date_trunc('month',d)::date)->>'fingerprint';
 w:=public.planning_wish_action(company_,'APPROVE',wish_,1,'{"reason":"Besetzung bleibt möglich"}');
 if w->>'status'<>'PROMISED' then raise exception 'Promise approval failed';end if;
 if private.sf_month_optimization_snapshot(company_,date_trunc('month',d)::date)->>'fingerprint'=old_fingerprint then raise exception 'Wish did not invalidate plan fingerprint';end if;
 begin perform public.planning_wish_action(company_,'REJECT',wish_,1,'{"reason":"Stale revision"}');raise exception 'Stale revision accepted';exception when serialization_failure then denied:=denied+1;end;
 begin perform public.planning_wish_action(company_,'RELEASE',wish_,2,'{"confirmed":true}');raise exception 'Manager released employee promise';exception when insufficient_privilege then denied:=denied+1;end;
 begin insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status) values(company_,employee_,'QA-WISH',(d-1)::timestamp at time zone 'Europe/Berlin'+interval '22 hours',d::timestamp at time zone 'Europe/Berlin'+interval '6 hours','DRAFT');raise exception 'Night carry-in ignored';exception when check_violation then if sqlerrm not like 'Geschützte Freizeitzusage%' then raise;end if;denied:=denied+1;end;
 w:=public.planning_wish_action(company_,'ASK_RELEASE',wish_,2,'{"reason":"Kurzfristige Besetzung prüfen"}');if w->>'status'<>'RELEASE_REQUESTED' then raise exception 'Release request failed';end if;
 begin insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status) values(company_,employee_,'QA-WISH',d::timestamp at time zone 'Europe/Berlin'+interval '6 hours',d::timestamp at time zone 'Europe/Berlin'+interval '14 hours','DRAFT');raise exception 'Pending release removed protection';exception when check_violation then if sqlerrm not like 'Geschützte Freizeitzusage%' then raise;end if;denied:=denied+1;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employee_user,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',employee_user::text,true);
 w:=public.planning_wish_action(company_,'KEEP',wish_,3,'{}');if w->>'status'<>'PROMISED' then raise exception 'Keep failed';end if;
 begin perform public.planning_wish_action(company_,'RELEASE',wish_,4,'{}');raise exception 'Unconfirmed release accepted';exception when raise_exception then if sqlerrm not like 'Bitte die Freigabe%' then raise;end if;denied:=denied+1;end;
 w:=public.planning_wish_action(company_,'RELEASE',wish_,4,'{"confirmed":true}');if w->>'status'<>'RELEASED' then raise exception 'Employee release failed';end if;
 result_:=public.planning_wish_bundle(company_,date_trunc('month',d)::date);if jsonb_array_length(result_->'employees')<>1 or jsonb_array_length(result_->'wishes')<>1 then raise exception 'Employee scope failed';end if;
 if jsonb_array_length(result_->'wishes'->0->'events')<>5 then raise exception 'History missing';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',time_user,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',time_user::text,true);
 begin perform public.planning_wish_bundle(company_,date_trunc('month',d)::date);raise exception 'Time-only role read wishes';exception when insufficient_privilege then denied:=denied+1;end;
 if exists(select 1 from public.planning_wishes where id=wish_) then raise exception 'RLS allowed time-only access';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',other_user,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',other_user::text,true);
 if exists(select 1 from public.planning_wishes where id=wish_) then raise exception 'RLS allowed cross company access';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',manager_,'role','authenticated')::text,true);perform set_config('request.jwt.claim.sub',manager_::text,true);
 insert into public.shift_assignments(company_id,employee_id,shift_code,starts_at,ends_at,status) values(company_,employee_,'QA-WISH',d::timestamp at time zone 'Europe/Berlin'+interval '6 hours',d::timestamp at time zone 'Europe/Berlin'+interval '14 hours','DRAFT');
 w:=public.planning_wish_action(company_,'SUBMIT',null,null,body_||jsonb_build_object('client_id',gen_random_uuid()));
 begin perform public.planning_wish_action(company_,'APPROVE',(w->>'id')::uuid,1,'{}');raise exception 'Promise approved over existing duty';exception when raise_exception then if sqlerrm not like 'Freizeitzusage blockiert%' then raise;end if;denied:=denied+1;end;
 begin perform public.planning_wish_action(company_,'REJECT',(w->>'id')::uuid,1,'{}');raise exception 'Rejection without reason';exception when raise_exception then if sqlerrm not like 'Bitte die Ablehnung%' then raise;end if;denied:=denied+1;end;
 perform public.planning_wish_action(company_,'REJECT',(w->>'id')::uuid,1,'{"reason":"Vorhandener Dienst muss zuerst neu besetzt werden"}');
 if has_function_privilege('anon','public.planning_wish_action(uuid,text,uuid,integer,jsonb)','EXECUTE') then raise exception 'Anonymous execute granted';end if;
 if denied<>12 then raise exception 'Missing deny checks: %',denied;end if;
 reset role;
 set constraints all immediate;
 if (select count(*) from private.sf_erasure_relations(company_,array[employee_],array[]::uuid[],array[]::uuid[],array[]::uuid[],array[]::uuid[],array[]::uuid[],array[]::uuid[]) where table_name in ('planning_wishes','planning_wish_events'))<>2 then raise exception 'Wish erasure manifest incomplete';end if;
 if (select count(*) from pg_trigger where tgname='a00_employee_erasure_freeze' and tgrelid in ('public.planning_wishes'::regclass,'public.planning_wish_events'::regclass))<>2 then raise exception 'Wish erasure freeze incomplete';end if;
 perform set_config('app.wish_qa_result','PASS: submission/retry, manager promise, night carry-in, release request retains protection, employee keeps/releases, revision guard, fingerprint, reason, history, RLS employee erasure manifest/freeze and 12 deny cases. Fixtures rolled back.',true);
end $test$;
select current_setting('app.wish_qa_result') result;
rollback;
