-- Public SECURITY INVOKER RPCs and RLS policies execute these private helpers
-- with the caller's role. Keep them unavailable to anonymous callers while
-- restoring the minimum EXECUTE privileges required by authenticated users.
grant usage on schema private to authenticated;

revoke all on function
  private.can_access_personnel_storage(text),
  private.employee_cancel_shift_swap_impl(uuid),
  private.employee_claim_shift_marketplace_impl(uuid,text),
  private.employee_create_shift_swap_impl(uuid,uuid,text),
  private.employee_list_disruption_offers_impl(),
  private.employee_list_shift_marketplace_impl(),
  private.employee_list_shift_swap_candidates_impl(uuid),
  private.employee_list_shift_swaps_impl(),
  private.employee_offer_shift_marketplace_impl(uuid,text),
  private.employee_respond_disruption_offer_impl(uuid,text,text),
  private.employee_respond_shift_swap_impl(uuid,text,text),
  private.employee_submit_absence_request_impl(text,date,date,text,boolean,time,time,text),
  private.is_company_creator(uuid),
  private.manager_add_personnel_note_impl(uuid,text,text,text),
  private.manager_cancel_disruption_impl(uuid,text),
  private.manager_create_disruption_impl(uuid,uuid,text,text),
  private.manager_delete_personnel_document_impl(uuid),
  private.manager_delete_personnel_qualification_impl(uuid),
  private.manager_list_disruption_candidates_impl(uuid),
  private.manager_list_disruptions_impl(uuid),
  private.manager_list_shift_marketplace_impl(uuid),
  private.manager_personnel_deadline_dashboard_impl(uuid),
  private.manager_personnel_file_bundle_impl(uuid),
  private.manager_register_personnel_document_impl(uuid,text,text,text,text,text,bigint,date,date,text),
  private.manager_resolve_legacy_assignment_reviews_impl(uuid,uuid[],text),
  private.manager_review_absence_request_impl(uuid,text,text),
  private.manager_review_shift_swap_impl(uuid,text,text),
  private.manager_save_personnel_qualification_impl(uuid,uuid,text,text,text,text,date,date,text),
  private.manager_send_disruption_offers_impl(uuid,uuid[]),
  private.manager_time_report_bundle_v2_impl(uuid,date,uuid),
  private.manager_update_personnel_details_impl(uuid,text,text,text,text,date,text,text,text),
  private.reset_schedule_impl(uuid,text),
  private.sf_is_manager(uuid,boolean)
from public, anon;

grant execute on function
  private.can_access_personnel_storage(text),
  private.employee_cancel_shift_swap_impl(uuid),
  private.employee_claim_shift_marketplace_impl(uuid,text),
  private.employee_create_shift_swap_impl(uuid,uuid,text),
  private.employee_list_disruption_offers_impl(),
  private.employee_list_shift_marketplace_impl(),
  private.employee_list_shift_swap_candidates_impl(uuid),
  private.employee_list_shift_swaps_impl(),
  private.employee_offer_shift_marketplace_impl(uuid,text),
  private.employee_respond_disruption_offer_impl(uuid,text,text),
  private.employee_respond_shift_swap_impl(uuid,text,text),
  private.employee_submit_absence_request_impl(text,date,date,text,boolean,time,time,text),
  private.is_company_creator(uuid),
  private.manager_add_personnel_note_impl(uuid,text,text,text),
  private.manager_cancel_disruption_impl(uuid,text),
  private.manager_create_disruption_impl(uuid,uuid,text,text),
  private.manager_delete_personnel_document_impl(uuid),
  private.manager_delete_personnel_qualification_impl(uuid),
  private.manager_list_disruption_candidates_impl(uuid),
  private.manager_list_disruptions_impl(uuid),
  private.manager_list_shift_marketplace_impl(uuid),
  private.manager_personnel_deadline_dashboard_impl(uuid),
  private.manager_personnel_file_bundle_impl(uuid),
  private.manager_register_personnel_document_impl(uuid,text,text,text,text,text,bigint,date,date,text),
  private.manager_resolve_legacy_assignment_reviews_impl(uuid,uuid[],text),
  private.manager_review_absence_request_impl(uuid,text,text),
  private.manager_review_shift_swap_impl(uuid,text,text),
  private.manager_save_personnel_qualification_impl(uuid,uuid,text,text,text,text,date,date,text),
  private.manager_send_disruption_offers_impl(uuid,uuid[]),
  private.manager_time_report_bundle_v2_impl(uuid,date,uuid),
  private.manager_update_personnel_details_impl(uuid,text,text,text,text,date,text,text,text),
  private.reset_schedule_impl(uuid,text),
  private.sf_is_manager(uuid,boolean)
to authenticated;
