create index if not exists absences_employee_fk_idx on public.absences(employee_id);
create index if not exists audit_events_actor_fk_idx on public.audit_events(actor_id);
create index if not exists companies_created_by_fk_idx on public.companies(created_by);
create index if not exists company_members_user_fk_idx on public.company_members(user_id);
create index if not exists compliance_check_runs_change_fk_idx on public.compliance_check_runs(change_request_id);
create index if not exists compliance_check_runs_company_fk_idx on public.compliance_check_runs(company_id);
create index if not exists compliance_findings_change_fk_idx on public.compliance_findings(change_request_id);
create index if not exists compliance_findings_run_fk_idx on public.compliance_findings(check_run_id);
create index if not exists compliance_findings_company_fk_idx on public.compliance_findings(company_id);
create index if not exists legacy_imports_user_fk_idx on public.legacy_imports(user_id);
create index if not exists plan_publications_published_by_fk_idx on public.plan_publications(published_by);
create index if not exists shift_assignments_created_by_fk_idx on public.shift_assignments(created_by);
create index if not exists shift_assignments_employee_fk_idx on public.shift_assignments(employee_id);
create index if not exists shift_assignments_last_change_fk_idx on public.shift_assignments(last_change_request_id);
create index if not exists approvals_company_fk_idx on public.shift_change_approvals(company_id);
create index if not exists approvals_decided_by_fk_idx on public.shift_change_approvals(decided_by);
create index if not exists change_requests_employee_fk_idx on public.shift_change_requests(employee_id);
create index if not exists change_requests_requested_by_fk_idx on public.shift_change_requests(requested_by);
create index if not exists time_entries_company_fk_idx on public.time_entries(company_id);
create index if not exists time_entries_updated_by_fk_idx on public.time_entries(updated_by);

drop policy if exists shift_templates_write on public.shift_templates;
create policy shift_templates_insert on public.shift_templates for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=shift_templates.company_id and cm.user_id=(select auth.uid()) and cm.status='ACTIVE' and cm.role in ('OWNER','ADMIN','PLANNER')));
create policy shift_templates_update on public.shift_templates for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_templates.company_id and cm.user_id=(select auth.uid()) and cm.status='ACTIVE' and cm.role in ('OWNER','ADMIN','PLANNER'))) with check (exists(select 1 from public.company_members cm where cm.company_id=shift_templates.company_id and cm.user_id=(select auth.uid()) and cm.status='ACTIVE' and cm.role in ('OWNER','ADMIN','PLANNER')));
create policy shift_templates_delete on public.shift_templates for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_templates.company_id and cm.user_id=(select auth.uid()) and cm.status='ACTIVE' and cm.role in ('OWNER','ADMIN','PLANNER')));

drop policy if exists global_staff_write on public.global_staffing_requirements;
create policy global_staff_insert on public.global_staffing_requirements for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=global_staffing_requirements.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy global_staff_update on public.global_staffing_requirements for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=global_staffing_requirements.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=global_staffing_requirements.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy global_staff_delete on public.global_staffing_requirements for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=global_staffing_requirements.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists daily_staff_write on public.daily_staffing_overrides;
create policy daily_staff_insert on public.daily_staffing_overrides for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=daily_staffing_overrides.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy daily_staff_update on public.daily_staffing_overrides for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=daily_staffing_overrides.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=daily_staffing_overrides.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy daily_staff_delete on public.daily_staffing_overrides for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=daily_staffing_overrides.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists employees_write on public.employees;
create policy employees_insert on public.employees for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=employees.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy employees_update on public.employees for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=employees.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=employees.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy employees_delete on public.employees for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=employees.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists absences_write on public.absences;
create policy absences_insert on public.absences for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=absences.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy absences_update on public.absences for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=absences.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=absences.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy absences_delete on public.absences for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=absences.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists publications_write on public.plan_publications;
create policy publications_insert on public.plan_publications for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=plan_publications.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy publications_update on public.plan_publications for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=plan_publications.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=plan_publications.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy publications_delete on public.plan_publications for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=plan_publications.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists assignments_write on public.shift_assignments;
create policy assignments_insert on public.shift_assignments for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=shift_assignments.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy assignments_update on public.shift_assignments for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_assignments.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=shift_assignments.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy assignments_delete on public.shift_assignments for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_assignments.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists time_entries_write on public.time_entries;
create policy time_entries_insert on public.time_entries for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=time_entries.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy time_entries_update on public.time_entries for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=time_entries.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=time_entries.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy time_entries_delete on public.time_entries for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=time_entries.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists compliance_policy_write on public.company_compliance_policy;
create policy compliance_policy_insert on public.company_compliance_policy for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=company_compliance_policy.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN') and cm.status='ACTIVE'));
create policy compliance_policy_update on public.company_compliance_policy for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=company_compliance_policy.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=company_compliance_policy.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN') and cm.status='ACTIVE'));
create policy compliance_policy_delete on public.company_compliance_policy for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=company_compliance_policy.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN') and cm.status='ACTIVE'));

drop policy if exists change_requests_write on public.shift_change_requests;
create policy change_requests_insert on public.shift_change_requests for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=shift_change_requests.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy change_requests_update on public.shift_change_requests for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_change_requests.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=shift_change_requests.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy change_requests_delete on public.shift_change_requests for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_change_requests.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists check_runs_write on public.compliance_check_runs;
create policy check_runs_insert on public.compliance_check_runs for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=compliance_check_runs.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy check_runs_update on public.compliance_check_runs for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=compliance_check_runs.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=compliance_check_runs.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy check_runs_delete on public.compliance_check_runs for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=compliance_check_runs.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists findings_write on public.compliance_findings;
create policy findings_insert on public.compliance_findings for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=compliance_findings.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy findings_update on public.compliance_findings for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=compliance_findings.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=compliance_findings.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy findings_delete on public.compliance_findings for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=compliance_findings.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));

drop policy if exists approvals_write on public.shift_change_approvals;
create policy approvals_insert on public.shift_change_approvals for insert to authenticated with check (exists(select 1 from public.company_members cm where cm.company_id=shift_change_approvals.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy approvals_update on public.shift_change_approvals for update to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_change_approvals.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE')) with check (exists(select 1 from public.company_members cm where cm.company_id=shift_change_approvals.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
create policy approvals_delete on public.shift_change_approvals for delete to authenticated using (exists(select 1 from public.company_members cm where cm.company_id=shift_change_approvals.company_id and cm.user_id=(select auth.uid()) and cm.role in ('OWNER','ADMIN','PLANNER') and cm.status='ACTIVE'));
;
